/**
 * Local Keyword Modifier Expander — pure logic (zero imports, zero network, zero DOM).
 *
 * Combines a seed keyword with location modifiers to produce geo-targeted
 * keyword IDEAS. Template/word-bank based — nothing is generated by an AI
 * model, and no live local search-volume data is included. Every output is
 * an idea seed the user must verify in a keyword research tool.
 *
 * Word banks (sizes documented):
 *   MODIFIER_TEMPLATES: 6 fixed templates ("{seed} in {loc}", ...)
 *   BUILT_IN_CITIES: 24 cities across the US, UK, CA and AU, used when the
 *   user leaves the locations field empty.
 *
 * Custom locations: 1-50 place names, each 1-60 chars, deduped
 * case-insensitively (first-seen spelling kept). Unicode place names are
 * supported.
 *
 * Determinism: same inputs -> identical outputs (locations keep input
 * order, templates apply in fixed order).
 */

export const MAX_LOCATIONS = 50;
export const MAX_LOCATION_CHARS = 60;

/** Fixed location-modifier templates. Bank size: 6. */
export const MODIFIER_TEMPLATES: string[] = [
  "{seed} in {loc}",
  "{loc} {seed}",
  "best {seed} in {loc}",
  "affordable {seed} in {loc}",
  "{seed} {loc} prices",
  "{seed} near {loc}",
];

/**
 * Built-in city list (US/UK/CA/AU) used when the user provides no custom
 * locations. Bank size: 24.
 */
export const BUILT_IN_CITIES: string[] = [
  "New York",
  "Los Angeles",
  "Chicago",
  "Houston",
  "Phoenix",
  "Philadelphia",
  "San Antonio",
  "San Diego",
  "Dallas",
  "Austin",
  "Seattle",
  "Denver",
  "Miami",
  "Atlanta",
  "Boston",
  "Orlando",
  "London",
  "Manchester",
  "Birmingham",
  "Leeds",
  "Toronto",
  "Vancouver",
  "Sydney",
  "Melbourne",
];

/**
 * Parse the locations input (textarea string or string array).
 * Empty/missing input -> null (caller falls back to BUILT_IN_CITIES).
 */
function parseLocations(
  raw: unknown,
): { locations: string[] | null; error: string | null } {
  if (raw === undefined || raw === null) return { locations: null, error: null };

  let entries: unknown[];
  if (typeof raw === "string") {
    if (raw.trim() === "") return { locations: null, error: null };
    entries = raw.split(/\r?\n/);
  } else if (Array.isArray(raw)) {
    if (raw.length === 0) return { locations: null, error: null };
    entries = raw;
  } else {
    return { locations: null, error: "Locations must be text (one place per line) or a list of place names." };
  }

  const seen = new Set<string>();
  const locations: string[] = [];
  for (const entry of entries) {
    if (typeof entry !== "string" && typeof entry !== "number") {
      return { locations: null, error: "Locations must contain text only." };
    }
    const place = String(entry).trim();
    if (!place) continue; // skip blank lines
    if (place.length > MAX_LOCATION_CHARS) {
      return {
        locations: null,
        error: `Each location must be ${MAX_LOCATION_CHARS} characters or fewer ("${place.slice(0, 30)}..." is too long).`,
      };
    }
    const key = place.toLowerCase();
    if (!seen.has(key)) {
      seen.add(key);
      locations.push(place);
    }
  }
  if (locations.length === 0) return { locations: null, error: null }; // blank-only input -> default list
  if (locations.length > MAX_LOCATIONS) {
    return {
      locations: null,
      error: `Use at most ${MAX_LOCATIONS} locations (you entered ${locations.length}).`,
    };
  }
  return { locations, error: null };
}

/**
 * Run the expander. Values in:
 *   seedKeyword: string            (required, 2-100 chars)
 *   locations: string | string[]   (optional; defaults to BUILT_IN_CITIES)
 *
 * Values out:
 *   expansions: string[]
 *   count: number
 */
export function runTool(values: Record<string, unknown>): {
  ok: boolean;
  values?: Record<string, unknown>;
  error?: string;
} {
  const v = values ?? {};

  const seedRaw = v["seedKeyword"];
  const seed = typeof seedRaw === "string" ? seedRaw.trim() : "";
  if (!seed) {
    return { ok: false, error: "Seed keyword is required." };
  }
  if (seed.length < 2 || seed.length > 100) {
    return { ok: false, error: "Seed keyword must be 2-100 characters." };
  }

  const parsed = parseLocations(v["locations"]);
  if (parsed.error) return { ok: false, error: parsed.error };
  const locations = parsed.locations ?? [...BUILT_IN_CITIES];

  const expansions: string[] = [];
  for (const loc of locations) {
    for (const template of MODIFIER_TEMPLATES) {
      expansions.push(
        template.replace(/\{seed\}/g, seed).replace(/\{loc\}/g, loc),
      );
    }
  }

  return {
    ok: true,
    values: { expansions, count: expansions.length },
  };
}
