import type { ToolInput, ToolOutput } from '../../../src/lib/registry/types.ts';
import type { ToolContent } from '../../../src/templates/types.ts';
import { TRACKER_ITEMS } from './logic.ts';

export const inputs: ToolInput[] = [];

export const outputs: ToolOutput[] = [];

export const trackerMode: 'checklist' | 'library' = 'library';

export const trackerItems = TRACKER_ITEMS;

export const content: ToolContent = {
  title: 'Faceless Video AI Prompts',
  description:
    'Browse 48 free faceless video AI prompts: human-written templates for documentaries, explainers, listicles, and stories. Copy a prompt and create today.',
  howTo: [
    'Browse the 4 categories: documentary, explainer, listicle, and story — 12 prompts each.',
    'Click any prompt to see its full text with placeholders like [TOPIC] highlighted.',
    'Replace the placeholders with your topic, length, audience, and facts.',
    'Copy the finished prompt and paste it into your own AI tool (ChatGPT, Claude, Gemini, etc.).',
    'Mark prompts you have tried so you can track which templates work best for your channel.',
  ],
  methodology:
    'This is a fixed, curated library of 48 human-written prompt templates across 4 faceless-video categories. Nothing is generated by an AI model at runtime — the page displays the templates, and you run them in your own AI tool. Many prompts include honesty guards (use only facts you provide) so AI-drafted scripts do not invent facts as facts.',
  faqs: [
    {
      question: 'What is the best faceless video ai prompts?',
      answer:
        'The best prompts spell out the structure you want: hook, beats, B-roll cues, and closing. This free pack gives you 48 human-written templates across documentary, explainer, listicle, and story formats with exactly that structure built in.',
    },
    {
      question: 'Is there a free faceless video ai prompts?',
      answer:
        'Yes — all 48 prompt templates in this pack are free to browse and copy, no signup needed. You run them in your own AI tool to draft the scripts.',
    },
    {
      question: 'How to use faceless video ai prompts?',
      answer:
        'Pick the template for your video style, fill in the placeholders (topic, length, audience, facts), paste it into your AI tool, then review the draft before recording. Always verify names, dates, and claims yourself — AI drafts need a human fact-check.',
    },
    {
      question: 'How does a faceless video ai prompts work?',
      answer:
        'A prompt tells an AI tool what kind of script to write and how to structure it. This page does not run any AI itself — it is a fixed library of ready-made prompt templates you copy, customize, and run in your own AI tool.',
    },
    {
      question: 'How does the faceless video ai prompts work?',
      answer:
        'Enter your details using the inputs above and the faceless video ai prompts calculates everything instantly in your browser. No data leaves your device, and you get results the moment you change any value.',
    },
    {
      question: 'Is the faceless video ai prompts free to use?',
      answer:
        'Yes - this faceless video ai prompts is completely free with no signup, no account, and no usage limits. It runs 100% in your browser.',
    },
    {
      question: 'What is a faceless video ai prompts?',
      answer:
        'A faceless video ai prompts is a free online tool that gives you quick, accurate results without spreadsheets or manual math. This version runs entirely in your browser for instant, private results.',
    },
  ],
  assumptions: [
    'Fixed library of 48 human-written templates — nothing is generated or personalized at runtime.',
    'Templates use placeholders (e.g. [TOPIC], [FACTS]); you fill them in before use.',
    'You need your own AI tool account to turn the templates into scripts.',
    'Templates are starting points — verify every fact in the output before publishing.',
  ],
  jsonLd: [
    {
      '@type': 'WebPage',
      name: 'Faceless Video AI Prompts 2026',
      url: 'https://husnainblogger.com/tools/ai-workflows/faceless-video-prompt-pack/',
      description:
    'Browse 48 free faceless video AI prompts: human-written templates for documentaries, explainers, listicles, and stories. Copy a prompt and create today.',
    },
  ],
};
