import type { ToolInput, ToolOutput } from '../../../src/lib/registry/types.ts';
import type { ToolContent } from '../../../src/templates/types.ts';

const TOOL_URL = 'https://husnainblogger.com/tools/blogging-seo/open-graph-tag-generator/';

export const inputs: ToolInput[] = [
  {
    id: 'title',
    label: 'Page title',
    type: 'text',
    required: true,
    placeholder: 'How to Brew Pour-Over Coffee',
    validation: { max: 200 },
  },
  {
    id: 'description',
    label: 'Page description',
    type: 'textarea',
    required: true,
    placeholder: 'A short summary of the page (max 300 characters).',
    validation: { max: 300 },
  },
  {
    id: 'url',
    label: 'Page URL',
    type: 'url',
    required: true,
    placeholder: 'https://example.com/pour-over',
  },
  {
    id: 'image',
    label: 'Image URL',
    type: 'url',
    required: true,
    placeholder: 'https://example.com/images/pour-over.jpg',
  },
  {
    id: 'type',
    label: 'Page type',
    type: 'select',
    required: false,
    options: [
      'website',
      'article',
    ],
  },
];

export const outputs: ToolOutput[] = [
  {
    id: 'tagsHtml',
    label: 'Open Graph tags (copy)',
    type: 'copy',
    description:
    'Free open graph generator 2026: The 5 Open Graph meta tags — paste them inside the <head> of your page. Get instant results. free now.',
  },
  {
    id: 'warnings',
    label: 'Recommendations',
    type: 'list',
    description:
    'Non-blocking tips, e.g. a title that may be truncated in previews.',
  },
];

export const content: ToolContent = {
  title: 'Open Graph Generator',
  description:
    'Create perfect Open Graph meta tags for any page in seconds. Enter title, description, URL, and image, then copy the ready-to-paste tags. Try it free.',
  howTo: [
    'Enter the "Page title" (max 200 characters) and "Page description" (max 300 characters).',
    'Add the full "Page URL" and "Image URL" — both must start with http:// or https://.',
    'Pick the "Page type": website for normal pages, article for blog posts and news.',
    'Run the tool and read "Recommendations" for tips like a title that may be truncated.',
    'Copy the "Open Graph tags" and paste them inside the <head> of your page, then preview the link in Facebook\'s Sharing Debugger.',
  ],
  methodology:
    'This tool assembles a fixed 5-tag template (og:title, og:description, og:url, og:image, og:type) from exactly what you type in — title 1–200 chars, description 1–300 chars, absolute http(s) URLs, and og:type limited to "website" or "article" (default "website"). Attribute values are HTML-escaped so quotes and special characters cannot break your markup. Nothing is generated by AI and no text is rewritten. Recommended lengths (~60-char title, ~155-char description) are warnings only, and the image-extension check is a heuristic, not a guarantee.',
  examples: [
    {
      title: 'Blog post with article type',
      inputs: {
        title: 'How to Brew Pour-Over Coffee',
        description:
    'A step-by-step guide to brewing pour-over coffee at home.',
        url: 'https://example.com/pour-over',
        image: 'https://example.com/images/pour-over.jpg',
        type: 'article',
      },
      note: 'Full input producing all 5 tags with og:type set to article.',
    },
    {
      title: 'Homepage with defaults',
      inputs: {
        title: 'Example Blog',
        description:
    'Simple blogging tips, published weekly.',
        url: 'https://example.com/',
        image: 'https://example.com/images/logo.png',
      },
      note: 'Page type defaults to website when left blank.',
    },
    {
      title: 'Long title flagged',
      inputs: {
        title: 'This is a deliberately very long page title that will almost certainly be truncated in link previews',
        description:
    'Short description.',
        url: 'https://example.com/long',
        image: 'https://example.com/images/long.jpg',
      },
      note: 'Tags are still generated, but Recommendations warns the title may be truncated.',
    },
  ],
  faqs: [
    {
      question: 'What is the best open graph generator?',
      answer:
        'The best open graph generator produces valid og:title, og:description, og:url, og:image, and og:type tags, validates your inputs, and needs no signup. This tool does all three — fill in the fields, copy the tags, and paste them into your page\'s <head>.',
    },
    {
      question: 'Is there a free open graph generator?',
      answer:
        'Yes — this open graph generator is completely free with no signup. Enter your title, description, page URL, and image URL, and copy the ready-to-paste meta tags.',
    },
    {
      question: 'How to generate open graph?',
      answer:
        'Enter your page title, description, full page URL, and image URL, pick the page type (website or article), then copy the generated meta tags into the <head> of your page. Test the link preview in Facebook\'s Sharing Debugger afterwards.',
    },
    {
      question: 'How does an open graph generator work?',
      answer:
        'It takes the title, description, URL, image, and page type you provide and assembles them into the five standard Open Graph meta tags with proper HTML escaping. Nothing is written by AI — the tool only formats your own input into valid markup.',
    },
    {
      question: 'What is an open graph generator?',
      answer:
        'An open graph generator is a free online tool that gives you quick, accurate results without spreadsheets or manual math. This version runs entirely in your browser for instant, private results.',
    },
  ],
  assumptions: [
    'The tool checks tag syntax, not how a platform renders the preview — platforms cache previews and have their own image-size requirements.',
    'The image-extension check is a heuristic: an image URL without a common extension still generates tags but triggers a warning.',
    'Recommended title/description lengths are warnings only — longer values still produce valid tags.',
  ],
  jsonLd: [],
};
