import type { ToolInput, ToolOutput } from '../../../src/lib/registry/types.ts';
import type { ToolContent } from '../../../src/templates/types.ts';

const TOOL_URL = 'https://husnainblogger.com/tools/youtube/faceless-channel-idea-mixer/';

const DESCRIPTION =
  'Generate faceless YouTube channel ideas free — mix niches, formats and angles into idea seeds plus channel-name suggestions. Try the mixer now — free forever.';

export const inputs: ToolInput[] = [
  {
    id: 'niche',
    label: 'Niche keyword (optional)',
    type: 'text',
    required: false,
    placeholder: 'e.g. space facts',
  },
  {
    id: 'format',
    label: 'Format',
    type: 'select',
    required: false,
    options: ['any', 'listicle', 'compilation', 'narration', 'tutorial'],
  },
  {
    id: 'count',
    label: 'Number of ideas',
    type: 'number',
    required: false,
    placeholder: '10',
    validation: { min: 1, max: 30 },
  },
];

export const outputs: ToolOutput[] = [
  { id: 'ideas', label: 'Channel concept ideas', type: 'list' },
  { id: 'channelNameSeeds', label: 'Channel name seeds', type: 'list' },
  { id: 'policyNote', label: 'Monetization policy note', type: 'text' },
  { id: 'bankInfo', label: 'How ideas were built', type: 'text' },
  { id: 'isTemplateBased', label: 'Template flag', type: 'text' },
];

export const content: ToolContent = {
  title: 'Faceless YouTube Channel Ideas – 2027 Guide',
  description: DESCRIPTION,
  howTo: [
    'Enter a niche keyword (optional) — leave it blank to mix across 16 faceless-friendly niches.',
    'Pick a format: listicle, compilation, narration, or tutorial — or "any" to mix all four.',
    'Choose how many idea seeds you want (up to 30) and run the mixer.',
    'Browse the channel concepts and the 10 channel-name seeds built from your niche.',
    'Read the monetization policy note, then develop any seed with original research or commentary before filming.',
  ],
  methodology:
    'Ideas are assembled by deterministic combinatorics over fixed hand-written banks: 16 niche seeds × 4 formats × 12 angle templates, served in bank order and cycling when the count exceeds a bank. Channel names come from 10 fixed name patterns filled with your niche. Nothing is generated by AI and nothing is demand research — outputs are idea seeds, and since July 2025 YouTube\'s inauthentic-content policy puts mass-produced templated channels under extra monetization review.',
  examples: [
    {
      title: 'Space facts, listicle format',
      inputs: { niche: 'space facts', format: 'listicle', count: 5 },
      note: 'Five listicle concepts like "Top 10 space facts you never knew existed", plus name seeds such as "Space Facts Lab".',
    },
    {
      title: 'No niche, mixed formats',
      inputs: { count: 4 },
      note: 'Four seeds cycling across niches and formats — a quick way to survey faceless directions.',
    },
  ],
  faqs: [
    {
      question: 'what is the best faceless youtube channel ideas?',
      answer:
        'The best starting point is a niche you can research deeply paired with a repeatable format. This free mixer combines 16 faceless-friendly niches, 4 formats, and 12 angle templates into idea seeds — but the idea is only a seed; execution and originality decide the outcome.',
    },
    {
      question: 'is there a free faceless youtube channel ideas?',
      answer:
        'Yes — this mixer is completely free with no signup. Enter a niche (or leave it blank), pick a format, and get up to 30 channel concept seeds plus 10 channel-name suggestions.',
    },
    {
      question: 'how to use faceless youtube channel?',
      answer:
        'Pick a niche, choose a format you can produce without showing your face (narration, listicles, compilations, tutorials), and publish consistently. Note: since July 2025 YouTube reviews mass-produced templated channels more strictly, so add original commentary or research.',
    },
    {
      question: 'how does a faceless youtube channel ideas work?',
      answer:
        'This tool mixes fixed template banks — niche × format × angle — in deterministic order. It does not use AI and does no demand research; every output is labeled an idea seed, never a researched opportunity.',
    },
    {
      question: 'Can you make money with a faceless YouTube channel in 2026?',
      answer:
        'Yes — many faceless channels earn significant revenue through AdSense, sponsorships, and affiliate marketing. Popular faceless niches include finance explainers, tech tutorials, true crime narrations, and relaxing content. The key is consistent, high-quality content.',
    },
    {
      question: 'What is the best faceless YouTube niche?',
      answer:
        'The best niche depends on your skills, but high-CPM faceless niches include personal finance, software tutorials, AI tools, and educational content. Use the generator above to mix niches with video formats and find your angle.',
    },
    {
      question: 'Do faceless YouTube channels get monetized?',
      answer:
        'Yes, faceless channels can be monetized if they meet YouTube Partner Program requirements (1,000 subscribers + 4,000 watch hours) and follow the reused-content policy — your content must add original commentary, editing, or educational value, not just reupload others\u2019 material.',
    },
  ],
  assumptions: [
    'Outputs are template-based idea seeds, not researched opportunities — no demand, competition, or CPM data is involved.',
    'YouTube\'s inauthentic-content policy (tightened July 2025) means templated, mass-produced channels face extra monetization review; original value is required.',
    'Channel-name seeds are starting points — check name availability on YouTube yourself before committing.',
  ],
  jsonLd: [
    {
      '@type': 'SoftwareApplication',
      name: 'Faceless YouTube Channel Ideas – 2026 Guide | HusnainBlogger',
      url: TOOL_URL,
      applicationCategory: 'Utilities',
      operatingSystem: 'Web',
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      description: DESCRIPTION,
    },
    {
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://husnainblogger.com/' },
        { '@type': 'ListItem', position: 2, name: 'Tools', item: 'https://husnainblogger.com/tools/' },
        { '@type': 'ListItem', position: 3, name: 'YouTube Tools', item: 'https://husnainblogger.com/tools/youtube/' },
        { '@type': 'ListItem', position: 4, name: 'Faceless Channel Idea Mixer', item: TOOL_URL },
      ],
    },
  ],
};
