import type { ToolInput, ToolOutput } from '../../../src/lib/registry/types.ts';
import type { ToolContent } from '../../../src/templates/types.ts';

const TOOL_URL = 'https://husnainblogger.com/tools/creator-business/brand-pitch-email-generator/';

export const inputs: ToolInput[] = [
  {
    id: 'brandName',
    label: 'Brand name',
    type: 'text',
    required: true,
    placeholder: 'e.g. GlowLab',
  },
  {
    id: 'creatorName',
    label: 'Your name',
    type: 'text',
    required: true,
    placeholder: 'e.g. Maya Khan',
  },
  {
    id: 'niche',
    label: 'Your niche',
    type: 'text',
    required: true,
    placeholder: 'e.g. skincare',
  },
  {
    id: 'followerCount',
    label: 'Follower count (as you report it)',
    type: 'text',
    required: false,
    placeholder: 'e.g. 125K on Instagram',
  },
  {
    id: 'engagementRate',
    label: 'Engagement rate % (your own figure)',
    type: 'number',
    required: false,
    placeholder: 'e.g. 4.2',
    validation: { min: 0, max: 100, unit: '%' },
  },
  {
    id: 'pastResults',
    label: 'Past results (one per line, optional)',
    type: 'textarea',
    required: false,
    placeholder: 'Drove 800 link clicks for a serum launch\n2 past brand deals completed',
  },
  {
    id: 'pitchAngle',
    label: 'Pitch angle',
    type: 'select',
    required: true,
    options: ['value-first', 'data-driven', 'creative-concept', 'ugc-offer', 'long-term-partnership'],
  },
  {
    id: 'callToAction',
    label: 'Call to action',
    type: 'text',
    required: false,
    placeholder: 'e.g. a 20-minute call on Thursday',
  },
];

export const outputs: ToolOutput[] = [
  {
    id: 'pitchEmailDraft',
    label: 'Pitch email draft (copy)',
    type: 'copy',
    description: 'Free brand pitch email template 2026: 3 subject-line options plus the full email body, ready to copy and send. Fast, private, no signup - try it now!',
  },
];

export const content: ToolContent = {
  title: 'Brand Pitch Email Template',
  description:
    'Generate a brand pitch email in seconds. Enter your niche, metrics, and pitch angle to get 3 subject lines plus a ready-to-send draft. Try it free now!',
  howTo: [
    'Enter the brand name, your name, and your niche in the matching fields.',
    'Add your follower count and engagement rate exactly as you report them — the tool inserts them verbatim and never verifies them.',
    'Optionally list past results (one per line) to add credibility bullets to the email.',
    'Pick a pitch angle: value-first, data-driven, creative-concept, ugc-offer, or long-term-partnership.',
    'Run the tool, choose one of the 3 subject lines, copy the email body, and personalize the final line before sending.',
  ],
  methodology:
    'This tool assembles your draft from fixed human-written templates: 5 pitch angles, each with 3 subject-line templates and 1 body template (15 subjects + 5 bodies total). Your brand name, metrics, past results, and call to action are slotted into the chosen template. Follower counts and engagement rates are echoed exactly as you typed them — the tool has no access to your analytics and does not verify any metric. Nothing is generated by AI.',
  examples: [
    {
      title: 'Skincare creator, value-first pitch',
      inputs: {
        brandName: 'GlowLab',
        creatorName: 'Maya Khan',
        niche: 'skincare',
        followerCount: '125K on Instagram',
        engagementRate: 4.2,
        pitchAngle: 'value-first',
        callToAction: 'a 20-minute call on Thursday',
      },
      note: 'Produces 3 subject options and a value-led email body with your metrics labeled as self-reported.',
    },
    {
      title: 'UGC offer with past results',
      inputs: {
        brandName: 'NorthPeak',
        creatorName: 'Dev Patel',
        niche: 'outdoor gear',
        followerCount: '40K on TikTok',
        pastResults: 'Delivered 12 UGC videos for a hiking brand\nAverage 6% CTR on spark ads',
        pitchAngle: 'ugc-offer',
      },
      note: 'Past results appear as bullet points in the body; the call to action falls back to a default intro call.',
    },
    {
      title: 'Data-driven pitch, metrics only',
      inputs: {
        brandName: 'FitFuel',
        creatorName: 'Aisha Rahman',
        niche: 'fitness',
        followerCount: '210K on YouTube',
        engagementRate: 5.8,
        pitchAngle: 'data-driven',
      },
      note: 'Leads with a metrics block — every figure is inserted exactly as entered, never researched or embellished.',
    },
  ],
  faqs: [
    {
      question: 'What is the best brand pitch email template?',
      answer:
        'The best brand pitch email is short, specific, and creator-led: who you are, why your audience fits the brand, one concrete idea, and one clear call to action. This free generator gives you 3 subject-line options and a full body across 5 pitch angles (value-first, data-driven, creative concept, UGC offer, long-term partnership) so you can pick the tone that fits.',
    },
    {
      question: 'Is there a free brand pitch email template?',
      answer:
        'Yes — this brand pitch email generator is completely free with no signup. Enter the brand name, your niche and metrics, pick a pitch angle, and copy a ready-to-send draft with 3 subject lines.',
    },
    {
      question: 'How to use brand pitch email?',
      answer:
        'Fill in the brand name, your name, and niche, add your follower count and engagement rate as you report them, optionally list past results, and choose a pitch angle. Run the tool, pick one of the 3 subject lines, copy the body, and personalize the final line — for example, mention a specific product you genuinely like — before sending.',
    },
    {
      question: 'How does the brand pitch email template work?',
      answer:
        'Enter your details using the inputs above and the brand pitch email template calculates everything instantly in your browser. No data leaves your device, and you get results the moment you change any value.',
    },
    {
      question: 'Is the brand pitch email template free to use?',
      answer:
        'Yes - this brand pitch email template is completely free with no signup, no account, and no usage limits. It runs 100% in your browser.',
    },
    {
      question: 'What is a brand pitch email template?',
      answer:
        'A brand pitch email template is a free online tool that gives you quick, accurate results without spreadsheets or manual math. This version runs entirely in your browser for instant, private results.',
    },
    {
      question: 'Do I need to create an account to use the brand pitch email template?',
      answer:
        'No account needed. Open the brand pitch email template, enter your values, and see results immediately - nothing is stored or sent anywhere.',
    },
  ],
  assumptions: [
    'Follower counts, engagement rates, and past results are inserted exactly as you type them — the tool cannot access your analytics and does not verify any metric. Only pitch numbers you can back up.',
    'Templates are starting points, not send-ready guarantees: personalizing one or two lines (a real product mention, a mutual connection) materially improves reply rates.',
    'No sending happens here — the tool produces a draft you copy into your own email client.',
  ],
  jsonLd: [
    {
      '@type': 'SoftwareApplication',
      name: 'Brand Pitch Email Template 2026 – Free | HusnainBlogger',
      url: TOOL_URL,
      applicationCategory: 'Utilities',
      operatingSystem: 'Web',
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      description: 'Free brand pitch email template 2026: 3 subject-line options plus the full email body, ready to copy and send. Fast, private, no signup - try it now!',
    },
    {
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://husnainblogger.com/' },
        { '@type': 'ListItem', position: 2, name: 'Tools', item: 'https://husnainblogger.com/tools/' },
        {
          '@type': 'ListItem',
          position: 3,
          name: 'Creator Business',
          item: 'https://husnainblogger.com/tools/creator-business/',
        },
        {
          '@type': 'ListItem',
          position: 4,
          name: 'Brand Pitch Email Generator',
          item: TOOL_URL,
        },
      ],
    },
  ],
};
