import type { ToolInput, ToolOutput } from '../../../src/lib/registry/types.ts';
import type { ToolContent } from '../../../src/templates/types.ts';

const TOOL_URL = 'https://husnainblogger.com/tools/blogging-seo/twitter-card-generator/';

export const inputs: ToolInput[] = [
  {
    id: 'title',
    label: 'Card title',
    type: 'text',
    required: true,
    placeholder: 'How to Brew Pour-Over Coffee',
    validation: { max: 200 },
  },
  {
    id: 'description',
    label: 'Card description',
    type: 'textarea',
    required: true,
    placeholder: 'A short summary of the page (max 300 characters).',
    validation: { max: 300 },
  },
  {
    id: 'image',
    label: 'Image URL',
    type: 'url',
    required: true,
    placeholder: 'https://example.com/images/pour-over.jpg',
  },
  {
    id: 'card',
    label: 'Card type',
    type: 'select',
    required: false,
    options: [
      'summary_large_image',
      'summary',
    ],
  },
  {
    id: 'site',
    label: 'X handle (optional)',
    type: 'text',
    required: false,
    placeholder: '@husnainblogger',
  },
];

export const outputs: ToolOutput[] = [
  {
    id: 'tagsHtml',
    label: 'Twitter Card tags (copy)',
    type: 'copy',
    description: 'Free twitter card generator 2026: The Twitter Card meta tags — paste them inside the <head> of your page. Get instant results. No signup - try it free now!',
  },
  {
    id: 'warnings',
    label: 'Recommendations',
    type: 'list',
    description: 'Non-blocking tips, e.g. a missing @site handle or an unusual image URL.',
  },
];

export const content: ToolContent = {
  title: 'Twitter Card Generator 2026 – Free Tool | HusnainBlogger',
  description:
    'Build Twitter Card meta tags that make your links stand out on X. Add title, description, image, and handle, then copy the tags. Free, no signup!',
  howTo: [
    'Enter the "Card title" (max 200 characters) and "Card description" (max 300 characters).',
    'Add the full "Image URL" — it must start with http:// or https://.',
    'Pick the "Card type": large image for a big preview, or summary for a small thumbnail.',
    'Optionally add your "X handle" (starting with @) so the card is attributed to your account.',
    'Copy the "Twitter Card tags" and paste them inside the <head> of your page, then preview the link with X\'s Card Validator.',
  ],
  methodology:
    'This tool assembles a fixed template (twitter:card, twitter:title, twitter:description, twitter:image, plus twitter:site when a handle is given) from exactly what you type in — title 1–200 chars, description 1–300 chars, an absolute http(s) image URL, and the card type limited to "summary" or "summary_large_image" (default summary_large_image). The handle must match @username format. Attribute values are HTML-escaped. Nothing is generated by AI and no text is rewritten. A missing handle or an unusual image URL is a warning only.',
  examples: [
    {
      title: 'Blog post, large image card',
      inputs: {
        title: 'How to Brew Pour-Over Coffee',
        description: 'A step-by-step guide to brewing pour-over coffee at home.',
        image: 'https://example.com/images/pour-over.jpg',
        card: 'summary_large_image',
        site: '@husnainblogger',
      },
      note: 'Full input producing all 5 tags including twitter:site.',
    },
    {
      title: 'Summary card without handle',
      inputs: {
        title: 'Example Blog',
        description: 'Simple blogging tips, published weekly.',
        image: 'https://example.com/images/logo.png',
        card: 'summary',
      },
      note: 'No handle given — the twitter:site tag is omitted and a warning is shown.',
    },
    {
      title: 'Invalid handle rejected',
      inputs: {
        title: 'Example Blog',
        description: 'Simple blogging tips, published weekly.',
        image: 'https://example.com/images/logo.png',
        site: 'husnainblogger',
      },
      note: 'Handles must start with @ — this input fails validation with a clear message.',
    },
  ],
  faqs: [
    {
      question: 'What is the best twitter card generator?',
      answer:
        'The best twitter card generator produces valid twitter:card, twitter:title, twitter:description, and twitter:image tags, supports both card types, and needs no signup. This tool does all three — fill in the fields, copy the tags, and paste them into your page\'s <head>.',
    },
    {
      question: 'Is there a free twitter card generator?',
      answer:
        'Yes — this twitter card generator is completely free with no signup. Enter your title, description, image URL, and optional X handle, and copy the ready-to-paste meta tags.',
    },
    {
      question: 'How to generate twitter?',
      answer:
        'Enter your card title, description, and image URL, pick the card type (summary or summary_large_image), optionally add your @handle, then copy the generated meta tags into the <head> of your page. Check the preview with X\'s Card Validator.',
    },
    {
      question: 'How does a twitter card generator work?',
      answer:
        'It takes the title, description, image URL, card type, and handle you provide and assembles them into the standard Twitter Card meta tags with proper HTML escaping. Nothing is written by AI — the tool only formats your own input into valid markup.',
    },
    {
      question: 'How does the twitter card generator work?',
      answer:
        'Enter your details using the inputs above and the twitter card generator calculates everything instantly in your browser. No data leaves your device, and you get results the moment you change any value.',
    },
    {
      question: 'Is the twitter card generator free to use?',
      answer:
        'Yes - this twitter card generator is completely free with no signup, no account, and no usage limits. It runs 100% in your browser.',
    },
    {
      question: 'What is a twitter card generator?',
      answer:
        'A twitter card generator is a free online tool that gives you quick, accurate results without spreadsheets or manual math. This version runs entirely in your browser for instant, private results.',
    },
  ],
  assumptions: [
    'The twitter:site tag is optional — leaving it out still produces valid cards, and the tool says so in Recommendations.',
    'The tool checks tag syntax, not how X renders the card — X caches previews and has its own image requirements.',
    'The image-extension check is a heuristic: an unusual image URL still generates tags but triggers a warning.',
  ],
  jsonLd: [
    {
      '@type': 'SoftwareApplication',
      name: 'Twitter Card Generator 2026 – Free Tool | HusnainBlogger',
      url: TOOL_URL,
      applicationCategory: 'Utilities',
      operatingSystem: 'Web',
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      description: 'Free twitter card generator 2026: The Twitter Card meta tags — paste them inside the <head> of your page. Get instant results. No signup - try it free now!',
    },
    {
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://husnainblogger.com/' },
        { '@type': 'ListItem', position: 2, name: 'Tools', item: 'https://husnainblogger.com/tools/' },
        {
          '@type': 'ListItem',
          position: 3,
          name: 'Blogging & SEO Tools',
          item: 'https://husnainblogger.com/tools/blogging-seo/',
        },
        {
          '@type': 'ListItem',
          position: 4,
          name: 'Twitter Card Generator',
          item: TOOL_URL,
        },
      ],
    },
  ],
};
