import type { ToolInput, ToolOutput } from '../../../src/lib/registry/types.ts';
import type { ToolContent } from '../../../src/templates/types.ts';

const TOOL_URL = 'https://husnainblogger.com/tools/blogging-seo/click-to-tweet-box-generator/';

export const inputs: ToolInput[] = [
  {
    id: 'tweetText',
    label: 'Text to tweet (1–280 characters)',
    type: 'textarea',
    required: true,
    placeholder: 'Your best quote from the post goes here.',
  },
  {
    id: 'via',
    label: 'Via handle (optional, e.g. @yourhandle)',
    type: 'text',
    required: false,
    placeholder: '@yourhandle',
    validation: { pattern: '^@.+' },
  },
  {
    id: 'url',
    label: 'Link to share (optional)',
    type: 'text',
    required: false,
    placeholder: 'https://yourblog.com/post/',
  },
];

export const outputs: ToolOutput[] = [
  {
    id: 'boxHtml',
    label: 'Box HTML (copy)',
    type: 'copy',
    description:
    'Free click to tweet generator 2026: Ready-to-paste click-to-tweet box with minimal inline styles — works in any blog theme. Fast, private.',
  },
  {
    id: 'intentUrl',
    label: 'Share URL (copy)',
    type: 'copy',
    description:
    'The X (Twitter) intent URL behind the button — use it on its own if you prefer.',
  },
];

export const content: ToolContent = {
  title: 'Click to Tweet Generator',
  description:
    'Turn any quote into a click to tweet box in seconds. Enter your text, copy the ready-to-share HTML, and get more shares from your readers. Try it free.',
  howTo: [
    'Type the quote or stat you want readers to share in "Text to tweet" (up to 280 characters).',
    'Optionally add your "Via handle" (starting with @) so shares credit you.',
    'Optionally add the "Link to share" — the URL readers will attach to the tweet.',
    'Run the tool and review the box preview.',
    'Copy the "Box HTML" and paste it into your post\'s HTML or Custom HTML block. Copy the "Share URL" separately if you want to link the text yourself.',
  ],
  methodology:
    'Your text is percent-encoded into an X (Twitter) intent URL (text, then via, then url parameters), and the visible box is built with your text HTML-escaped so it can never inject markup. Styling is intentionally minimal and inline so the snippet works in any blog theme. Nothing is generated by AI — the box contains only the words you typed.',
  examples: [
    {
      title: 'Quote with credit and link',
      inputs: { tweetText: 'Blogging is compounding — every post pays rent forever.', via: '@husnain', url: 'https://example.com/blogging/' },
      note: 'A full box with attribution and a shared link.',
    },
    {
      title: 'Text only',
      inputs: { tweetText: 'Write the post you wish you had found.' },
      note: 'Just the shareable quote — no handle or link attached.',
    },
    {
      title: 'Stat teaser',
      inputs: { tweetText: 'Posts with share boxes get more shares. 📈', url: 'https://example.com/stats/' },
      note: 'Emoji and unicode are encoded safely in the share URL.',
    },
  ],
  faqs: [
    {
      question: 'What is the best click to tweet generator?',
      answer:
        'The best click to tweet generator builds a clean share box with a working X (Twitter) intent link that survives unicode and emoji, and needs no signup. This tool does that — you get inline-styled box HTML plus the raw share URL, free.',
    },
    {
      question: 'Is there a free click to tweet generator?',
      answer:
        'Yes — this click to tweet generator is completely free with no signup. Create as many share boxes as you like, each up to 280 characters.',
    },
    {
      question: 'How to generate click to tweet?',
      answer:
        'Type the text you want readers to share, optionally add your @handle and a link, then run the tool. Copy the generated box HTML into your post\'s HTML or Custom HTML block and readers can share it in one click.',
    },
    {
      question: 'How does a click to tweet generator work?',
      answer:
        'It percent-encodes your text into an X (Twitter) intent URL and wraps it in a styled box with a share button. When a reader clicks, their compose window opens with your text pre-filled. Nothing is written by AI — the box contains only your words.',
    },
    {
      question: 'How does the click to tweet generator work?',
      answer:
        'Enter your details using the inputs above and the click to tweet generator calculates everything instantly in your browser. No data leaves your device, and you get results the moment you change any value.',
    },
    {
      question: 'Is the click to tweet generator free to use?',
      answer:
        'Yes - this click to tweet generator is completely free with no signup, no account, and no usage limits. It runs 100% in your browser.',
    },
    {
      question: 'What is a click to tweet generator?',
      answer:
        'A click to tweet generator is a free online tool that gives you quick, accurate results without spreadsheets or manual math. This version runs entirely in your browser for instant, private results.',
    },
  ],
  assumptions: [
    'Styling is intentionally minimal and inline so the snippet works in any blog theme.',
    'All visible text is HTML-escaped; you cannot inject raw HTML, scripts, or attributes through this tool.',
    'The share link opens X (Twitter)\'s intent endpoint — posting still requires the reader\'s own X account.',
    'Tweet text is limited to 280 characters, counted in Unicode code points so emoji count as one.',
  ],
  jsonLd: [
  ],
};
