/**
 * AI Image Prompt Builder (tool-303) — pure logic, zero imports.
 *
 * PROMPT ASSEMBLER, NOT AI: builds an image-generation prompt string from
 * the user's choices using preset phrase banks. NO image is generated by
 * this tool and no AI model runs — the user pastes the assembled prompt
 * into their own image generator (Midjourney, DALL-E, Stable Diffusion…).
 *
 * Phrase banks (sizes documented for honest UI copy):
 *   ART_STYLES    — 12 presets
 *   ASPECT_RATIOS — 5 presets (1:1, 16:9, 9:16, 4:3, 3:2)
 *   LIGHTING      — 8 presets
 *   CAMERA_ANGLES — 8 presets
 *
 * Rules:
 *   - subject is required.
 *   - artStyle: matched case-insensitively against ART_STYLES; unknown or
 *     empty falls back to "photorealistic" (per spec edge case).
 *   - aspectRatio: empty falls back to "16:9"; a provided value must be one
 *     of the 5 presets, otherwise the item is rejected.
 *   - lighting / cameraAngle: empty falls back to defaults ("soft daylight",
 *     "eye level"); a provided value matching a preset is canonicalized,
 *     any other text is used verbatim as the user's own creative choice.
 *   - negativeTerms: optional free text, appended as a negative-prompt line.
 */

export const ART_STYLES = [
  "photorealistic",
  "cinematic",
  "anime",
  "digital painting",
  "3d render",
  "watercolor",
  "pixel art",
  "minimalist",
  "oil painting",
  "cyberpunk",
  "studio photography",
  "ink sketch",
] as const;

export const ASPECT_RATIOS = ["1:1", "16:9", "9:16", "4:3", "3:2"] as const;

export const LIGHTING = [
  "golden hour",
  "soft daylight",
  "dramatic",
  "neon",
  "studio lighting",
  "moonlight",
  "backlit",
  "overcast",
] as const;

export const CAMERA_ANGLES = [
  "eye level",
  "low angle",
  "high angle",
  "close-up",
  "wide shot",
  "aerial",
  "dutch angle",
  "macro",
] as const;

export const DEFAULT_STYLE = "photorealistic";
export const DEFAULT_ASPECT_RATIO = "16:9";
export const DEFAULT_LIGHTING = "soft daylight";
export const DEFAULT_CAMERA_ANGLE = "eye level";
export const MAX_FIELD_CHARS = 300;
export const MAX_ITEMS = 20;

export interface BuilderItem {
  subject?: unknown;
  artStyle?: unknown;
  aspectRatio?: unknown;
  lighting?: unknown;
  cameraAngle?: unknown;
  negativeTerms?: unknown;
}

export interface RunResult {
  ok: boolean;
  values?: { lines: string[] };
  error?: string;
}

/** Trim, strip control chars, collapse whitespace, cap length. */
export function sanitize(value: unknown): string {
  if (typeof value !== "string") return "";
  return value
    .replace(/[\u0000-\u001F\u007F]/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, MAX_FIELD_CHARS);
}

/** Case-insensitive match against a preset bank; null when no match. */
function matchPreset(value: string, bank: readonly string[]): string | null {
  const v = value.toLowerCase();
  const found = bank.find((b) => b.toLowerCase() === v);
  return found ?? null;
}

export interface NormalizedItem {
  subject: string;
  style: string;
  aspectRatio: string;
  lighting: string;
  cameraAngle: string;
  negativeTerms: string;
}

/**
 * Validate + normalize one item. Returns the normalized fields or an
 * error string (already prefixed with "Item N:").
 */
export function normalizeItem(item: BuilderItem, index: number): {
  ok: boolean;
  item?: NormalizedItem;
  error?: string;
} {
  const label = `Item ${index + 1}`;
  if (!item || typeof item !== "object") return { ok: false, error: `${label}: not an object.` };

  const subject = sanitize(item.subject);
  if (subject === "") return { ok: false, error: `${label}: subject is required.` };

  const styleRaw = sanitize(item.artStyle);
  const style = styleRaw === "" ? DEFAULT_STYLE : (matchPreset(styleRaw, ART_STYLES) ?? DEFAULT_STYLE);

  const arRaw = sanitize(item.aspectRatio);
  let aspectRatio = DEFAULT_ASPECT_RATIO;
  if (arRaw !== "") {
    const matched = matchPreset(arRaw, ASPECT_RATIOS);
    if (matched === null)
      return {
        ok: false,
        error: `${label}: aspect ratio "${arRaw}" is not valid. Use one of: ${ASPECT_RATIOS.join(", ")}.`,
      };
    aspectRatio = matched;
  }

  const lightRaw = sanitize(item.lighting);
  const lighting =
    lightRaw === "" ? DEFAULT_LIGHTING : (matchPreset(lightRaw, LIGHTING) ?? lightRaw);

  const angleRaw = sanitize(item.cameraAngle);
  const cameraAngle =
    angleRaw === "" ? DEFAULT_CAMERA_ANGLE : (matchPreset(angleRaw, CAMERA_ANGLES) ?? angleRaw);

  const negativeTerms = sanitize(item.negativeTerms);

  return { ok: true, item: { subject, style, aspectRatio, lighting, cameraAngle, negativeTerms } };
}

/** Assemble the final copy-paste image prompt string. */
export function assembleImagePrompt(n: NormalizedItem): string {
  let prompt = `${n.style} image of ${n.subject}, ${n.lighting} lighting, ${n.cameraAngle} shot, highly detailed (aspect ratio ${n.aspectRatio})`;
  if (n.negativeTerms !== "") prompt += ` | Negative prompt: ${n.negativeTerms}`;
  return prompt;
}

export function runTool(args: { items: Record<string, unknown>[] }): RunResult {
  if (!args || !Array.isArray(args.items))
    return { ok: false, error: "No items were provided." };
  if (args.items.length === 0)
    return { ok: false, error: "Add at least one item to build a prompt." };
  if (args.items.length > MAX_ITEMS)
    return { ok: false, error: `Too many items (max ${MAX_ITEMS}).` };

  const lines: string[] = [];
  for (let i = 0; i < args.items.length; i++) {
    const res = normalizeItem(args.items[i] as BuilderItem, i);
    if (!res.ok || !res.item) return { ok: false, error: res.error };
    lines.push(assembleImagePrompt(res.item));
  }
  return { ok: true, values: { lines } };
}
