import type { ToolInput, ToolOutput } from '../../../src/lib/registry/types.ts';
import type { ToolContent } from '../../../src/templates/types.ts';

export const inputs: ToolInput[] = [
  {
    id: 'niche',
    label: 'Your niche',
    type: 'select',
    required: true,
    options: [
      'gaming',
      'personal-finance',
      'cooking-food',
      'fitness-health',
      'tech-reviews',
      'beauty-style',
      'education',
      'travel',
      'music',
      'entertainment-comedy',
      'diy-crafts',
      'parenting-family',
    ],
  },
  {
    id: 'audienceBand',
    label: 'Audience size',
    type: 'select',
    required: true,
    options: ['under-1k', '1k-10k', '10k-100k', 'over-100k'],
  },
  {
    id: 'effortTolerance',
    label: 'Effort you can invest',
    type: 'select',
    required: true,
    options: ['low', 'medium', 'high'],
  },
];

export const outputs: ToolOutput[] = [
  { id: 'rankedIdeas', label: 'Ranked product ideas', type: 'list' },
  { id: 'summary', label: 'Top match summary', type: 'text' },
  { id: 'honestyNote', label: 'Honesty note', type: 'text' },
];

const DESCRIPTION =
  'Discover profitable digital products for YouTubers matched to your niche, audience size, and effort level — every idea ranked by real fit. Answer.';

export const content: ToolContent = {
  title: 'Digital Products for YouTubers',
  description: DESCRIPTION,
  howTo: [
    'Pick your channel niche from the dropdown (gaming, finance, cooking, fitness, and 8 more).',
    'Select your audience size band — digital products are boosted for smaller audiences, services for larger ones.',
    'Choose how much effort you can invest: low, medium, or high filters the idea list.',
    'Run the matcher and read your ranked ideas — each one explains why it fits your channel.',
    'Validate the top idea with your own audience (a poll or comment prompt) before building anything.',
  ],
  methodology:
    'A fixed mapping table holds 72 product ideas (12 niches x 6 each), each tagged with product kind (digital, physical, service), effort level, and an opinionated 1–5 fit score. Ideas are filtered by your effort tolerance, then scored: fit score plus a +0.5 boost for digital products at small audiences or service products at large audiences. Nothing is generated by AI and no market or sales data is used — it is a brainstorm aid, not market research.',
  examples: [
    {
      title: 'Small gaming channel, low effort',
      inputs: { niche: 'gaming', audienceBand: '1k-10k', effortTolerance: 'low' },
      note: 'Digital products rank first — a settings pack and aim routine beat high-effort services here.',
    },
    {
      title: 'Large education channel, high effort',
      inputs: { niche: 'education', audienceBand: 'over-100k', effortTolerance: 'high' },
      note: 'All six ideas qualify; services get a boost and the exam prep course tops the list.',
    },
  ],
  faqs: [
    {
      question: 'What is the best digital products for YouTubers?',
      answer:
        'The best digital products for YouTubers are ones your viewers already ask for: templates, planners, presets, and courses tied to your niche. This matcher ranks 72 fixed ideas across 12 niches by fit, audience size, and your effort level — but treat it as a brainstorm aid and validate demand with your own audience before building.',
    },
    {
      question: 'Is there a free digital products for YouTubers?',
      answer:
        'Yes — this matcher is completely free with no signup. It draws from a fixed table of product ideas rather than live market data, so always test demand with your viewers before investing time or money.',
    },
    {
      question: 'How to use digital products for YouTubers?',
      answer:
        'Pick your niche, audience size band, and effort level, then review the ranked ideas with their fit rationales. Start with the top low-effort idea, pre-sell or poll your audience, and only build once you see real interest.',
    },
    {
      question: 'What is a digital products for youtubers?',
      answer:
        'A digital products for youtubers is a free online tool that gives you quick, accurate results without spreadsheets or manual math. This version runs entirely in your browser for instant, private results.',
    },
    {
      question: 'Do I need to create an account to use the digital products for youtubers?',
      answer:
        'No account needed. Open the digital products for youtubers, enter your values, and see results immediately - nothing is stored or sent anywhere.',
    },
  ],
  assumptions: [
    'Fit scores (1–5) are opinionated judgments from a fixed table — not backed by sales or trend data.',
    'The audience boost rule (+0.5 for digital at small audiences, services at large audiences) is a heuristic, not research.',
    'Ideas are generic per niche; they are not personalized to your channel\'s topic or audience.',
    'No pricing, revenue estimates, or demand guarantees are given — validate with your own audience.',
  ],
  jsonLd: [],
};
