import type { ToolInput, ToolOutput } from '../../../src/lib/registry/types.ts';
import type { ToolContent } from '../../../src/templates/types.ts';

const TOOL_URL = 'https://husnainblogger.com/tools/instagram/q-a-sticker-prompt-generator/';

export const inputs: ToolInput[] = [
  {
    id: 'niche',
    label: 'Niche',
    type: 'text',
    required: true,
    placeholder: 'e.g. skincare, freelance writing, home baking',
  },
  {
    id: 'tone',
    label: 'Tone',
    type: 'select',
    required: true,
    options: ['Friendly', 'Funny', 'Professional', 'Bold'],
  },
  {
    id: 'count',
    label: 'Number of prompts',
    type: 'number',
    required: false,
    placeholder: '5',
    validation: { min: 1, max: 10 },
  },
];

export const outputs: ToolOutput[] = [
  {
    id: 'prompts',
    label: 'Q&A sticker prompts',
    type: 'list',
    description: 'Free ask me a question sticker ideas 2026: Question-sticker prompts in your chosen tone, each ready to paste. Fast, private, no signup - try it now!',
  },
  {
    id: 'copyAll',
    label: 'Copy all prompts',
    type: 'copy',
    description: 'All prompts as plain text, ready to paste.',
  },
  {
    id: 'promptCount',
    label: 'Prompts generated',
    type: 'number',
    description: 'How many prompts were generated.',
  },
];

export const content: ToolContent = {
  title: 'Ask Me a Question Sticker Ideas 2026 – Free | HusnainBlogger',
  description:
    'Get ask me a question sticker ideas in friendly, funny, professional, or bold tone. Enter your niche, copy ready-to-post prompts — free, no signup. Try it now!',
  howTo: [
    'Type your niche into the "Niche" box — e.g. "skincare" or "freelance writing".',
    'Pick a "Tone" for the prompts: Friendly, Funny, Professional, or Bold.',
    'Choose how many prompts you want with "Number of prompts" (1–10, defaults to 5).',
    'Run the tool to get question-sticker prompts written in your chosen tone.',
    'Use "Copy all prompts" and paste a prompt into the Questions sticker on your Instagram story.',
  ],
  methodology:
    'This tool assembles prompts from two fixed, hand-written banks: 12 tone openers (3 per tone) and 14 core prompt templates. Prompt N pairs opener N with core template N in bank order and inserts your niche verbatim — the tone changes the opening line\u2019s voice only. Nothing is written by AI, and the same niche, tone and count always produce the same prompts.',
  examples: [
    {
      title: 'Skincare, friendly tone',
      inputs: { niche: 'skincare', tone: 'Friendly', count: 3 },
      note: 'Three warm, welcoming question prompts about skincare.',
    },
    {
      title: 'Fitness, bold tone',
      inputs: { niche: 'home workouts', tone: 'Bold', count: 5 },
      note: 'Five high-energy prompts that invite spicy questions.',
    },
    {
      title: 'Default count',
      inputs: { niche: 'book reviews', tone: 'Professional' },
      note: 'Omitting the count gives you the default 5 prompts.',
    },
  ],
  faqs: [
    {
      question: 'What is the best ask me a question sticker ideas?',
      answer:
        'The best ask me a question sticker ideas invite a specific kind of reply — like "What\u2019s your biggest struggle with X?" or "Drop your hot takes, I\u2019ll rate them." This tool gives you 14 such prompts in four tones: enter your niche, pick a tone, and copy the ones that fit your audience.',
    },
    {
      question: 'Is there a free ask me a question sticker ideas?',
      answer:
        'Yes — this ask me a question sticker ideas generator is completely free with no signup. You can generate between 1 and 10 prompts per run in any of the four tones, and run it again for as many niches as you like.',
    },
    {
      question: 'How to use ask me a question sticker?',
      answer:
        'Enter your niche, pick a tone, and copy a prompt from the tool. In the Instagram app, create a story, add the Questions sticker, and paste the prompt into the "Ask me a question" field so followers know what to ask about.',
    },
    {
      question: 'How does an ask me a question sticker ideas work?',
      answer:
        'You provide a niche and a tone, and the tool pairs 12 hand-written tone openers with 14 hand-written prompt templates, inserting your niche into each. Nothing is generated by AI, so the same niche, tone and count always return the same prompts.',
    },
    {
      question: 'How does the ask me a question sticker ideas work?',
      answer:
        'Enter your details using the inputs above and the ask me a question sticker ideas calculates everything instantly in your browser. No data leaves your device, and you get results the moment you change any value.',
    },
    {
      question: 'Is the ask me a question sticker ideas free to use?',
      answer:
        'Yes - this ask me a question sticker ideas is completely free with no signup, no account, and no usage limits. It runs 100% in your browser.',
    },
    {
      question: 'What is an ask me a question sticker ideas?',
      answer:
        'An ask me a question sticker ideas is a free online tool that gives you quick, accurate results without spreadsheets or manual math. This version runs entirely in your browser for instant, private results.',
    },
  ],
  assumptions: [
    'Prompts come from 26 fixed bank entries (12 tone openers + 14 core prompts) — not AI generation.',
    'The tone only changes the opening line\u2019s voice; it does not rewrite the core prompt.',
    'Prompts are starting points — adapt the wording to your voice before posting.',
  ],
  jsonLd: [
    {
      '@type': 'SoftwareApplication',
      name: 'Ask Me a Question Sticker Ideas 2026 – Free | HusnainBlogger',
      url: TOOL_URL,
      applicationCategory: 'Utilities',
      operatingSystem: 'Web',
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      description: 'Free ask me a question sticker ideas 2026: Question-sticker prompts in your chosen tone, each ready to paste. Fast, private, no signup - try it now!',
    },
    {
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://husnainblogger.com/' },
        { '@type': 'ListItem', position: 2, name: 'Tools', item: 'https://husnainblogger.com/tools/' },
        {
          '@type': 'ListItem',
          position: 3,
          name: 'Instagram',
          item: 'https://husnainblogger.com/tools/instagram/',
        },
        {
          '@type': 'ListItem',
          position: 4,
          name: 'Q&A Sticker Prompt Generator',
          item: TOOL_URL,
        },
      ],
    },
  ],
};
