import type { ToolInput, ToolOutput } from '../../../src/lib/registry/types.ts';
import type { ToolContent } from '../../../src/templates/types.ts';

const TOOL_URL = 'https://husnainblogger.com/tools/instagram/story-poll-idea-generator/';

export const inputs: ToolInput[] = [
  {
    id: 'topic',
    label: 'Topic',
    type: 'text',
    required: true,
    placeholder: 'e.g. morning routines, home workouts, skincare',
  },
  {
    id: 'count',
    label: 'Number of polls',
    type: 'number',
    required: false,
    placeholder: '5',
    validation: { min: 1, max: 10 },
  },
];

export const outputs: ToolOutput[] = [
  {
    id: 'polls',
    label: 'Poll ideas',
    type: 'table',
    description: 'Free instagram story poll questions 2026: Poll question with its two matched answer options. Instant, private, and mobile-friendly. No signup - try it free!',
  },
  {
    id: 'copyAll',
    label: 'Copy all polls',
    type: 'copy',
    description: 'All poll ideas as plain text, ready to paste.',
  },
  {
    id: 'pollCount',
    label: 'Polls generated',
    type: 'number',
    description: 'How many poll ideas were generated.',
  },
];

export const content: ToolContent = {
  title: 'Instagram Story Poll Questions 2026 – Free | HusnainBlogger',
  description:
    'Generate instagram story poll questions with ready-made answer options. Pick a topic, copy your polls, and boost story replies — free, no signup. Try it now!',
  howTo: [
    'Type your topic into the "Topic" box — e.g. "morning routines" or "home workouts".',
    'Choose how many polls you want with "Number of polls" (1–10, defaults to 5).',
    'Run the tool to get poll questions, each paired with two tap-ready answer options.',
    'Use "Copy all polls" to grab the full list as plain text.',
    'In Instagram, add a Poll sticker to your story and paste in the question and both options.',
  ],
  methodology:
    'This tool assembles polls from a fixed bank of 12 hand-written question templates, each paired with answer options that fit that question. It returns the first N templates in bank order and inserts your topic verbatim — nothing is written by AI, and the same topic and count always produce the same polls.',
  examples: [
    {
      title: 'Fitness polls',
      inputs: { topic: 'home workouts', count: 3 },
      note: 'Three poll ideas about home workouts with matched Yes/No style options.',
    },
    {
      title: 'Food polls, full set',
      inputs: { topic: 'meal prep', count: 10 },
      note: 'All 10 poll templates filled with the meal-prep topic.',
    },
    {
      title: 'Default count',
      inputs: { topic: 'skincare' },
      note: 'Omitting the count gives you the default 5 polls.',
    },
  ],
  faqs: [
    {
      question: 'What is the best instagram story poll questions?',
      answer:
        'The best instagram story poll questions are short, opinion-based, and easy to answer with one tap — like "Is this worth the hype?" with Yes/No options. This tool gives you 12 such templates: enter a topic and each question comes with two ready-made answer options.',
    },
    {
      question: 'Is there a free instagram story poll questions?',
      answer:
        'Yes — this instagram story poll questions generator is completely free with no signup. You can generate between 1 and 10 poll ideas per run, and run it as many times as you like for different topics.',
    },
    {
      question: 'How to use instagram story poll questions?',
      answer:
        'Enter your topic and pick how many polls you want (1–10), then copy a question and its two options. In the Instagram app, create a story, add the Poll sticker, and paste the question and both answers into the sticker fields.',
    },
    {
      question: 'How does an instagram story poll questions work?',
      answer:
        'You provide a topic, and the tool fills 12 fixed, hand-written poll templates with your topic — each template already includes two matching answer options. Nothing is generated by AI, so the same topic and count always return the same polls.',
    },
    {
      question: 'How does the instagram story poll questions work?',
      answer:
        'Enter your details using the inputs above and the instagram story poll questions calculates everything instantly in your browser. No data leaves your device, and you get results the moment you change any value.',
    },
    {
      question: 'Is the instagram story poll questions free to use?',
      answer:
        'Yes - this instagram story poll questions is completely free with no signup, no account, and no usage limits. It runs 100% in your browser.',
    },
    {
      question: 'What is an instagram story poll questions?',
      answer:
        'An instagram story poll questions is a free online tool that gives you quick, accurate results without spreadsheets or manual math. This version runs entirely in your browser for instant, private results.',
    },
  ],
  assumptions: [
    'Polls come from 12 fixed templates with pre-matched answer options — not AI generation.',
    'Options like "Team A / Team B" are placeholders you should replace with your own choices.',
    'Poll ideas are starting points — adapt the wording to your voice before posting.',
  ],
  jsonLd: [
    {
      '@type': 'SoftwareApplication',
      name: 'Instagram Story Poll Questions 2026 – Free | HusnainBlogger',
      url: TOOL_URL,
      applicationCategory: 'Utilities',
      operatingSystem: 'Web',
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      description: 'Free instagram story poll questions 2026: Poll question with its two matched answer options. Instant, private, and mobile-friendly. No signup - try it free!',
    },
    {
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://husnainblogger.com/' },
        { '@type': 'ListItem', position: 2, name: 'Tools', item: 'https://husnainblogger.com/tools/' },
        {
          '@type': 'ListItem',
          position: 3,
          name: 'Instagram',
          item: 'https://husnainblogger.com/tools/instagram/',
        },
        {
          '@type': 'ListItem',
          position: 4,
          name: 'Story Poll Idea Generator',
          item: TOOL_URL,
        },
      ],
    },
  ],
};
