import type { ToolInput, ToolOutput } from '../../../src/lib/registry/types.ts';
import type { ToolContent } from '../../../src/templates/types.ts';
import { TRACKER_ITEMS } from './logic.ts';

export const inputs: ToolInput[] = [];

export const outputs: ToolOutput[] = [];

export const trackerMode: 'checklist' | 'library' = 'library';

export const trackerItems = TRACKER_ITEMS;

export const content: ToolContent = {
  title: 'AI Voiceover Prompts',
  description:
    'Browse 48 free AI voiceover prompts: human-written templates for ads, narration, and explainers with voice direction built in. Copy any prompt and record today.',
  howTo: [
    'Browse the 3 categories: ad voiceover, narration, and explainer voiceover — 16 prompts each.',
    'Click any prompt to see its full text with placeholders like [PRODUCT] highlighted.',
    'Replace the placeholders with your product, audience, tone, and facts.',
    'Copy the finished prompt and paste it into your own AI tool (ChatGPT, Claude, Gemini, etc.).',
    'Mark prompts you have tried so you can track which templates give you the best scripts.',
  ],
  methodology:
    'This is a fixed, curated library of 48 human-written voiceover prompt templates across 3 script types. Nothing is generated by an AI model at runtime — the page displays the templates, and you run them in your own AI tool. Every prompt includes voice direction (pace, tone, emphasis cues) and honesty guards so the drafted scripts do not invent claims, figures, or prices.',
  faqs: [
    {
      question: 'What is the best ai voiceover prompts?',
      answer:
        'The best prompts include voice direction — pace, tone, and emphasis cues — not just the words. This free pack gives you 48 human-written templates for ads, narration, and explainers with direction built into every one.',
    },
    {
      question: 'Is there a free ai voiceover prompts?',
      answer:
        'Yes — all 48 prompt templates in this pack are free to browse and copy, no signup needed. You run them in your own AI tool to draft the scripts.',
    },
    {
      question: 'How to use ai voiceover prompts?',
      answer:
        'Pick the template for your script type, fill in the placeholders (product, audience, tone, facts), paste it into your AI tool, then read the draft aloud before recording. Scripts written for the eye rarely work for the ear — always do a read-through.',
    },
    {
      question: 'How does an ai voiceover prompts work?',
      answer:
        'A prompt tells an AI tool what script to write and how it should sound. This page does not run any AI itself — it is a fixed library of ready-made prompt templates you copy, customize, and run in your own AI tool.',
    },
    {
      question: 'How does the ai voiceover prompts work?',
      answer:
        'Enter your details using the inputs above and the ai voiceover prompts calculates everything instantly in your browser. No data leaves your device, and you get results the moment you change any value.',
    },
    {
      question: 'Is the ai voiceover prompts free to use?',
      answer:
        'Yes - this ai voiceover prompts is completely free with no signup, no account, and no usage limits. It runs 100% in your browser.',
    },
    {
      question: 'What is an ai voiceover prompts?',
      answer:
        'An ai voiceover prompts is a free online tool that gives you quick, accurate results without spreadsheets or manual math. This version runs entirely in your browser for instant, private results.',
    },
  ],
  assumptions: [
    'Fixed library of 48 human-written templates — nothing is generated or personalized at runtime.',
    'Templates use placeholders (e.g. [PRODUCT], [FACTS]); you fill them in before use.',
    'You need your own AI tool account to turn the templates into scripts.',
    'Pacing guidance (~150 words per minute) is a common rule of thumb, not a guarantee — always time your read-through.',
  ],
  jsonLd: [
    {
      '@type': 'SoftwareApplication',
      name: 'AI Voiceover Prompts 2026 – Free Tool | HusnainBlogger',
      url: 'https://husnainblogger.com/tools/ai-workflows/ai-voiceover-script-prompt-pack/',
      applicationCategory: 'Utilities',
      operatingSystem: 'Web',
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      description: 'Free AI Voiceover Prompts 2026 – Free Tool - no signup required.',
    },
    {
      '@type': 'WebPage',
      name: 'AI Voiceover Prompts 2026 – Free Tool | HusnainBlogger',
      url: 'https://husnainblogger.com/tools/ai-workflows/ai-voiceover-script-prompt-pack/',
      description: 'Browse 48 free AI voiceover prompts: human-written templates for ads, narration, and explainers with voice direction built in. Copy any prompt and record today.',
    },
    {
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://husnainblogger.com/' },
        { '@type': 'ListItem', position: 2, name: 'Tools', item: 'https://husnainblogger.com/tools/' },
        {
          '@type': 'ListItem',
          position: 3,
          name: 'AI Workflow Tools',
          item: 'https://husnainblogger.com/tools/ai-workflows/',
        },
        {
          '@type': 'ListItem',
          position: 4,
          name: 'AI Voiceover Script Prompt Pack',
          item: 'https://husnainblogger.com/tools/ai-workflows/ai-voiceover-script-prompt-pack/',
        },
      ],
    },
  ],
};
