/**
 * meta.ts — <head> metadata builder for every page type.
 *
 * Data flow: registry/MA3 content → buildMeta() → PageMeta → renderMetaTags()
 * → emitted into BaseLayout.astro / ToolPageLayout.astro. Title/description
 * FORMULAS implement docs/seo/METADATA_SCHEMA.md; MA3-authored overrides
 * (`metaTitle`, `metaDescription`) always win over formulas. CI enforces the
 * hard caps (title ≤70, description ≤170) and per-page uniqueness.
 *
 * Honesty rules enforced here:
 * - No invented claims: the "free / no signup" phrasing is only used when
 *   `isFree === true` (the platform rule), never blindly.
 * - og:image: never a broken tag. A per-page image is emitted ONLY when
 *   `ogImage` is supplied AND exists; otherwise the site default from
 *   site.config is used. Empty string input = fall back to default, not omitted.
 */

import { siteConfig } from '../../../../../config/site.config.js';
import { canonical, cleanCanonical, homeUrl, hubUrl, toolUrl } from './urls.js';

export interface MetaInput {
  /** Page kind drives title formula + defaults. */
  kind: 'tool' | 'hub' | 'tools-index' | 'home' | 'utility' | '404';
  /** Tool display name from inventory, e.g. "Tag Relevance Scorer". */
  name: string;
  /** MA3 primary keyword, e.g. "youtube tag checker". Title-cased by the formula. */
  primaryKeyword?: string;
  /** MA3-authored title override. Wins over the formula. */
  metaTitle?: string;
  /** MA3-authored description override. Wins over the formula. */
  metaDescription?: string;
  /** One plain sentence describing what the page/tool does (MA3 content). */
  summary?: string;
  /** Tool/category slug pair for canonical construction. */
  categorySlug?: string;
  toolSlug?: string;
  /** Human category name for hub breadcrumbs/titles, e.g. "YouTube". */
  categoryName?: string;
  /** Tool count on the hub — derived from the registry at codegen, never hardcoded. */
  toolCount?: number;
  /** Verified-existing per-page OG image path (from base). Omit → site default. */
  ogImage?: string;
  /** alt text for og:image. */
  ogImageAlt?: string;
  /** Robots directive. Defaults per kind; 'noindex, follow' for filtered/search views. */
  robots?: string;
  /** Platform pricing truth. Only emit "free" language when true. */
  isFree?: boolean;
  /** Explicit canonical override (rare; canonical self-reference is the default). */
  canonicalOverride?: string;
}

export interface PageMeta {
  title: string;
  description: string;
  canonical: string;
  robots: string;
  og: { title: string; description: string; type: 'website'; url: string; image: string; imageAlt?: string };
  twitter: { card: 'summary_large_image'; title: string; description: string; image: string };
  /** 'formula' = generated by the rules below; 'authored' = MA3 supplied it. CI can audit the mix. */
  titleSource: 'formula' | 'authored';
  descriptionSource: 'formula' | 'authored';
  /** True when a hard cap was hit and the value was truncated — CI must flag these for MA3 review. */
  truncated: boolean;
}

export const TITLE_HARD_CAP = 70; // docs/seo/METADATA_SCHEMA.md §1
export const DESCRIPTION_HARD_CAP = 170; // docs/seo/METADATA_SCHEMA.md §2

function titleCase(s: string): string {
  return s.replace(/\w\S*/g, (w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase());
}

function truncate(s: string, cap: number): { value: string; truncated: boolean } {
  if (s.length <= cap) return { value: s, truncated: false };
  // Cut at the last word boundary before the cap, then add ellipsis.
  const cut = s.slice(0, cap - 1).replace(/\s+\S*$/, '');
  return { value: `${cut}…`, truncated: true };
}

function freePhrase(isFree: boolean | undefined): string {
  return isFree === false ? '' : ' Free, no signup.';
}

export function buildMeta(input: MetaInput): PageMeta {
  const brand = siteConfig.name;
  let rawTitle: string;
  let titleSource: PageMeta['titleSource'] = 'formula';
  let rawDescription: string;
  let descriptionSource: PageMeta['descriptionSource'] = 'formula';
  let canonicalUrl: string;

  if (input.metaTitle) {
    rawTitle = input.metaTitle;
    titleSource = 'authored';
  } else if (input.kind === 'tool') {
    // METADATA_SCHEMA §1.1: primary keyword FIRST (Title Case), brand last.
    const kw = input.primaryKeyword ? titleCase(input.primaryKeyword) : titleCase(input.name);
    rawTitle = `${kw} | ${brand}`;
  } else if (input.kind === 'hub') {
    // §1.2: "<N> Free <Category> Tools | Brand" — N derived from registry.
    const n = input.toolCount ?? 50;
    rawTitle = `${n} Free ${input.categoryName ?? input.name} Tools | ${brand}`;
  } else if (input.kind === 'home') {
    rawTitle = `${brand} — 500 Free Mini Tools for Creators & Bloggers`; // §1.3 (brand-first only here)
  } else if (input.kind === '404') {
    rawTitle = `Page Not Found | ${brand}`;
  } else {
    rawTitle = `${input.name} | ${brand}`; // §1.4 utility pages + tools index
  }

  if (input.metaDescription) {
    rawDescription = input.metaDescription;
    descriptionSource = 'authored';
  } else if (input.kind === 'tool') {
    const what = input.summary ?? `Use the ${input.name} online.`;
    rawDescription = `${what} Get instant results in your browser.${freePhrase(input.isFree)}`;
  } else if (input.kind === 'hub') {
    const n = input.toolCount ?? 50;
    rawDescription = `Browse ${n} free ${input.categoryName ?? input.name} tools: generators, checkers, calculators and more.${freePhrase(input.isFree)}`;
  } else if (input.kind === 'home') {
    rawDescription = `500 free mini tools for creators and bloggers — SEO, YouTube, TikTok, Instagram and more. 100% in your browser, no signup.`;
  } else {
    rawDescription = `${input.summary ?? input.name} — ${brand}.`;
  }

  const t = truncate(rawTitle, TITLE_HARD_CAP);
  const d = truncate(rawDescription, DESCRIPTION_HARD_CAP);

  if (input.canonicalOverride) {
    canonicalUrl = cleanCanonical(input.canonicalOverride);
  } else if (input.kind === 'tool' && input.categorySlug && input.toolSlug) {
    canonicalUrl = toolUrl(input.categorySlug, input.toolSlug);
  } else if (input.kind === 'hub' && input.categorySlug) {
    canonicalUrl = hubUrl(input.categorySlug);
  } else if (input.kind === 'home') {
    canonicalUrl = homeUrl();
  } else {
    canonicalUrl = canonical(`/${input.toolSlug ?? ''}`);
  }

  const robots = input.robots ?? defaultRobots(input.kind);

  // og:image: verified per-page image wins; else the site default (always exists
  // in app/public/). Never emit a path that hasn't been verified — the caller
  // passes ogImage only for images MA2 generated and MA4 verified.
  const image = input.ogImage && input.ogImage.length > 0 ? input.ogImage : siteConfig.defaultOgImage;
  const imageUrl = image.startsWith('http') ? image : canonical(image);

  return {
    title: t.value,
    description: d.value,
    canonical: canonicalUrl,
    robots,
    og: {
      title: t.value.length > 60 ? truncate(t.value, 60).value : t.value, // may shorten, never rewrite
      description: d.value,
      type: 'website', // never fake `article` on tool pages
      url: canonicalUrl, // og:url = canonical, always
      image: imageUrl,
      ...(input.ogImageAlt ? { imageAlt: input.ogImageAlt } : {}),
    },
    twitter: {
      card: 'summary_large_image',
      title: t.value.length > 60 ? truncate(t.value, 60).value : t.value,
      description: d.value,
      image: imageUrl,
    },
    titleSource,
    descriptionSource,
    truncated: t.truncated || d.truncated,
  };
}

function defaultRobots(kind: MetaInput['kind']): string {
  // index,follow is the default — emitting it explicitly is harmless and
  // makes the noindex cases (filtered views, search) auditable in one place.
  switch (kind) {
    case '404':
      return 'noindex, follow';
    default:
      return 'index, follow';
  }
}

/** Escape once, at the render boundary — never trust content-layer strings in <head>. */
function esc(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/** Render the full <head> tag block for BaseLayout.astro. */
export function renderMetaTags(m: PageMeta): string {
  const tags = [
    `<title>${esc(m.title)}</title>`,
    `<meta name="description" content="${esc(m.description)}" />`,
    `<link rel="canonical" href="${esc(m.canonical)}" />`,
    `<meta name="robots" content="${esc(m.robots)}" />`,
    `<meta property="og:title" content="${esc(m.og.title)}" />`,
    `<meta property="og:description" content="${esc(m.og.description)}" />`,
    `<meta property="og:type" content="${esc(m.og.type)}" />`,
    `<meta property="og:url" content="${esc(m.og.url)}" />`,
    `<meta property="og:image" content="${esc(m.og.image)}" />`,
    ...(m.og.imageAlt ? [`<meta property="og:image:alt" content="${esc(m.og.imageAlt)}" />`] : []),
    `<meta name="twitter:card" content="${esc(m.twitter.card)}" />`,
    `<meta name="twitter:title" content="${esc(m.twitter.title)}" />`,
    `<meta name="twitter:description" content="${esc(m.twitter.description)}" />`,
    `<meta name="twitter:image" content="${esc(m.twitter.image)}" />`,
    `<meta name="theme-color" content="${esc(siteConfig.themeColor)}" />`,
  ];
  return tags.join('\n');
}
