import type { ToolInput, ToolOutput } from '../../../src/lib/registry/types.ts';
import type { ToolContent } from '../../../src/templates/types.ts';
import type { BuilderField } from '../../../src/templates/types.ts';

const TOOL_URL = 'https://husnainblogger.com/tools/ai-workflows/testimonial-request-builder/';

export const inputs: ToolInput[] = [];

export const itemFields: BuilderField[] = [
  {
    id: 'clientName',
    label: 'Client name',
    type: 'text',
    required: true,
    placeholder: 'e.g. Sara Ahmed',
  },
  {
    id: 'productName',
    label: 'Product or service name',
    type: 'text',
    required: true,
    placeholder: 'e.g. Email List Accelerator',
  },
  {
    id: 'channel',
    label: 'Channel (email, DM, or form)',
    type: 'text',
    required: false,
    placeholder: 'email',
  },
];

export const outputs: ToolOutput[] = [
  {
    id: 'requestMessages',
    label: 'Request messages',
    type: 'list',
    description:
    'Free testimonial request template 2026: Ready-to-send testimonial request message for each client. Get instant results. free now.',
  },
  {
    id: 'followUpMessages',
    label: 'Follow-up messages',
    type: 'list',
    description:
    'Polite follow-up message for each client, sent a few days later.',
  },
];

export const content: ToolContent = {
  title: 'Testimonial Request Template',
  description:
    'Ask for testimonials the right way with a free testimonial request template. Add client details, pick email/DM/form, and get ready-to-send messages.',
  howTo: [
    'Add one entry per client with their name and your product or service name.',
    'Set the channel for each entry: email, DM, or form (defaults to email).',
    'Run the tool to get a request message and a follow-up message per client.',
    'Replace the [your name] and [your form link] placeholders, then send.',
    'Wait 3–5 days, then send the follow-up message to anyone who did not reply.',
  ],
  methodology:
    'The tool fills 6 fixed message templates (3 channels x request + follow-up) with your client and product names. Templates are fixed human-written text — nothing is generated by AI. Only the request is written; the testimonial itself must always come from the real client in their own words.',
  faqs: [
    {
      question: 'What is the best testimonial request template?',
      answer:
        'The best request is short, specific, and low-pressure: name the product, ask for 2–3 sentences, and make replying easy. This free builder gives you channel-specific templates (email, DM, form) plus a polite follow-up for each client.',
    },
    {
      question: 'Is there a free testimonial request template?',
      answer:
        'Yes — this testimonial request builder is completely free with no signup. Add as many clients as you like and get a request message and a follow-up message for each one.',
    },
    {
      question: 'How to use testimonial request?',
      answer:
        'Enter the client\'s name, your product name, and the channel, then run the tool. Copy the request message, replace the [your name] and [your form link] placeholders, and send it. Use the follow-up message a few days later for non-responders.',
    },
    {
      question: 'How does a testimonial request template work?',
      answer:
        'It slots your client and product names into fixed, channel-specific message templates — one initial request and one follow-up. It writes the ask, never the testimonial: the actual review must come from the client in their own words.',
    },
    {
      question: 'What is a testimonial request template?',
      answer:
        'A testimonial request template is a free online tool that gives you quick, accurate results without spreadsheets or manual math. This version runs entirely in your browser for instant, private results.',
    },
  ],
  assumptions: [
    'The tool writes the request, never the testimonial. Any testimonial you publish must be written by the real client — never write or edit fake reviews.',
    'Only ask clients who genuinely used your product; ask permission before publishing any testimonial with their name.',
  ],
  jsonLd: [],
};
