import type { ToolInput, ToolOutput } from '../../../src/lib/registry/types.ts';
import type { ToolContent } from '../../../src/templates/types.ts';

const TOOL_URL = 'https://husnainblogger.com/tools/instagram/aesthetic-feed-theme-planner/';

export const inputs: ToolInput[] = [
  {
    id: 'theme',
    label: 'Feed theme',
    type: 'select',
    required: true,
    options: ['minimal', 'bold', 'pastel', 'moody', 'editorial'],
  },
  {
    id: 'niche',
    label: 'Your niche (optional)',
    type: 'text',
    required: false,
    placeholder: 'e.g. coffee shops, fitness, fashion',
  },
];

export const outputs: ToolOutput[] = [
  {
    id: 'palette',
    label: 'Color palette',
    type: 'list',
    description:
    'Free instagram feed theme planner 2026: 6 curated rules that keep the theme consistent. free.',
  },
  {
    id: 'doList',
    label: 'Do list',
    type: 'list',
    description:
    '6 curated rules that keep the theme consistent.',
  },
  {
    id: 'dontList',
    label: "Don't list",
    type: 'list',
    description:
    '6 curated mistakes that break the theme.',
  },
  {
    id: 'postingRhythm',
    label: 'Posting rhythm',
    type: 'text',
    description:
    'Curated posting frequency suggestion for this theme.',
  },
  {
    id: 'sampleGrid',
    label: 'Sample 3x3 grid',
    type: 'list',
    description:
    "A row-by-row sample grid pattern in this theme's style.",
  },
  {
    id: 'themeNote',
    label: 'Plan summary',
    type: 'text',
    description:
    'Theme confirmation, niche tip, and the honesty note.',
  },
];

export const content: ToolContent = {
  title: 'Instagram Feed Theme Planner',
  description:
    'Plan a consistent Instagram feed theme free with a curated planner. Pick minimal, bold, pastel, moody or editorial and get palettes, dos and donts.',
  howTo: [
    'Choose your feed theme from the dropdown: minimal, bold, pastel, moody, or editorial.',
    'Optionally add your niche (e.g. "coffee shops") to get a tailored shooting tip in the plan summary.',
    'Run the tool to get the theme\'s 6-color palette, 6 dos, 6 don\'ts, posting rhythm, and a sample 3x3 grid.',
    'Apply the palette to your next 9 posts and follow the sample grid row pattern for instant consistency.',
  ],
  methodology:
    'This tool returns hand-curated guidance — nothing is generated by AI and no API is called. Each of the 5 themes ships with a fixed 6-color palette, 6 do rules, 6 don\'t rules, one posting-rhythm suggestion, and a 9-cell sample grid pattern, all written by hand. The optional niche only shapes the closing tip; it never changes the curated bank. An unknown theme value defaults to "minimal" and says so in the output.',
  examples: [
    {
      title: 'Minimal theme for a coffee shop',
      inputs: { theme: 'minimal', niche: 'coffee shops' },
      note: 'Airy white palette, negative-space rules, and a niche tip about consistent daylight shooting.',
    },
    {
      title: 'Moody theme, no niche',
      inputs: { theme: 'moody', niche: '' },
      note: 'Dark cinematic guidance with 2–3 posts per week as the curated rhythm.',
    },
    {
      title: 'Bold theme for streetwear',
      inputs: { theme: 'bold', niche: 'streetwear' },
      note: 'High-contrast palette with a signature-color rule repeated in every row.',
    },
  ],
  faqs: [
    {
      question: 'What is the best Instagram feed theme planner?',
      answer:
        'The best Instagram feed theme planner gives you a concrete palette plus practical do/don\'t rules and a sample grid — not just vague inspiration. This tool is free: pick one of 5 curated themes and get exactly that, ready to apply to your next 9 posts.',
    },
    {
      question: 'Is there a free Instagram feed theme planner?',
      answer:
        'Yes — this Instagram feed theme planner is completely free with no signup. All five themes, palettes, and grid patterns are included; nothing is locked behind an account.',
    },
    {
      question: 'How to plan Instagram feed theme?',
      answer:
        'Pick one theme and commit for at least a month: lock a 6-color palette, edit every photo with the same preset, and alternate post types in a repeating 3x3 pattern. This tool hands you the palette, the rules, and the sample grid — your job is shooting and editing consistently.',
    },
    {
      question: 'How does the instagram feed theme planner work?',
      answer:
        'Enter your details using the inputs above and the instagram feed theme planner calculates everything instantly in your browser. No data leaves your device, and you get results the moment you change any value.',
    },
    {
      question: 'Is the instagram feed theme planner free to use?',
      answer:
        'Yes - this instagram feed theme planner is completely free with no signup, no account, and no usage limits. It runs 100% in your browser.',
    },
    {
      question: 'What is an instagram feed theme planner?',
      answer:
        'An instagram feed theme planner is a free online tool that gives you quick, accurate results without spreadsheets or manual math. This version runs entirely in your browser for instant, private results.',
    },
    {
      question: 'Do I need to create an account to use the instagram feed theme planner?',
      answer:
        'No account needed. Open the instagram feed theme planner, enter your values, and see results immediately - nothing is stored or sent anywhere.',
    },
  ],
  assumptions: [
    'All guidance is hand-curated opinion, not AI analysis and not a guarantee of growth — consistent execution matters more than the theme itself.',
    'The niche input only shapes the closing tip; it does not change any palette, rule, or grid pattern.',
    'Posting-rhythm suggestions are starting points; your audience data should override them.',
  ],
  jsonLd: [],
};
