import type { ToolInput, ToolOutput } from '../../../src/lib/registry/types.ts';
import type { ToolContent } from '../../../src/templates/types.ts';

const TOOL_URL = 'https://husnainblogger.com/tools/ai-workflows/cta-prompt-library/';

export const inputs: ToolInput[] = [
  {
    id: 'ctaGoal',
    label: 'CTA goal',
    type: 'select',
    required: true,
    options: ['click', 'subscribe', 'buy', 'share'],
  },
  {
    id: 'tone',
    label: 'Tone',
    type: 'select',
    required: true,
    options: ['direct', 'friendly', 'urgent', 'playful', 'professional'],
  },
];

export const outputs: ToolOutput[] = [
  {
    id: 'ctaLines',
    label: 'CTA lines (copy any line)',
    type: 'list',
    description:
    'Free call to action prompts 2026: 3 human-written CTA lines matching your goal and tone, ready to paste. Get instant results. free now.',
  },
];

export const content: ToolContent = {
  title: 'Call To Action Prompts',
  description:
    'Browse a free library of human-written call to action prompts. Filter 60 lines by goal and tone, then copy them into your pages and emails. Start.',
  howTo: [
    'Pick your CTA goal from the dropdown: click, subscribe, buy, or share.',
    'Choose the tone that fits your brand: direct, friendly, urgent, playful, or professional.',
    'Run the tool to see the 3 matching lines from the fixed library.',
    'Copy any line and paste it straight into your page, email, or ad.',
  ],
  methodology:
    'This is a fixed library of 60 human-written CTA lines (4 goals x 5 tones x 3 lines). Nothing is written by AI at runtime — the tool only filters the bank by your goal and tone, so the output is identical for the same inputs every time.',
  examples: [
    {
      title: 'Newsletter signup (friendly)',
      inputs: { ctaGoal: 'subscribe', tone: 'friendly' },
      note: 'Warm signup lines for a blog newsletter form.',
    },
    {
      title: 'Product launch (urgent)',
      inputs: { ctaGoal: 'buy', tone: 'urgent' },
      note: 'Time-pressure buy lines for a launch email.',
    },
    {
      title: 'Blog post share (playful)',
      inputs: { ctaGoal: 'share', tone: 'playful' },
      note: 'Fun share lines for the end of a blog post.',
    },
  ],
  faqs: [
    {
      question: 'What is the best call to action prompts?',
      answer:
        'The best CTA lines are short, specific, and matched to the reader\'s goal — this library gives you 60 human-written lines organized by goal (click, subscribe, buy, share) and tone, so you can pick one that fits instead of writing from scratch.',
    },
    {
      question: 'Is there a free call to action prompts?',
      answer:
        'Yes — this tool is completely free. The whole 60-line library is available with no signup; you just pick a goal and tone and copy the lines you like.',
    },
    {
      question: 'How to use call to action prompts?',
      answer:
        'Pick your goal (click, subscribe, buy, or share) and a tone, run the tool, then copy any of the 3 matching lines into your landing page, email, or ad. You can edit the wording to match your brand.',
    },
    {
      question: 'How does a call to action prompts work?',
      answer:
        'You select a goal and tone, and the tool looks up the matching lines in a fixed bank of 60 human-written CTAs. Nothing is generated by AI — the same inputs always return the same lines.',
    },
    {
      question: 'What is a call to action prompts?',
      answer:
        'A call to action prompts is a free online tool that gives you quick, accurate results without spreadsheets or manual math. This version runs entirely in your browser for instant, private results.',
    },
      {
      question: 'Is this call to action prompts tool really free?',
      answer: 'Yes, completely free with no account required. Use it as many times as you want — there are no usage limits or hidden paywalls.',
    },
    {
      question: 'How do I use this call to action prompts tool?',
      answer: 'Enter your details in the fields above and get instant results. Everything runs in your browser — no signup, no waiting, no data uploaded.',
    },
  ],
  assumptions: [
    'Fixed bank of 60 human-written CTA lines (4 goals x 5 tones x 3 lines each). Nothing is generated at runtime and no new copy is written by AI.',
    'Lines are generic starting points — adapt wording, offers, and urgency claims to your actual product so the CTA stays honest.',
  ],
  jsonLd: [
    {
      '@type': 'WebPage',
      name: 'Call To Action Prompts 2026',
      url: TOOL_URL,
      description:
    'Free call to action prompts 2026: 3 human-written CTA lines matching your goal and tone, ready to paste. Get instant results. free now.',
    },
  ],
};
