import type { ToolInput, ToolOutput } from '../../../src/lib/registry/types.ts';
import type { ToolContent } from '../../../src/templates/types.ts';

const TOOL_URL = 'https://husnainblogger.com/tools/blogging-seo/comparison-table-html-generator/';

export const inputs: ToolInput[] = [
  {
    id: 'headers',
    label: 'Table headers (one per line, 2–6)',
    type: 'textarea',
    required: true,
    placeholder: 'Feature\nProduct A\nProduct B',
  },
  {
    id: 'rows',
    label: 'Table rows (one per line, cells separated by |)',
    type: 'textarea',
    required: true,
    placeholder: 'Price | $10 | $20\nRating | 4.5 | 4.0',
  },
  {
    id: 'highlightColumn',
    label: 'Highlight column (optional, 0 = first)',
    type: 'number',
    required: false,
    placeholder: '1',
    validation: { min: 0 },
  },
];

export const outputs: ToolOutput[] = [
  {
    id: 'tableHtml',
    label: 'Table HTML (copy)',
    type: 'copy',
    description: 'Free comparison table generator 2026: Ready-to-paste HTML table with minimal inline styles — works in any blog theme. Fast, private, no signup - try it now!',
  },
  {
    id: 'tableCss',
    label: 'Table CSS (copy)',
    type: 'copy',
    description: 'Optional matching CSS block — the HTML already carries inline styles, so this is skippable.',
  },
];

export const content: ToolContent = {
  title: 'Comparison Table Generator 2026 – Free | HusnainBlogger',
  description:
    'Build a clean comparison table for your blog in seconds. Enter headers and rows, copy the ready-to-paste HTML, and drop it into any post. Try it free!',
  howTo: [
    'Type your column headers in "Table headers" — one per line, between 2 and 6.',
    'Type each row in "Table rows" — one row per line, with cells separated by the | character.',
    'Optionally enter a "Highlight column" number (0 = first column) to visually emphasize one product.',
    'Run the tool and review the table preview.',
    'Copy the "Table HTML" and paste it into your post\'s HTML or Custom HTML block. Add the "Table CSS" to your theme only if you want to restyle it.',
  ],
  methodology:
    'Your headers and rows are parsed as plain text, HTML-escaped (so nothing you type can inject markup), and assembled into a semantic <table> wrapped in a scrollable container for mobile. Styling is intentionally minimal and inline so the snippet works in any blog theme without edits. Nothing is generated by AI — the output contains only your own words, structured as a table.',
  examples: [
    {
      title: 'Two-product comparison',
      inputs: { headers: 'Feature\nProduct A\nProduct B', rows: 'Price | $10 | $20\nFree trial | Yes | No', highlightColumn: 1 },
      note: 'A basic 3-column table with Product A highlighted.',
    },
    {
      title: 'No highlight',
      inputs: { headers: 'Plan\nStarter\nPro', rows: 'Price/mo | $9 | $29\nUsers | 1 | 10' },
      note: 'Omitting the highlight column produces a plain table.',
    },
    {
      title: 'Four columns',
      inputs: { headers: 'Tool\nA\nB\nC', rows: 'Free plan | Yes | No | Yes\nSupport | Email | Chat | Chat' },
      note: 'Works with up to 6 columns.',
    },
  ],
  faqs: [
    {
      question: 'What is the best comparison table generator?',
      answer:
        'The best comparison table generator produces clean, responsive HTML you can paste into any blog theme without fighting your site\'s CSS, and it escapes your content safely. This tool does both — you get inline-styled table HTML plus an optional CSS block, free with no signup.',
    },
    {
      question: 'Is there a free comparison table generator?',
      answer:
        'Yes — this comparison table generator is completely free with no signup. Build tables with 2–6 columns and up to 20 rows, and regenerate as often as you like.',
    },
    {
      question: 'How to generate comparison table?',
      answer:
        'Enter your column headers one per line, then your rows one per line with cells separated by |. Optionally pick a column to highlight, run the tool, and copy the HTML into your post\'s HTML or Custom HTML block.',
    },
    {
      question: 'How does a comparison table generator work?',
      answer:
        'It takes the text you type, escapes it so it can\'t break your page, and assembles it into a semantic HTML table with minimal inline styling that works in any blog theme. Nothing is written by AI — the table contains only your own content.',
    },
    {
      question: 'How does the comparison table generator work?',
      answer:
        'Enter your details using the inputs above and the comparison table generator calculates everything instantly in your browser. No data leaves your device, and you get results the moment you change any value.',
    },
    {
      question: 'Is the comparison table generator free to use?',
      answer:
        'Yes - this comparison table generator is completely free with no signup, no account, and no usage limits. It runs 100% in your browser.',
    },
    {
      question: 'What is a comparison table generator?',
      answer:
        'A comparison table generator is a free online tool that gives you quick, accurate results without spreadsheets or manual math. This version runs entirely in your browser for instant, private results.',
    },
  ],
  assumptions: [
    'Styling is intentionally minimal and inline so the snippet works in any blog theme — customize the CSS block for a branded look.',
    'All content is HTML-escaped; you cannot inject raw HTML, scripts, or attributes through this tool.',
    'Wide tables scroll horizontally on small screens via the wrapper; the tool does not restyle your theme.',
    'Maximum 6 columns and 20 rows per table.',
  ],
  jsonLd: [
    {
      '@type': 'SoftwareApplication',
      name: 'Comparison Table Generator 2026 – Free | HusnainBlogger',
      url: TOOL_URL,
      applicationCategory: 'Utilities',
      operatingSystem: 'Web',
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      description: 'Free comparison table generator 2026: Ready-to-paste HTML table with minimal inline styles — works in any blog theme. Fast, private, no signup - try it now!',
    },
    {
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://husnainblogger.com/' },
        { '@type': 'ListItem', position: 2, name: 'Tools', item: 'https://husnainblogger.com/tools/' },
        {
          '@type': 'ListItem',
          position: 3,
          name: 'Blogging & SEO Tools',
          item: 'https://husnainblogger.com/tools/blogging-seo/',
        },
        {
          '@type': 'ListItem',
          position: 4,
          name: 'Comparison Table HTML Generator',
          item: TOOL_URL,
        },
      ],
    },
  ],
};
