import type { ToolInput, ToolOutput } from '../../../src/lib/registry/types.ts';
import type { ToolContent } from '../../../src/templates/types.ts';

export const inputs: ToolInput[] = [
  {
    id: 'text',
    label: 'Your text',
    type: 'textarea',
    required: true,
    placeholder: 'e.g. Coffee lover ☕',
    validation: { max: 500 },
  },
  {
    id: 'styleId',
    label: 'Font style',
    type: 'select',
    required: true,
    options: [
      'bold',
      'italic',
      'bold-italic',
      'script',
      'script-bold',
      'monospace',
      'double-struck',
      'fraktur',
      'fraktur-bold',
      'small-caps',
      'circled',
      'squared',
    ],
  },
];

export const outputs: ToolOutput[] = [
  { id: 'styledText', label: 'Styled text', type: 'copy' },
  { id: 'charCount', label: 'Character count', type: 'number' },
  { id: 'platformSafeNote', label: 'Compatibility note', type: 'text' },
];

const DESCRIPTION =
  'Style your bio with this free instagram fonts generator — 12 unicode styles, copy-paste ready. Preview on your phone; styled text varies by device. Try it.';

export const content: ToolContent = {
  title: 'Instagram Fonts Generator 2026 – Free Tool | HusnainBlogger',
  description: DESCRIPTION,
  howTo: [
    'Type the text you want to style (up to 500 characters) — your bio line, name, or caption.',
    'Pick one of the 12 styles: bold, italic, script, monospace, circled, squared, and more.',
    'Generate to get your styled Unicode text instantly.',
    'Copy it and paste it into your Instagram bio, name field, or caption.',
    'Preview on your phone first — styled text renders differently across devices and fonts.',
  ],
  methodology:
    'This tool is not AI and fetches nothing: it swaps each character through one of 12 fixed Unicode substitution maps (mathematical alphanumeric symbols, circled, squared, and small-caps forms). Characters with no styled equivalent pass through unchanged and are counted in the result. The output is plain Unicode text, not a font.',
  examples: [
    {
      title: 'Bio line in script',
      inputs: { text: 'Coffee lover', styleId: 'script' },
      note: 'Each letter maps to its script Unicode form; the space is kept as-is.',
    },
    {
      title: 'Bold announcement',
      inputs: { text: 'SALE', styleId: 'bold' },
      note: 'Capitals map to bold serif forms — copy and paste into your caption.',
    },
  ],
  faqs: [
    {
      question: 'What is the best instagram fonts generator?',
      answer:
        'The best one is free, works on any device, and warns you about rendering quirks. This tool gives you 12 unicode styles with copy-paste output and a device-compatibility note — always preview styled text on your phone before posting.',
    },
    {
      question: 'Is there a free instagram fonts generator?',
      answer:
        'Yes — this generator is completely free with no signup. Type your text, pick a style, copy the result, and paste it into your bio or caption.',
    },
    {
      question: 'How to generate instagram fonts?',
      answer:
        'Enter your text, choose one of the 12 styles, and copy the generated Unicode text into your Instagram bio, name, or caption. No font installation is needed — the styling lives in the characters themselves.',
    },
    {
      question: 'How does an instagram fonts generator work?',
      answer:
        'It replaces each letter and digit with a lookalike Unicode character from a fixed substitution map — for example, A becomes 𝐀 in the bold style. Characters with no styled form are kept unchanged.',
    },
    {
      question: 'How does the instagram fonts generator work?',
      answer:
        'Enter your details using the inputs above and the instagram fonts generator calculates everything instantly in your browser. No data leaves your device, and you get results the moment you change any value.',
    },
    {
      question: 'Is the instagram fonts generator free to use?',
      answer:
        'Yes - this instagram fonts generator is completely free with no signup, no account, and no usage limits. It runs 100% in your browser.',
    },
    {
      question: 'What is an instagram fonts generator?',
      answer:
        'An instagram fonts generator is a free online tool that gives you quick, accurate results without spreadsheets or manual math. This version runs entirely in your browser for instant, private results.',
    },
  ],
  assumptions: [
    '12 fixed Unicode substitution maps — nothing is generated by AI and no live data is used.',
    'Styled text is plain Unicode, not a font: some devices show empty boxes, and screen readers may read it letter by letter.',
    'Characters with no styled equivalent (e.g. most emoji, F/Q/S/X in small caps) pass through unchanged.',
    'Styled characters can double the character count; the tool warns if you exceed Instagram\'s 2,200-character caption limit.',
  ],
  jsonLd: [
    {
      '@type': 'SoftwareApplication',
      name: 'Instagram Fonts Generator 2026 – Free Tool | HusnainBlogger',
      url: 'https://husnainblogger.com/tools/instagram/stylish-fonts-generator/',
      applicationCategory: 'Utilities',
      operatingSystem: 'Web',
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      description: DESCRIPTION,
    },
    {
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://husnainblogger.com/' },
        { '@type': 'ListItem', position: 2, name: 'Tools', item: 'https://husnainblogger.com/tools/' },
        {
          '@type': 'ListItem',
          position: 3,
          name: 'Instagram Tools',
          item: 'https://husnainblogger.com/tools/instagram/',
        },
        {
          '@type': 'ListItem',
          position: 4,
          name: 'Instagram Fonts Generator',
          item: 'https://husnainblogger.com/tools/instagram/stylish-fonts-generator/',
        },
      ],
    },
  ],
};
