/**
 * FAQ Schema Generator — pure logic (zero imports, zero network, zero DOM).
 *
 * Builds a valid schema.org FAQPage JSON-LD block from Q/A pairs.
 *
 * Honesty contract (from spec honestyNote):
 * - This tool only FORMATS the user's own text into schema.org FAQPage
 *   JSON-LD. Nothing is generated by AI; there is no fixed word bank — the
 *   words in the output are always exactly the words the user typed.
 * - Validation is structural (presence + length bounds). It is NOT a
 *   guarantee that Google will show a rich result — eligibility is decided
 *   by Google, and the same Q&A content must be visible on the page.
 * - HTML in questions/answers is kept as literal text, never parsed.
 * - Deterministic: same input pairs always produce the same JSON-LD.
 *
 * Input shape for runTool values["pairs"]:
 *   - preferred: FaqPair[] (array of { question, answer })
 *   - also accepted: a textarea string in the documented format —
 *     one pair per blank-line-separated block; the first line of each block
 *     is the question, the remaining lines are the answer.
 *
 * Validation bounds (documented per the batch contract):
 *   - 1–50 pairs per block
 *   - question: 1–300 chars
 *   - answer: 1–5000 chars
 *   - duplicate questions (case-insensitive) are deduplicated
 */

export interface FaqPair {
  question: string;
  answer: string;
}

export interface FaqSchemaRunValues {
  jsonLd: string;
  errors: string[];
  pairCount: number;
}

export interface RunToolResult {
  ok: boolean;
  values?: Record<string, unknown>;
  error?: string;
}

export const MAX_PAIRS = 50;
export const MAX_QUESTION_CHARS = 300;
export const MAX_ANSWER_CHARS = 5000;

/**
 * Validate a single Q/A pair. Returns a list of error messages
 * (empty = valid). Exported so templates can show per-row feedback.
 */
export function validatePair(pair: FaqPair, index: number): string[] {
  const errors: string[] = [];
  const label = `Pair ${index + 1}`;
  if (!pair || typeof pair !== "object") {
    return [`${label}: not a question/answer pair.`];
  }
  const q = typeof pair.question === "string" ? pair.question.trim() : "";
  const a = typeof pair.answer === "string" ? pair.answer.trim() : "";
  if (q.length === 0) errors.push(`${label}: question is required.`);
  else if (q.length > MAX_QUESTION_CHARS)
    errors.push(
      `${label}: question is ${q.length} chars (max ${MAX_QUESTION_CHARS}).`
    );
  if (a.length === 0) errors.push(`${label}: answer is required.`);
  else if (a.length > MAX_ANSWER_CHARS)
    errors.push(
      `${label}: answer is ${a.length} chars (max ${MAX_ANSWER_CHARS}).`
    );
  return errors;
}

/**
 * Parse the textarea format into pairs: blank-line-separated blocks, first
 * line = question, remaining lines = answer. Empty blocks are ignored.
 */
export function parsePairsText(text: string): FaqPair[] {
  const pairs: FaqPair[] = [];
  const blocks = text.split(/\r?\n\s*\r?\n/);
  for (const block of blocks) {
    const lines = block.split(/\r?\n/).map((l) => l.trimEnd());
    // Drop leading blank lines inside the block.
    while (lines.length > 0 && lines[0].trim() === "") lines.shift();
    if (lines.length === 0) continue;
    const question = lines[0].trim();
    const answer = lines.slice(1).join("\n").trim();
    if (question === "" && answer === "") continue;
    pairs.push({ question, answer });
  }
  return pairs;
}

/**
 * Core builder: returns pretty-printed JSON-LD plus per-pair notes.
 * Invalid pairs are excluded and reported; duplicates (case-insensitive)
 * are deduplicated and reported. Deterministic — input order preserved.
 */
export function buildFaqSchema(pairs: FaqPair[]): {
  ok: boolean;
  jsonLd: string;
  errors: string[];
  pairCount: number;
  acceptedPairs: FaqPair[];
} {
  const errors: string[] = [];

  if (pairs.length === 0) {
    return {
      ok: false,
      jsonLd: "",
      errors: ["Add at least one question/answer pair."],
      pairCount: 0,
      acceptedPairs: [],
    };
  }
  if (pairs.length > MAX_PAIRS) {
    return {
      ok: false,
      jsonLd: "",
      errors: [
        `Too many pairs: ${pairs.length} (max ${MAX_PAIRS}). Split into multiple FAQ blocks.`,
      ],
      pairCount: 0,
      acceptedPairs: [],
    };
  }

  const seen = new Set<string>();
  const mainEntity: object[] = [];
  const acceptedPairs: FaqPair[] = [];

  pairs.forEach((pair, i) => {
    const pairErrors = validatePair(pair, i);
    if (pairErrors.length > 0) {
      errors.push(...pairErrors);
      return;
    }
    const q = (pair.question as string).trim();
    const a = (pair.answer as string).trim();
    const key = q.toLowerCase();
    if (seen.has(key)) {
      errors.push(
        `Pair ${i + 1}: duplicate question skipped ("${q.slice(0, 60)}${q.length > 60 ? "…" : ""}").`
      );
      return;
    }
    seen.add(key);
    acceptedPairs.push({ question: q, answer: a });
    mainEntity.push({
      "@type": "Question",
      name: q,
      acceptedAnswer: { "@type": "Answer", text: a },
    });
  });

  if (mainEntity.length === 0) {
    return { ok: false, jsonLd: "", errors, pairCount: 0, acceptedPairs: [] };
  }

  const jsonLd = JSON.stringify(
    { "@context": "https://schema.org", "@type": "FAQPage", mainEntity },
    null,
    2
  );
  return {
    ok: true,
    jsonLd,
    errors,
    pairCount: mainEntity.length,
    acceptedPairs,
  };
}

/**
 * Tool-logic slot: validate input, build the schema, return run values.
 * Values keys: jsonLd, errors, pairCount (match meta.ts output ids).
 */
export function runTool(values: Record<string, unknown>): RunToolResult {
  if (!values || typeof values !== "object") {
    return { ok: false, error: "Please add your question/answer pairs first." };
  }
  const raw = values["pairs"];

  let pairs: FaqPair[];
  if (Array.isArray(raw)) {
    pairs = raw as FaqPair[];
  } else if (typeof raw === "string") {
    if (raw.trim() === "") {
      return {
        ok: false,
        error: "Please add at least one question/answer pair.",
      };
    }
    pairs = parsePairsText(raw);
  } else {
    return {
      ok: false,
      error: "Please add at least one question/answer pair.",
    };
  }

  const result = buildFaqSchema(pairs);
  if (!result.ok) {
    return { ok: false, error: result.errors[0] ?? "Invalid input." };
  }
  const out: FaqSchemaRunValues = {
    jsonLd: result.jsonLd,
    errors: result.errors,
    pairCount: result.pairCount,
  };
  return { ok: true, values: out as unknown as Record<string, unknown> };
}
