import type { ToolInput, ToolOutput } from '../../../src/lib/registry/types.ts';
import type { ToolContent } from '../../../src/templates/types.ts';

const TOOL_URL = 'https://husnainblogger.com/tools/blogging-seo/faq-schema-generator/';

export const inputs: ToolInput[] = [
  {
    id: 'pairs',
    label: 'Question/answer pairs',
    type: 'textarea',
    required: true,
    placeholder:
      'What is SEO?\nSearch engine optimization.\n\nHow long does SEO take?\nTypically 3–6 months.',
  },
];

export const outputs: ToolOutput[] = [
  {
    id: 'jsonLd',
    label: 'JSON-LD markup (copy)',
    type: 'copy',
    description:
    'Valid schema.org FAQPage JSON-LD — paste it into your page.',
  keywords: ['faq schema code', 'faq schema example', 'faq schema generator tool', 'faq schema markup generator'],
  },
  {
    id: 'errors',
    label: 'Validation notes',
    type: 'list',
    description:
    'Pairs that were skipped and why (duplicates, length issues).',
  },
  {
    id: 'pairCount',
    label: 'Pairs included',
    type: 'number',
    description:
    'Number of Q&A pairs in the generated markup.',
  },
];

export const content: ToolContent = {
  title: 'FAQ Schema Generator – Free JSON-LD',
  description:
    'Generate valid schema.org FAQPage JSON-LD for free — copy the markup and paste it straight into your page. Generate yours now!',
  howTo: [
    'Paste your Q&A pairs into the "Question/answer pairs" box — each question on its own line, followed by its answer, with a blank line between pairs.',
    'Run the tool to validate every pair (up to 50 pairs per block).',
    'Check the "Validation notes" for skipped duplicates or over-length pairs.',
    'Copy the "JSON-LD markup" and paste it into your page where the same FAQ content is visible.',
    'Test the live page in Google\'s Rich Results Test to confirm the FAQPage is detected.',
  ],
  methodology:
    'This tool formats the Q&A pairs you provide into a schema.org FAQPage JSON-LD block: each pair is validated (question 1–300 chars, answer 1–5000 chars, max 50 pairs), duplicate questions are removed case-insensitively, and any HTML is kept as literal text. Nothing is generated by AI — the output contains only your own words, structured to the schema.org FAQPage specification.',
  examples: [
    {
      title: 'Two-question FAQ',
      inputs: {
        pairs: 'What is SEO?\nSearch engine optimization.\n\nHow long does SEO take?\nTypically 3–6 months.',
      },
      note: 'A basic two-pair block producing one FAQPage JSON-LD snippet.',
    },
    {
      title: 'Duplicate question skipped',
      inputs: {
        pairs: 'What is SEO?\nFirst answer.\n\nWHAT IS SEO?\nDuplicate answer.',
      },
      note: 'The duplicate is removed and reported in Validation notes.',
    },
    {
      title: 'Invalid pair reported',
      inputs: {
        pairs: 'What is SEO?\nSearch engine optimization.\n\n\nNo answer here.',
      },
      note: 'The pair with no answer is skipped; the valid pair still generates markup.',
    },
  ],
  faqs: [
    {
      question: 'What is faq schema?',
      answer: 'This is a common question about what is faq schema. Use the tool above to get your answer instantly - it is free and requires no signup.',
    },
    {
      question: 'What is the best FAQ schema generator?',
      answer:
        'The best FAQ schema generator produces valid schema.org FAQPage JSON-LD you can paste into any page, validates your questions and answers, and needs no signup. This tool does all three — enter your pairs, copy the markup, and test it in Google\'s Rich Results Test.',
    },
    {
      question: 'Is there a free FAQ schema generator?',
      answer:
        'Yes — this FAQ schema generator is completely free with no signup. You can generate JSON-LD for up to 50 Q&A pairs per block, and split longer FAQs into multiple blocks.',
    },
    {
      question: 'How to generate FAQ schema?',
      answer:
        'Paste your question/answer pairs into the tool, review the validation notes, then copy the generated JSON-LD into your page where the same FAQ content is visible. Finally, run the live page through Google\'s Rich Results Test to confirm it is detected.',
    },
    {
      question: 'How does a FAQ schema generator work?',
      answer:
        'It takes your Q&A pairs and assembles them into a schema.org FAQPage JSON-LD block with the correct Question and Answer nesting. Nothing is written by AI — the tool only formats the text you provide into valid markup.',
    },
    {
      question: 'Will FAQ schema get me rich results?',
      answer:
        'Valid FAQPage markup makes your page eligible, but Google decides whether to show the rich result — and only when the same Q&A content is visible on the page. This tool produces spec-valid JSON-LD for up to 50 pairs per block, then you confirm detection in Google\'s Rich Results Test.',
    },
    {
      question: 'Where do I put FAQ schema on my page?',
      answer:
        'Paste the generated JSON-LD inside a <script type="application/ld+json"> tag in your page — usually in a custom code or SEO plugin field. The FAQ content itself must also appear visibly on the page, not only inside the markup.',
    },
    {
      question: 'Does FAQ schema help SEO?',
      answer:
        'FAQ schema does not directly boost rankings, but it can improve how your result appears, which can lift click-through when Google shows the FAQ dropdown. Pair it with genuinely useful answers — the tool formats your own text into valid markup, but it cannot make thin content win rich results.',
    },
  ],
  assumptions: [
    'Valid markup does not guarantee rich results — Google decides whether to show an FAQ rich result, and only when the same Q&A content is visible on the page.',
    'HTML in questions or answers is kept as literal text, never parsed or executed.',
    'Up to 50 pairs per block; split longer FAQs into multiple blocks.',
  ],
  jsonLd: [],
};
