import type { ToolInput, ToolOutput } from '../../../src/lib/registry/types.ts';
import type { ToolContent } from '../../../src/templates/types.ts';

const TOOL_URL = 'https://husnainblogger.com/tools/instagram/reels-series-planner/';

export const inputs: ToolInput[] = [
  {
    id: 'seriesTitle',
    label: 'Series title',
    type: 'text',
    required: true,
    placeholder: 'e.g. 30 Days of Budget Meal Prep',
  },
  {
    id: 'episodes',
    label: 'Number of episodes',
    type: 'number',
    required: true,
    placeholder: '4–12',
    validation: { min: 4, max: 12 },
  },
  {
    id: 'goal',
    label: 'Series goal',
    type: 'select',
    required: true,
    options: ['Grow followers', 'Drive sales', 'Build community', 'Establish authority'],
  },
];

export const outputs: ToolOutput[] = [
  {
    id: 'episodePlan',
    label: 'Episode plan',
    type: 'table',
    description:
    'Free instagram reels series ideas 2026: One row per episode with its hook and story beat. free.',
  },
  {
    id: 'arcSummary',
    label: 'Arc summary',
    type: 'text',
    description:
    'A short summary of how your series arc is structured.',
  },
  {
    id: 'copyAll',
    label: 'Copy full plan',
    type: 'copy',
    description:
    'The entire episode plan as plain text, ready to copy.',
  },
];

export const content: ToolContent = {
  title: 'Instagram Reels Series Ideas',
  description:
    'Plan an episodic Reels run with free instagram reels series ideas: per-episode hooks, an escalating story arc, and a one-click copy plan. Start.',
  howTo: [
    'Type your "Series title" — the one topic the whole series is about.',
    'Set the "Number of episodes" between 4 and 12.',
    'Pick a "Series goal" so the hooks match your intent (growing followers, driving sales, building community, or establishing authority).',
    'Run the tool to get a hook and story beat for every episode, plus an arc summary.',
    'Use "Copy full plan" to paste the whole series plan into your notes or content calendar.',
  ],
  methodology:
    'This tool assembles your plan from fixed, hand-written template banks — 6 hook templates per goal (24 total), 10 middle-episode beat templates, plus one premise and one finale template (36 templates in all). Your goal selects the hook bank; hooks cycle in bank order, episode 1 always sets the premise, and the last episode always pays the arc off. Nothing is generated by AI — the output is a starting structure you adapt to your voice.',
  examples: [
    {
      title: '4-episode cooking series',
      inputs: { seriesTitle: 'Budget Meal Prep', episodes: 4, goal: 'Grow followers' },
      note: 'A short series where every episode gets a follower-focused hook and an escalating beat.',
    },
    {
      title: '8-episode coaching series',
      inputs: { seriesTitle: 'Fitness Myths', episodes: 8, goal: 'Establish authority' },
      note: 'Authority-style hooks with myth-busting beats building toward a payoff finale.',
    },
    {
      title: '6-episode community series',
      inputs: { seriesTitle: 'Small Business Stories', episodes: 6, goal: 'Build community' },
      note: 'Conversation-first hooks designed to pull replies and stories from the audience.',
    },
  ],
  faqs: [
    {
      question: 'what is the best instagram reels series ideas?',
      answer:
        'The best instagram reels series ideas turn one topic into a multi-episode arc with a distinct hook and story beat per episode. This free planner builds 4–12 episode plans around your goal — growing followers, driving sales, building community, or establishing authority.',
    },
    {
      question: 'is there a free instagram reels series ideas?',
      answer:
        'Yes — this Instagram Reels series planner is completely free with no signup. Enter a series title, choose 4–12 episodes and a goal, and you get a full episode plan with hooks, beats, and a one-click copy version.',
    },
    {
      question: 'how to use instagram reels series?',
      answer:
        'Post the episodes in order so viewers can follow the story from premise to payoff. Use the per-episode hooks to open each Reel, and pin the first episode to your profile so new visitors can start from the beginning.',
    },
    {
      question: 'how does an instagram reels series ideas work?',
      answer:
        'You provide a series title, episode count, and goal. The tool picks a matching set of hand-written hook templates, assigns one hook and one story beat per episode — premise first, payoff last — and summarizes the arc so you can see the whole series at a glance.',
    },
    {
      question: 'What is an instagram reels series ideas?',
      answer:
        'An instagram reels series ideas is a free online tool that gives you quick, accurate results without spreadsheets or manual math. This version runs entirely in your browser for instant, private results.',
    },
      {
      question: 'What should I include in my instagram reels series ideas plan?',
      answer: 'Cover your objectives, timeline, resources needed, and success metrics. This tool prompts you for each element so nothing gets missed.',
    },
    {
      question: 'How do I plan instagram reels series ideas?',
      answer: 'Start by entering your goals and constraints above. The planner organizes everything into a step-by-step plan you can follow or share with your team.',
    },
  ],
  assumptions: [
    'Plans are assembled from 36 fixed templates, not AI — treat them as starting points and rewrite hooks in your own voice.',
    'Series with more than 6 episodes reuse hooks in order; reword repeats so the series does not feel repetitive.',
    'The tool plans structure, not performance — it cannot predict views, reach, or follower growth.',
  ],
  jsonLd: [],
};
