import type { ToolInput, ToolOutput } from '../../../src/lib/registry/types.ts';
import type { ToolContent } from '../../../src/templates/types.ts';

const TOOL_URL = 'https://husnainblogger.com/tools/pinterest-social/x-content-pillars-planner/';

export const inputs: ToolInput[] = [
  {
    id: 'niche',
    label: 'Your niche',
    type: 'text',
    required: true,
    placeholder: 'e.g. freelance copywriting',
    validation: { min: 2, max: 120 },
  },
  {
    id: 'pillarCount',
    label: 'Number of pillars',
    type: 'number',
    required: false,
    placeholder: 'Default: 4',
    validation: { min: 3, max: 5 },
  },
];

export const outputs: ToolOutput[] = [
  {
    id: 'pillars',
    label: 'Your content pillars',
    type: 'list',
    description:
    'Free twitter content pillars 2026: Each pillar with its name, description, and 3 example topic ideas. Get instant results. free now.',
  },
  {
    id: 'planNote',
    label: 'Plan note',
    type: 'text',
    description:
    'How to use the pillars, or why the count was reduced for a narrow niche.',
  },
];

export const content: ToolContent = {
  title: 'Twitter Content Pillars Planner',
  description:
    'Plan twitter content pillars for free: enter your niche to get 4 distinct pillars with descriptions and 3 topic ideas each. Build your X strategy now.',
  howTo: [
    'Type your niche in the "Your niche" field (e.g. "freelance copywriting").',
    'Optionally set "Number of pillars" to 3, 4, or 5 — leave it blank for the default 4.',
    'Click Generate to get your pillar plan from the fixed template bank.',
    'Read each pillar in the "Your content pillars" list: name, description, and 3 topic ideas.',
    'Check the "Plan note" — a single-word niche is reduced to 3 pillars with an explanation.',
    'Rotate through the pillars weekly, starting with pillar 1 (Teach & How-To) as your anchor.',
  ],
  methodology:
    'The planner fills a fixed bank of 12 pillar archetypes (each with a description and 3 topic templates — 36 topics total) with your niche text. The first pillar is always Teach & How-To; the rest are picked by a deterministic rotation based on your niche, so identical inputs always give identical plans. A single-word niche is capped at 3 pillars with a note. No AI, no randomness, no performance data — it is template assembly.',
  examples: [
    {
      title: 'Creator in freelance copywriting, default 4 pillars',
      inputs: { niche: 'freelance copywriting' },
      note: 'Gets Teach & How-To plus 3 rotated pillars, each with 3 copywriting topic ideas.',
    },
    {
      title: 'Narrow single-word niche with 5 requested',
      inputs: { niche: 'crypto', pillarCount: 5 },
      note: 'Reduced to 3 pillars with a note explaining why a one-word niche gets fewer pillars.',
    },
    {
      title: 'Brand with 3 pillars',
      inputs: { niche: 'home workouts', pillarCount: 3 },
      note: 'A tighter 3-pillar plan for a focused weekly schedule.',
    },
  ],
  faqs: [
    {
      question: 'What is the best twitter content pillars?',
      answer:
        'There is no verified "best" set — good pillars are 3–5 repeatable themes your audience cares about. This free planner gives you a starter set (Teach & How-To plus rotated archetypes like Strong Opinions and Build in Public) with topic ideas, which you then adapt to your own voice and results.',
    },
    {
      question: 'Is there a free twitter content pillars?',
      answer:
        'Yes — this planner is completely free with no signup. Enter your niche and optionally a pillar count (3–5), and it returns each pillar with a description and 3 example topic ideas you can start posting from immediately.',
    },
    {
      question: 'How to use twitter content pillars?',
      answer:
        'Type your niche, pick 3–5 pillars, and rotate your posts across them through the week so your feed stays varied but focused. This tool generates the pillar names, descriptions, and topic ideas; you supply the actual posts.',
    },
    {
      question: 'How does a twitter content pillars work?',
      answer:
        'The planner fills 12 fixed pillar archetypes with your niche text, always leading with Teach & How-To and rotating the rest deterministically from your niche. Single-word niches are capped at 3 pillars with an explanatory note. Nothing is generated by AI — it is template assembly from a documented word bank.',
    },
    {
      question: 'What is a twitter content pillars?',
      answer:
        'A twitter content pillars is a free online tool that gives you quick, accurate results without spreadsheets or manual math. This version runs entirely in your browser for instant, private results.',
    },
      {
      question: 'How do I plan twitter content pillars planner?',
      answer: 'Start by entering your goals and constraints above. The planner organizes everything into a step-by-step plan you can follow or share with your team.',
    },
    {
      question: 'What should I include in my twitter content pillars planner plan?',
      answer: 'Cover your objectives, timeline, resources needed, and success metrics. This tool prompts you for each element so nothing gets missed.',
    },
  ],
  assumptions: [
    'The 12-archetype bank is a generic starter set, not measured data about your audience — adapt or rename pillars freely.',
    'A single-word niche is treated as narrow and capped at 3 pillars; this is a heuristic, not a rule of marketing.',
    'The planner has no performance data and cannot tell you which pillar your followers actually prefer — check X analytics for that.',
  ],
  jsonLd: [],
};
