/**
 * Seasonal Keyword Planner — pure logic (zero imports, zero network, zero DOM).
 *
 * Turns one seed keyword into a 12-month seasonal content plan using a
 * built-in EDITORIAL event bank. This is a planning template, not live
 * data: events and angles are fixed, human-written templates. Nothing is
 * generated by an AI model and no live search-trend data is shown — verify
 * real demand in Google Trends before publishing.
 *
 * Event bank: 36 events x 3 angle templates each (bank size documented in
 * EVENT_BANK / ANGLES_PER_EVENT). Niche tags are plain topic words; an
 * event counts as a "niche match" when any tag appears in the seed keyword
 * (or vice versa). Generic events (no tags) are always included.
 *
 * Determinism: same inputs -> identical outputs. "year" defaults to the
 * current UTC calendar year. Publish-by dates are computed as
 * (first day of the event month) minus leadWeeks, using UTC date math.
 */

export const EVENT_BANK_VERSION = "v1.0.0 (effective 2026-10-01)";
export const ANGLES_PER_EVENT = 3;

export interface SeasonalEvent {
  /** e.g. "Black Friday". */
  name: string;
  /** 1-12. */
  month: number;
  /** Topic words that mark this event as niche-relevant, e.g. ["fitness"]. Empty = generic. */
  nicheTags: string[];
  /** How many weeks before the event month content should be published. */
  leadWeeks: number;
  /** Exactly ANGLES_PER_EVENT templates; use {seed} for the keyword. */
  angles: string[];
}

/**
 * Editorial seasonal event bank: 36 events x 3 angle templates.
 * Northern-hemisphere bias is documented (see assumptions in meta.ts):
 * verify timing for southern-hemisphere audiences.
 */
export const EVENT_BANK: SeasonalEvent[] = [
  {
    name: "New Year's resolutions",
    month: 1,
    nicheTags: ["fitness", "health", "goals", "productivity", "finance"],
    leadWeeks: 4,
    angles: [
      "{seed} new year resolutions guide",
      "new year {seed} checklist for beginners",
      "best {seed} goals to set this year",
    ],
  },
  {
    name: "Winter sales",
    month: 1,
    nicheTags: [],
    leadWeeks: 3,
    angles: [
      "post-holiday {seed} deals worth buying",
      "january {seed} sale roundup",
      "is {seed} cheaper after the holidays?",
    ],
  },
  {
    name: "Valentine's Day",
    month: 2,
    nicheTags: ["gifts", "relationships", "ecommerce", "dating"],
    leadWeeks: 5,
    angles: [
      "{seed} valentine's day gift guide",
      "romantic {seed} ideas on a budget",
      "last-minute {seed} valentine's gifts",
    ],
  },
  {
    name: "Super Bowl",
    month: 2,
    nicheTags: ["sports", "football", "food", "recipes"],
    leadWeeks: 3,
    angles: [
      "super bowl {seed} party guide",
      "{seed} recipes for game day",
      "super bowl {seed} hosting checklist",
    ],
  },
  {
    name: "International Women's Day",
    month: 3,
    nicheTags: ["business", "careers", "finance", "women"],
    leadWeeks: 3,
    angles: [
      "{seed} tips for women in business",
      "women's day {seed} gift ideas",
      "how {seed} empowers women entrepreneurs",
    ],
  },
  {
    name: "St. Patrick's Day",
    month: 3,
    nicheTags: ["food", "recipes", "travel", "beer"],
    leadWeeks: 3,
    angles: [
      "st. patrick's day {seed} ideas",
      "{seed} recipes for st. patrick's day",
      "where to celebrate st. patrick's day: {seed} guide",
    ],
  },
  {
    name: "Spring break travel",
    month: 3,
    nicheTags: ["travel", "students", "vacation"],
    leadWeeks: 5,
    angles: [
      "spring break {seed} destinations guide",
      "budget {seed} tips for spring break",
      "spring break {seed} packing checklist",
    ],
  },
  {
    name: "Spring gardening season",
    month: 3,
    nicheTags: ["gardening", "plants", "home"],
    leadWeeks: 4,
    angles: [
      "spring {seed} planting guide",
      "when to start {seed} in spring",
      "beginner spring {seed} checklist",
    ],
  },
  {
    name: "Tax season",
    month: 4,
    nicheTags: ["finance", "tax", "business", "money"],
    leadWeeks: 4,
    angles: [
      "{seed} tax deductions explained",
      "tax season {seed} checklist",
      "how {seed} affects your taxes",
    ],
  },
  {
    name: "Easter",
    month: 4,
    nicheTags: ["recipes", "crafts", "family", "kids"],
    leadWeeks: 4,
    angles: [
      "easter {seed} ideas for families",
      "{seed} easter recipes and crafts",
      "easter weekend {seed} guide",
    ],
  },
  {
    name: "Earth Day",
    month: 4,
    nicheTags: ["sustainability", "eco", "environment", "gardening"],
    leadWeeks: 3,
    angles: [
      "eco-friendly {seed} guide for earth day",
      "sustainable {seed} swaps to try",
      "earth day {seed} activities",
    ],
  },
  {
    name: "Spring marathon season",
    month: 4,
    nicheTags: ["fitness", "running", "health"],
    leadWeeks: 4,
    angles: [
      "spring marathon {seed} training plan",
      "{seed} tips for first-time runners",
      "best {seed} gear for race season",
    ],
  },
  {
    name: "Spring cleaning season",
    month: 4,
    nicheTags: ["home", "cleaning", "organizing"],
    leadWeeks: 3,
    angles: [
      "spring cleaning {seed} checklist",
      "best {seed} tools for deep cleaning",
      "room-by-room {seed} spring cleaning guide",
    ],
  },
  {
    name: "Mother's Day",
    month: 5,
    nicheTags: ["gifts", "family", "ecommerce", "mom"],
    leadWeeks: 5,
    angles: [
      "mother's day {seed} gift guide",
      "thoughtful {seed} gifts for mom",
      "mother's day {seed} ideas under $50",
    ],
  },
  {
    name: "Wedding season",
    month: 5,
    nicheTags: ["weddings", "events", "photography", "fashion"],
    leadWeeks: 6,
    angles: [
      "{seed} guide for wedding season",
      "wedding {seed} planning checklist",
      "budget-friendly wedding {seed} ideas",
    ],
  },
  {
    name: "Summer grilling season",
    month: 5,
    nicheTags: ["food", "recipes", "outdoor", "bbq"],
    leadWeeks: 3,
    angles: [
      "summer {seed} grilling guide",
      "best {seed} recipes for bbq season",
      "{seed} cookout hosting checklist",
    ],
  },
  {
    name: "Memorial Day",
    month: 5,
    nicheTags: ["travel", "sales", "ecommerce", "outdoor"],
    leadWeeks: 3,
    angles: [
      "memorial day {seed} sales worth shopping",
      "memorial day weekend {seed} travel guide",
      "best memorial day {seed} deals",
    ],
  },
  {
    name: "Graduation season",
    month: 6,
    nicheTags: ["education", "careers", "gifts", "students"],
    leadWeeks: 4,
    angles: [
      "graduation {seed} gift guide",
      "{seed} tips for new graduates",
      "best {seed} ideas for grad parties",
    ],
  },
  {
    name: "Father's Day",
    month: 6,
    nicheTags: ["gifts", "family", "ecommerce", "dad"],
    leadWeeks: 5,
    angles: [
      "father's day {seed} gift guide",
      "{seed} gifts dad will actually use",
      "last-minute father's day {seed} ideas",
    ],
  },
  {
    name: "Summer travel season",
    month: 6,
    nicheTags: ["travel", "vacation", "family", "outdoor"],
    leadWeeks: 6,
    angles: [
      "summer {seed} travel guide",
      "best summer {seed} destinations",
      "summer {seed} packing checklist",
    ],
  },
  {
    name: "Independence Day",
    month: 7,
    nicheTags: ["food", "travel", "outdoor", "sales"],
    leadWeeks: 3,
    angles: [
      "4th of july {seed} party guide",
      "independence day {seed} sales",
      "best {seed} ideas for the 4th of july",
    ],
  },
  {
    name: "Mid-year sale season",
    month: 7,
    nicheTags: ["ecommerce", "deals", "shopping"],
    leadWeeks: 3,
    angles: [
      "mid-year {seed} sales roundup",
      "is {seed} cheaper in july?",
      "best mid-year {seed} deals to buy now",
    ],
  },
  {
    name: "Back to school",
    month: 8,
    nicheTags: ["education", "parenting", "shopping", "kids", "students"],
    leadWeeks: 5,
    angles: [
      "back to school {seed} checklist",
      "best {seed} supplies for students",
      "back to school {seed} shopping guide",
    ],
  },
  {
    name: "Labor Day",
    month: 9,
    nicheTags: ["sales", "ecommerce", "travel"],
    leadWeeks: 3,
    angles: [
      "labor day {seed} sales guide",
      "labor day weekend {seed} getaway ideas",
      "best labor day {seed} deals",
    ],
  },
  {
    name: "Fall fashion season",
    month: 9,
    nicheTags: ["fashion", "beauty", "style", "clothing"],
    leadWeeks: 4,
    angles: [
      "fall {seed} trends to try",
      "best fall {seed} essentials",
      "fall {seed} style guide",
    ],
  },
  {
    name: "Fall home prep",
    month: 9,
    nicheTags: ["home", "diy", "gardening", "maintenance"],
    leadWeeks: 3,
    angles: [
      "fall {seed} home maintenance checklist",
      "prepare your {seed} for autumn",
      "best fall {seed} upgrades for your home",
    ],
  },
  {
    name: "Halloween",
    month: 10,
    nicheTags: ["crafts", "recipes", "parenting", "kids", "costumes"],
    leadWeeks: 5,
    angles: [
      "halloween {seed} ideas",
      "diy halloween {seed} guide",
      "halloween {seed} party checklist",
    ],
  },
  {
    name: "Autumn home decor",
    month: 10,
    nicheTags: ["home", "decor", "interior"],
    leadWeeks: 3,
    angles: [
      "fall {seed} decor ideas",
      "cozy autumn {seed} styling guide",
      "budget fall {seed} decor swaps",
    ],
  },
  {
    name: "Thanksgiving",
    month: 11,
    nicheTags: ["recipes", "family", "travel", "food"],
    leadWeeks: 5,
    angles: [
      "thanksgiving {seed} guide",
      "best thanksgiving {seed} recipes",
      "thanksgiving {seed} hosting checklist",
    ],
  },
  {
    name: "Black Friday",
    month: 11,
    nicheTags: ["ecommerce", "deals", "shopping", "tech"],
    leadWeeks: 5,
    angles: [
      "black friday {seed} deals preview",
      "best black friday {seed} deals to watch",
      "black friday {seed} buying guide",
    ],
  },
  {
    name: "Gift guide season",
    month: 11,
    nicheTags: ["gifts", "ecommerce", "shopping"],
    leadWeeks: 6,
    angles: [
      "ultimate {seed} gift guide",
      "{seed} gifts for everyone on your list",
      "best {seed} gifts under $25, $50 and $100",
    ],
  },
  {
    name: "Cyber Monday",
    month: 11,
    nicheTags: ["ecommerce", "deals", "tech", "shopping"],
    leadWeeks: 5,
    angles: [
      "cyber monday {seed} deals",
      "best cyber monday {seed} discounts",
      "cyber monday vs black friday: {seed} deals compared",
    ],
  },
  {
    name: "Christmas",
    month: 12,
    nicheTags: ["gifts", "recipes", "family", "ecommerce", "decor"],
    leadWeeks: 6,
    angles: [
      "christmas {seed} gift guide",
      "{seed} christmas recipes and traditions",
      "christmas {seed} planning checklist",
    ],
  },
  {
    name: "Holiday baking season",
    month: 12,
    nicheTags: ["recipes", "baking", "food"],
    leadWeeks: 4,
    angles: [
      "holiday {seed} baking guide",
      "best {seed} cookie and dessert recipes",
      "{seed} treats for holiday gifting",
    ],
  },
  {
    name: "Winter skincare season",
    month: 12,
    nicheTags: ["beauty", "skincare", "health"],
    leadWeeks: 3,
    angles: [
      "winter {seed} skincare routine",
      "best {seed} products for cold weather",
      "{seed} tips for dry winter skin",
    ],
  },
  {
    name: "New Year's Eve",
    month: 12,
    nicheTags: ["parties", "food", "travel", "events"],
    leadWeeks: 4,
    angles: [
      "new year's eve {seed} party guide",
      "{seed} ideas for nye at home",
      "new year's eve {seed} hosting checklist",
    ],
  },
];

const MONTH_NAMES = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

/** True when any niche tag of the event relates to the seed keyword (or vice versa). */
export function nicheMatchesSeed(seed: string, event: SeasonalEvent): boolean {
  const words = seed
    .toLowerCase()
    .split(/[\s\-_.,;:!?()/"'&]+/)
    .filter(Boolean);
  if (event.nicheTags.length === 0) return false;
  return event.nicheTags.some((tag) =>
    words.some((w) => w.includes(tag) || tag.includes(w)),
  );
}

/**
 * Publish-by date: first day of the event month minus leadWeeks,
 * computed with UTC date math. Returns YYYY-MM-DD.
 */
export function publishByDate(year: number, month: number, leadWeeks: number): string {
  const ms = Date.UTC(year, month - 1, 1) - leadWeeks * 7 * 86400000;
  const d = new Date(ms);
  const pad = (n: number): string => String(n).padStart(2, "0");
  return `${d.getUTCFullYear()}-${pad(d.getUTCMonth() + 1)}-${pad(d.getUTCDate())}`;
}

/**
 * Run the planner. Values in:
 *   seedKeyword: string (required, 2-100 chars)
 *   year: number        (optional; defaults to current UTC year, must be current year +/- 1)
 *
 * Values out:
 *   seasonalPlan: { columns: string[]; rows: string[][] }
 *   eventBankVersion: string
 */
export function runTool(values: Record<string, unknown>): {
  ok: boolean;
  values?: Record<string, unknown>;
  error?: string;
} {
  const v = values ?? {};

  const seedRaw = v["seedKeyword"];
  const seed = typeof seedRaw === "string" ? seedRaw.trim() : "";
  if (!seed) {
    return { ok: false, error: "Seed keyword is required." };
  }
  if (seed.length < 2 || seed.length > 100) {
    return { ok: false, error: "Seed keyword must be 2-100 characters." };
  }

  const currentYear = new Date().getUTCFullYear();
  let year = currentYear;
  const yearRaw = v["year"];
  if (yearRaw !== undefined && yearRaw !== null && yearRaw !== "") {
    const parsed = typeof yearRaw === "number" ? yearRaw : Number(String(yearRaw).trim());
    if (!Number.isInteger(parsed)) {
      return { ok: false, error: "Year must be a whole number." };
    }
    if (parsed < currentYear - 1 || parsed > currentYear + 1) {
      return {
        ok: false,
        error: `Year must be ${currentYear - 1}, ${currentYear}, or ${currentYear + 1}.`,
      };
    }
    year = parsed;
  }

  const sorted = [...EVENT_BANK].sort((a, b) =>
    a.month === b.month ? (a.name < b.name ? -1 : a.name > b.name ? 1 : 0) : a.month - b.month,
  );

  const columns = ["Month", "Event", "Content angles", "Publish by", "Niche match"];
  const rows: string[][] = sorted.map((event) => {
    const matched = nicheMatchesSeed(seed, event);
    const angles = event.angles.map((t) => t.replace(/\{seed\}/g, seed)).join(" / ");
    return [
      MONTH_NAMES[event.month - 1],
      event.name,
      angles,
      publishByDate(year, event.month, event.leadWeeks),
      matched ? "Yes" : "Generic",
    ];
  });

  return {
    ok: true,
    values: {
      seasonalPlan: { columns, rows },
      eventBankVersion: EVENT_BANK_VERSION,
    },
  };
}
