import type { ToolInput, ToolOutput } from '../../../src/lib/registry/types.ts';
import type { ToolContent } from '../../../src/templates/types.ts';

export const inputs: ToolInput[] = [
  {
    id: 'mood',
    label: 'Mood',
    type: 'select',
    required: true,
    options: ['bold', 'elegant', 'playful', 'techy'],
  },
  {
    id: 'useCase',
    label: 'Use case',
    type: 'select',
    required: true,
    options: ['captions', 'titles', 'lower-thirds'],
  },
];

export const outputs: ToolOutput[] = [
  { id: 'pairings', label: 'Font pairings', type: 'list' },
  { id: 'contrastNote', label: 'Contrast note', type: 'text' },
];

const DESCRIPTION =
  'Pair fonts that look professionally designed: pick a mood and use case for heading and body font combos with direct Google Fonts links included.';

export const content: ToolContent = {
  title: 'Font Pairing Generator',
  description: DESCRIPTION,
  howTo: [
    'Choose a mood that fits your video: bold, elegant, playful, or techy.',
    'Choose a use case: captions, titles, or lower-thirds.',
    'Read the two curated pairings — each shows a heading font plus a body font and why they work together.',
    'Follow the Google Fonts links to preview and download the fonts (links are informational).',
    'Use the fallback stack shown with each font so your design degrades gracefully on devices missing the font.',
  ],
  methodology:
    'The tool returns fixed pairs from a curated bank of 24 combinations (4 moods x 3 use cases x 2 pairs) — nothing is generated by AI. Every pair follows one rule: a single display font for headings plus a readable body font, never two display fonts together. Each font ships with a system fallback stack because font availability varies by device, and the Google Fonts links are plain informational search links.',
  examples: [
    {
      title: 'Bold YouTube titles',
      inputs: { mood: 'bold', useCase: 'titles' },
      note: 'Heavy headline fonts like Bebas Neue paired with quiet, readable partners.',
    },
    {
      title: 'Elegant lower thirds',
      inputs: { mood: 'elegant', useCase: 'lower-thirds' },
      note: 'Light, professional name treatments for interviews and documentaries.',
    },
  ],
  faqs: [
    {
      question: 'What is the best font pairing generator?',
      answer:
        'The best pairing generator gives you combinations that follow real typography rules — one display font plus one readable partner, never two display fonts fighting. This free tool curates 24 such pairs across four moods and three video use cases.',
    },
    {
      question: 'Is there a free font pairing generator?',
      answer:
        'Yes — this font pairing generator is completely free with no signup. Pick a mood and a use case and you get two curated heading/body combinations with Google Fonts links instantly.',
    },
    {
      question: 'How to generate font pairing?',
      answer:
        'Choose the mood your video needs and where the text will appear (captions, titles, or lower-thirds). The tool returns two curated pairs with an explanation of why each works, plus fallback stacks for devices missing the fonts.',
    },
    {
      question: 'How does a font pairing generator work?',
      answer:
        'This one looks up your mood and use case in a fixed curated bank of 24 hand-picked pairs and adds per-use-case contrast guidance. Every font named is a real, widely available font — no names are invented — and there is no AI or live font preview involved.',
    },
    {
      question: 'How does the font pairing generator work?',
      answer:
        'Enter your details using the inputs above and the font pairing generator calculates everything instantly in your browser. No data leaves your device, and you get results the moment you change any value.',
    },
    {
      question: 'Is the font pairing generator free to use?',
      answer:
        'Yes - this font pairing generator is completely free with no signup, no account, and no usage limits. It runs 100% in your browser.',
    },
    {
      question: 'What is a font pairing generator?',
      answer:
        'A font pairing generator is a free online tool that gives you quick, accurate results without spreadsheets or manual math. This version runs entirely in your browser for instant, private results.',
    },
  ],
  assumptions: [
    'Pairings come from a fixed curated bank of 24 combinations — the tool does not invent or preview fonts.',
    'Font availability varies by device; always use the provided fallback stack and test on your target devices.',
    'Google Fonts links are informational search links, not downloads or license grants — check each font\'s license before commercial use.',
  ],
  jsonLd: [
    {
      '@type': 'SoftwareApplication',
      name: 'Font Pairing Generator 2026 – Free Tool | HusnainBlogger',
      url: 'https://husnainblogger.com/tools/video-editing/font-pairing-generator/',
      applicationCategory: 'Utilities',
      operatingSystem: 'Web',
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      description: DESCRIPTION,
    },
    {
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://husnainblogger.com/' },
        { '@type': 'ListItem', position: 2, name: 'Tools', item: 'https://husnainblogger.com/tools/' },
        {
          '@type': 'ListItem',
          position: 3,
          name: 'Video Editing Tools',
          item: 'https://husnainblogger.com/tools/video-editing/',
        },
        {
          '@type': 'ListItem',
          position: 4,
          name: 'Font Pairing Generator',
          item: 'https://husnainblogger.com/tools/video-editing/font-pairing-generator/',
        },
      ],
    },
  ],
};
