import type { ToolInput, ToolOutput } from '../../../src/lib/registry/types.ts';
import type { ToolContent } from '../../../src/templates/types.ts';

const TOOL_URL = 'https://husnainblogger.com/tools/pinterest-social/facebook-hashtag-generator/';

export const inputs: ToolInput[] = [
  {
    id: 'topic',
    label: 'Post topic',
    type: 'text',
    required: true,
    placeholder: 'e.g. handmade candles, home workouts, budget travel',
  },
  {
    id: 'count',
    label: 'Number of hashtags (1-5)',
    type: 'number',
    required: false,
    placeholder: '3',
    validation: { min: 1, max: 5 },
  },
];

export const outputs: ToolOutput[] = [
  {
    id: 'hashtags',
    label: 'Hashtags',
    type: 'list',
    description:
    'Free facebook hashtags 2026: One ready-to-paste hashtag set of 1-5 curated tags for your topic. Get instant results. free now.',
  },
  {
    id: 'usageNote',
    label: 'Honest usage note',
    type: 'text',
    description:
    'Why Facebook hashtags carry low weight and how many to use per post.',
  },
];

export const content: ToolContent = {
  title: 'Facebook Hashtags',
  description:
    'Stop guessing hashtags on Facebook: enter your post topic for 1-5 curated tags plus honest guidance on whether hashtags are even worth using.',
  howTo: [
    'Type your Post topic into the field (e.g. handmade candles, home workouts).',
    'Set "Number of hashtags" to any number from 1 to 5 (default is 3).',
    'Click run to get a ready-to-paste set: your topic as the first tag, then category tags.',
    'Copy the set into the end of your Facebook post or first comment.',
    'Read the usage note — on Facebook, strong post text and audience matter more than tags.',
  ],
  methodology:
    'This tool assembles hashtags from a fixed bundled bank of 68 hand-curated tags (6 category pools x 10 tags, plus 8 Facebook-flavored tags). Your topic is normalized into the first tag, the topic is matched to a category pool by keyword, and the remaining slots fill deterministically from the pool in fixed order. Nothing is generated by AI and there is no live tag volume or trend data — the usage note states the honest limitation.',
  examples: [
    {
      title: 'Hashtags for a candle business',
      inputs: { topic: 'handmade candles', count: 3 },
      note: 'Returns 3 tags: your topic tag plus small-business tags.',
    },
    {
      title: 'One tag for a quick post',
      inputs: { topic: 'budget travel', count: 1 },
      note: 'Returns a single normalized topic tag (#budgettravel).',
    },
    {
      title: 'Five tags for a fitness post',
      inputs: { topic: 'home workouts', count: 5 },
      note: 'Returns 5 tags: topic tag plus fitness pool tags.',
    },
  ],
  faqs: [
    {
      question: 'What is the best facebook hashtags?',
      answer:
        'There is no verified "best" set — Facebook itself gives hashtags little algorithmic weight, so the best approach is 1-3 relevant tags on a strong post. This free generator builds you a curated set of 1-5 tags from a fixed 68-tag bank and tells you honestly that keywords and audience matter more.',
    },
    {
      question: 'Is there a free facebook hashtags?',
      answer:
        'Yes — this Facebook hashtag generator is completely free with no signup. Enter your post topic and choose 1-5 hashtags; you get a ready-to-paste set plus an honest usage note, as many times as you like.',
    },
    {
      question: 'How to use facebook hashtags?',
      answer:
        'Add 1-3 hashtags at the end of your post or in the first comment, keep them relevant to the topic, and do not rely on them for reach — strong post text, keywords, and engaging your audience matter far more on Facebook.',
    },
    {
      question: 'How does a facebook hashtags generator work?',
      answer:
        'This one normalizes your topic into the first tag, matches the topic to a category pool (business, fitness, food, travel, beauty, or general) by keyword, and fills the rest deterministically from the fixed 68-tag bank. It has no live data on which tags are trending.',
    },
    {
      question: 'How does the facebook hashtags work?',
      answer:
        'Enter your details using the inputs above and the facebook hashtags calculates everything instantly in your browser. No data leaves your device, and you get results the moment you change any value.',
    },
    {
      question: 'Is the facebook hashtags free to use?',
      answer:
        'Yes - this facebook hashtags is completely free with no signup, no account, and no usage limits. It runs 100% in your browser.',
    },
    {
      question: 'What is a facebook hashtags?',
      answer:
        'A facebook hashtags is a free online tool that gives you quick, accurate results without spreadsheets or manual math. This version runs entirely in your browser for instant, private results.',
    },
  ],
  assumptions: [
    'Hashtags come from a fixed bundled bank of 68 curated tags — no live data on tag volume, reach, or what is trending.',
    'On Facebook, hashtags carry low weight: use 1-3 per post; they are a small helper, never the strategy.',
    'Topics are normalized (lowercase, letters and numbers only, max 30 chars); symbols-only topics are rejected.',
  ],
  jsonLd: [],
};
