import type { ToolInput, ToolOutput } from '../../../src/lib/registry/types.ts';
import type { ToolContent } from '../../../src/templates/types.ts';
import type { BuilderField } from '../../../src/templates/types.ts';

const TOOL_URL = 'https://husnainblogger.com/tools/youtube/livestream-title-pack-builder/';

const DESCRIPTION =
  'Get youtube live stream title ideas fast — add each stream topic and type for announcement, live and replay titles plus a description snippet. Try it free.';

export const inputs: ToolInput[] = [];

export const itemFields: BuilderField[] = [
  {
    id: 'topic',
    label: 'Stream topic',
    type: 'text',
    required: true,
    placeholder: 'e.g. sourdough starter mistakes',
  },
  {
    id: 'streamType',
    label: 'Stream type',
    type: 'text',
    required: true,
    placeholder: 'Q&A, gaming, talk, or tutorial',
  },
];

export const outputs: ToolOutput[] = [
  { id: 'titles', label: 'Title pack (all phases)', type: 'list' },
  { id: 'descriptions', label: 'Description snippets', type: 'list' },
  { id: 'count', label: 'Streams packed', type: 'number' },
];

export const content: ToolContent = {
  title: 'Youtube Live Stream Title Ideas',
  description: DESCRIPTION,
  howTo: [
    'Add one item per stream you are planning.',
    'Enter the stream topic (e.g. "sourdough starter mistakes").',
    'Enter the stream type: Q&A, gaming, talk, or tutorial.',
    'Run the builder: each stream gets 6 titles — 2 announcement, 2 live, 2 replay — plus a description snippet.',
    'Pick one variant per phase, keep every title under 100 characters, and paste the snippet into your stream description.',
  ],
  methodology:
    'Template packs, not AI. Each item\u2019s topic is filled into fixed title templates across the three stream phases (announcement, live, replay — two variants each) and one fixed description snippet with a type-specific "what to expect" line and hashtags. Stream types are matched case-insensitively (Q&A, gaming, talk, tutorial, plus common aliases). Every generated title is checked against YouTube\u2019s 100-character title limit — an over-long topic fails with a per-item error asking you to shorten it. Nothing is generated by a language model; you choose the variant that fits your stream.',
  faqs: [
    {
      question: 'What is the best youtube live stream title ideas?',
      answer:
        'The best titles change with the phase: announcement titles build anticipation ("Going LIVE soon"), live titles create urgency ("LIVE NOW — join the chat"), and replay titles serve search ("full replay"). This free builder gives you two variants per phase for every stream, so you cover all three.',
    },
    {
      question: 'Is there a free youtube live stream title ideas?',
      answer:
        'Yes — this builder is completely free with no signup. Add your stream topics, set the type (Q&A, gaming, talk, or tutorial), and get 6 titles plus a description snippet per stream.',
    },
    {
      question: 'How to use youtube live stream title?',
      answer:
        'Use the announcement variant when you schedule the stream, switch to a live variant the moment you go live, and rename to the replay variant after — replays earn search traffic for months. Keep titles under 100 characters and put the topic first so it reads on mobile.',
    },
    {
      question: 'How does a youtube live stream title ideas work?',
      answer:
        'You add one item per stream with a topic and type. The tool fills your topic into fixed templates for the announcement, live, and replay phases (two variants each) and appends a description snippet with hashtags. Titles are validated against the 100-character limit. These are hand-written templates, not AI copywriting.',
    },
    {
      question: 'How does the youtube live stream title ideas work?',
      answer:
        'Enter your details using the inputs above and the youtube live stream title ideas calculates everything instantly in your browser. No data leaves your device, and you get results the moment you change any value.',
    },
    {
      question: 'Is the youtube live stream title ideas free to use?',
      answer:
        'Yes - this youtube live stream title ideas is completely free with no signup, no account, and no usage limits. It runs 100% in your browser.',
    },
    {
      question: 'What is a youtube live stream title ideas?',
      answer:
        'A youtube live stream title ideas is a free online tool that gives you quick, accurate results without spreadsheets or manual math. This version runs entirely in your browser for instant, private results.',
    },
  ],
  assumptions: [
    'Titles come from fixed templates with your topic filled in — rewrite any variant that does not sound like your channel.',
    'Every title is validated to stay within YouTube\u2019s 100-character title limit; very long topics are rejected with a per-item error.',
    'Only four stream types are supported (Q&A, gaming, talk, tutorial); anything else fails validation with the allowed list.',
    'The description snippet is a starting template — add your links, timestamps, and rules before publishing.',
  ],
  jsonLd: [
  ],
};
