/**
 * Content Angle Generator — pure logic (zero imports, zero network, zero DOM).
 *
 * Turns a topic (and optional audience) into 12 ready-to-write content
 * angles using fixed editorial templates. Template/word-bank based —
 * nothing is generated by an AI model. The angles are starting frames
 * (listicle, how-to, comparison, case study, opinion, ...); the actual
 * writing, research, and facts remain the user's job.
 *
 * Word bank: ANGLE_BANK — 12 angle entries, each with a type, a title
 * template ({topic}, {audience}, {year} placeholders), and a "why it
 * works" note. Bank size is fixed and documented.
 *
 * Audience defaults to "beginners" when omitted. {year} resolves to the
 * current UTC calendar year.
 *
 * Determinism: same inputs -> identical outputs.
 */

export const DEFAULT_AUDIENCE = "beginners";
export const MAX_TOPIC_CHARS = 120;
export const MAX_AUDIENCE_CHARS = 80;

export interface ContentAngle {
  /** e.g. "Listicle". */
  type: string;
  /** Title template with {topic}, {audience}, {year} placeholders. */
  template: string;
  /** One-line note on why this angle tends to work. */
  why: string;
}

/** Fixed editorial angle bank. Bank size: 12. */
export const ANGLE_BANK: ContentAngle[] = [
  {
    type: "Listicle",
    template: "7 {topic} mistakes {audience} keep making",
    why: "Numbered lists promise a quick, scannable read and tend to earn clicks.",
  },
  {
    type: "How-to guide",
    template: "How to {topic}: a step-by-step guide for {audience}",
    why: "How-to intent matches high-volume searches and builds trust.",
  },
  {
    type: "Beginner primer",
    template: "{topic} for beginners: everything {audience} need to know",
    why: "Beginner content captures the widest audience and ranks for broad terms.",
  },
  {
    type: "Comparison",
    template: "{topic} vs. the alternatives: an honest comparison for {audience}",
    why: "Comparison posts catch readers near a buying decision.",
  },
  {
    type: "Case study",
    template: "How one {audience} used {topic} to get real results (case study)",
    why: "Real examples add credibility that generic advice posts lack.",
  },
  {
    type: "Contrarian take",
    template: "Why most {topic} advice is wrong — a contrarian take for {audience}",
    why: "Counter-intuitive angles stand out in crowded feeds and earn shares.",
  },
  {
    type: "Checklist",
    template: "The {topic} checklist every {audience} should follow",
    why: "Checklists are saveable and shareable, which boosts engagement.",
  },
  {
    type: "Data roundup",
    template: "{topic} statistics {audience} should know in {year}",
    why: "Fresh stats attract links from writers who need citations.",
  },
  {
    type: "FAQ",
    template: "{topic} FAQs: real {audience} questions, answered",
    why: "FAQs target long-tail question searches and featured snippets.",
  },
  {
    type: "Tools roundup",
    template: "The best {topic} tools and resources for {audience}",
    why: "Tool roundups monetize well through affiliates and stay evergreen.",
  },
  {
    type: "Myth-busting",
    template: "10 {topic} myths {audience} should stop believing",
    why: "Myth-busting hooks curiosity and corrects costly misconceptions.",
  },
  {
    type: "Trends",
    template: "The future of {topic}: 5 trends {audience} should watch",
    why: "Trend pieces position you as forward-looking and get cited early.",
  },
];

/**
 * Run the generator. Values in:
 *   topic: string     (required, 2-120 chars)
 *   audience: string  (optional, max 80 chars; defaults to "beginners")
 *
 * Values out:
 *   angles: { columns: string[]; rows: string[][] }
 *   count: number
 */
export function runTool(values: Record<string, unknown>): {
  ok: boolean;
  values?: Record<string, unknown>;
  error?: string;
} {
  const v = values ?? {};

  const topicRaw = v["topic"];
  const topic = typeof topicRaw === "string" ? topicRaw.trim() : "";
  if (!topic) {
    return { ok: false, error: "Topic is required." };
  }
  if (topic.length < 2 || topic.length > MAX_TOPIC_CHARS) {
    return { ok: false, error: `Topic must be 2-${MAX_TOPIC_CHARS} characters.` };
  }

  let audience = DEFAULT_AUDIENCE;
  const audienceRaw = v["audience"];
  if (audienceRaw !== undefined && audienceRaw !== null && String(audienceRaw).trim() !== "") {
    audience = String(audienceRaw).trim();
    if (audience.length > MAX_AUDIENCE_CHARS) {
      return { ok: false, error: `Audience must be ${MAX_AUDIENCE_CHARS} characters or fewer.` };
    }
  }

  const year = String(new Date().getUTCFullYear());
  const columns = ["Angle type", "Title idea", "Why it works"];
  const rows: string[][] = ANGLE_BANK.map((angle) => [
    angle.type,
    angle.template
      .replace(/\{topic\}/g, topic)
      .replace(/\{audience\}/g, audience)
      .replace(/\{year\}/g, year),
    angle.why,
  ]);

  return {
    ok: true,
    values: { angles: { columns, rows }, count: rows.length },
  };
}
