/**
 * How-To Schema Generator — pure logic (zero imports, zero network, zero DOM).
 *
 * Builds a valid schema.org HowTo JSON-LD block with a HowToStep list.
 *
 * Honesty contract (from spec honestyNote):
 * - This tool only FORMATS the user's own steps into schema.org HowTo
 *   JSON-LD. Nothing is generated by AI; no steps, times, or costs are
 *   invented or verified.
 * - totalTime is validated as an ISO 8601 duration string only — the tool
 *   cannot check it matches your real steps.
 * - estimatedCost is emitted as plain text exactly as typed — the tool
 *   cannot verify prices or currencies.
 * - Deterministic: same inputs always produce the same JSON-LD.
 *
 * Input shape for runTool values["steps"]:
 *   - preferred: { name, text }[] (1–30 steps)
 *   - also accepted: a textarea string in the documented format —
 *     blank-line-separated blocks; the first line of each block is the
 *     step name, the remaining lines are the step text.
 */

export interface HowToStepInput {
  name: string;
  text: string;
}

export interface HowToSchemaRunValues {
  jsonLd: string;
  errors: string[];
}

export interface RunToolResult {
  ok: boolean;
  values?: Record<string, unknown>;
  error?: string;
}

export const MAX_STEPS = 30;
export const MAX_NAME_CHARS = 200;
export const MAX_COST_CHARS = 100;

/**
 * ISO 8601 duration, e.g. PT30M, P1DT2H, P2W. At least one component is
 * required — bare "P" or "PT" is rejected. Weeks cannot be combined with
 * other date components (per ISO 8601).
 */
const DURATION_RE =
  /^P(?!$)(\d+Y)?(\d+M)?(\d+W)?(\d+D)?(T(?!$)(\d+H)?(\d+M)?(\d+S)?)?$/;

export function isValidIso8601Duration(value: string): boolean {
  const v = value.trim();
  if (v === "" || !DURATION_RE.test(v)) return false;
  // A week designator must stand alone among the date components.
  const datePart = v.split("T")[0].slice(1);
  const hasW = /\d+W/.test(datePart);
  const hasOtherDate = /(\d+Y|\d+M|\d+D)/.test(datePart);
  return !(hasW && hasOtherDate);
}

/**
 * Parse the textarea format into steps: blank-line-separated blocks, first
 * line = step name, remaining lines = step text. Empty blocks are ignored.
 */
export function parseStepsText(text: string): HowToStepInput[] {
  const steps: HowToStepInput[] = [];
  const blocks = text.split(/\r?\n\s*\r?\n/);
  for (const block of blocks) {
    const lines = block.split(/\r?\n/).map((l) => l.trimEnd());
    while (lines.length > 0 && lines[0].trim() === "") lines.shift();
    if (lines.length === 0) continue;
    const name = lines[0].trim();
    const stepText = lines.slice(1).join("\n").trim();
    if (name === "" && stepText === "") continue;
    steps.push({ name, text: stepText });
  }
  return steps;
}

/**
 * Tool-logic slot. Values keys: name, steps, totalTime?, estimatedCost?.
 * Returns values: { jsonLd, errors } (match meta.ts ids).
 */
export function runTool(values: Record<string, unknown>): RunToolResult {
  if (!values || typeof values !== "object") {
    return { ok: false, error: "Please enter your how-to details first." };
  }

  const name = typeof values["name"] === "string" ? values["name"].trim() : "";
  const totalTimeRaw = values["totalTime"];
  const totalTime = typeof totalTimeRaw === "string" ? totalTimeRaw.trim() : "";
  const costRaw = values["estimatedCost"];
  const estimatedCost = typeof costRaw === "string" ? costRaw.trim() : "";

  if (name.length === 0) {
    return { ok: false, error: "Please enter the how-to title." };
  }
  if (name.length > MAX_NAME_CHARS) {
    return {
      ok: false,
      error: `Title is ${name.length} characters (max ${MAX_NAME_CHARS}).`,
    };
  }

  const rawSteps = values["steps"];
  let steps: HowToStepInput[];
  if (Array.isArray(rawSteps)) {
    steps = rawSteps as HowToStepInput[];
  } else if (typeof rawSteps === "string") {
    steps = parseStepsText(rawSteps);
  } else {
    return { ok: false, error: "Please add at least one step." };
  }

  if (steps.length === 0) {
    return { ok: false, error: "Please add at least one step." };
  }
  if (steps.length > MAX_STEPS) {
    return {
      ok: false,
      error: `Too many steps: ${steps.length} (max ${MAX_STEPS}). Split into multiple how-tos.`,
    };
  }

  const errors: string[] = [];
  const stepList: object[] = [];
  for (let i = 0; i < steps.length; i++) {
    const s = steps[i];
    const sName = s && typeof s.name === "string" ? s.name.trim() : "";
    const sText = s && typeof s.text === "string" ? s.text.trim() : "";
    if (sName === "") {
      return { ok: false, error: `Step ${i + 1}: step name is required.` };
    }
    if (sText === "") {
      errors.push(`Step ${i + 1}: step text is empty — a name-only step was emitted.`);
    }
    stepList.push({
      "@type": "HowToStep",
      position: i + 1,
      name: sName,
      text: sText,
    });
  }

  if (totalTime !== "" && !isValidIso8601Duration(totalTime)) {
    return {
      ok: false,
      error: `"${totalTime}" is not a valid ISO 8601 duration. Use e.g. PT30M (30 minutes) or P1DT2H (1 day, 2 hours).`,
    };
  }
  if (estimatedCost.length > MAX_COST_CHARS) {
    return {
      ok: false,
      error: `Estimated cost is ${estimatedCost.length} characters (max ${MAX_COST_CHARS}).`,
    };
  }

  const howTo: Record<string, unknown> = {
    "@context": "https://schema.org",
    "@type": "HowTo",
    name,
    step: stepList,
  };
  if (totalTime !== "") howTo["totalTime"] = totalTime;
  if (estimatedCost !== "") howTo["estimatedCost"] = estimatedCost;

  const out: HowToSchemaRunValues = {
    jsonLd: JSON.stringify(howTo, null, 2),
    errors,
  };
  return { ok: true, values: out as unknown as Record<string, unknown> };
}
