import type { ToolInput, ToolOutput } from '../../../src/lib/registry/types.ts';
import type { ToolContent } from '../../../src/templates/types.ts';

const TOOL_URL = 'https://husnainblogger.com/tools/blogging-seo/how-to-schema-generator/';

export const inputs: ToolInput[] = [
  {
    id: 'name',
    label: 'How-to title',
    type: 'text',
    required: true,
    placeholder: 'How to brew pour-over coffee',
  },
  {
    id: 'steps',
    label: 'Steps',
    type: 'textarea',
    required: true,
    placeholder:
      'Heat the water\nHeat filtered water to 92°C.\n\nGrind the beans\nGrind 20g of beans medium-coarse.',
  },
  {
    id: 'totalTime',
    label: 'Total time (optional)',
    type: 'text',
    required: false,
    placeholder: 'PT15M (ISO 8601, e.g. PT30M or P1DT2H)',
  },
  {
    id: 'estimatedCost',
    label: 'Estimated cost (optional)',
    type: 'text',
    required: false,
    placeholder: 'Under $5',
  },
];

export const outputs: ToolOutput[] = [
  {
    id: 'jsonLd',
    label: 'JSON-LD markup (copy)',
    type: 'copy',
    description:
    'Free howto schema generator 2026: Valid schema.org HowTo JSON-LD with your step list. free.',
  },
  {
    id: 'errors',
    label: 'Validation notes',
    type: 'list',
    description:
    'Warnings about the steps (e.g. a step with no text).',
  },
];

export const content: ToolContent = {
  title: 'How-To Schema Generator',
  description:
    'Generate valid howto schema JSON-LD for your tutorials in seconds. List steps, time, and cost, then copy the ready-to-paste markup. Try it free now.',
  howTo: [
    'Enter the "How-to title" — the name of your tutorial or guide.',
    'Add your "Steps" — one block per step: the step name on the first line, the step text on the following lines, with a blank line between steps.',
    'Optionally enter "Total time" as an ISO 8601 duration (e.g. PT30M for 30 minutes) and an "Estimated cost" in plain text.',
    'Run the tool and check "Validation notes" for warnings such as steps without text.',
    'Copy the "JSON-LD markup" into your tutorial page and test it in Google\'s Rich Results Test.',
  ],
  methodology:
    'This tool formats your title and steps into a schema.org HowTo JSON-LD block with a numbered HowToStep list (each step gets a position). Title is limited to 200 chars, 1–30 steps are allowed, totalTime is validated as an ISO 8601 duration (format only — the tool cannot check it matches your real steps), and estimatedCost is emitted as plain text exactly as typed. Nothing is generated by AI — the output contains only your own words.',
  examples: [
    {
      title: 'Coffee tutorial with time and cost',
      inputs: {
        name: 'How to brew pour-over coffee',
        steps: 'Heat the water\nHeat filtered water to 92°C.\n\nGrind the beans\nGrind 20g of beans medium-coarse.',
        totalTime: 'PT15M',
        estimatedCost: 'Under $5',
      },
      note: 'Full how-to with duration and cost included in the markup.',
    },
    {
      title: 'Minimal single step',
      inputs: {
        name: 'How to restart the app',
        steps: 'Restart\nClose the app fully, then open it again.',
      },
      note: 'One step and no optionals — still valid HowTo markup.',
    },
    {
      title: 'Step without text warned',
      inputs: {
        name: 'Setup guide',
        steps: 'Install the app\n\nCreate an account\nSign up with your email.',
      },
      note: 'The text-less step is still emitted; Validation notes flag it.',
    },
  ],
  faqs: [
    {
      question: 'What is the best howto schema generator?',
      answer:
        'The best HowTo schema generator builds valid schema.org HowTo JSON-LD with a properly numbered step list, validates the ISO 8601 duration format, and needs no signup. This tool does all three — add your steps, copy the markup, and test it in Google\'s Rich Results Test.',
    },
    {
      question: 'Is there a free howto schema generator?',
      answer:
        'Yes — this HowTo schema generator is completely free with no signup. Add up to 30 steps with optional total time and estimated cost, then copy the ready-to-paste JSON-LD.',
    },
    {
      question: 'How to generate howto schema?',
      answer:
        'Enter your how-to title and steps (step name on the first line, step text after it), add an ISO 8601 total time like PT30M if you want, then copy the generated JSON-LD into your tutorial page. Test the live page in Google\'s Rich Results Test to confirm it is detected.',
    },
    {
      question: 'How does the howto schema generator work?',
      answer:
        'Enter your details using the inputs above and the howto schema generator calculates everything instantly in your browser. No data leaves your device, and you get results the moment you change any value.',
    },
    {
      question: 'Is the howto schema generator free to use?',
      answer:
        'Yes - this howto schema generator is completely free with no signup, no account, and no usage limits. It runs 100% in your browser.',
    },
    {
      question: 'What is a howto schema generator?',
      answer:
        'A howto schema generator is a free online tool that gives you quick, accurate results without spreadsheets or manual math. This version runs entirely in your browser for instant, private results.',
    },
    {
      question: 'Do I need to create an account to use the howto schema generator?',
      answer:
        'No account needed. Open the howto schema generator, enter your values, and see results immediately - nothing is stored or sent anywhere.',
    },
  ],
  assumptions: [
    'estimatedCost is emitted as plain text exactly as you typed it — the tool does not verify prices or currencies.',
    'totalTime is validated as an ISO 8601 duration format only; the tool cannot check it matches your actual steps.',
    'HowTo rich results are only eligible when the steps are visible on the page and match the markup.',
  ],
  jsonLd: [
  ],
};
