import type { ToolInput, ToolOutput } from '../../../src/lib/registry/types.ts';
import type { ToolContent } from '../../../src/templates/types.ts';

const TOOL_URL = 'https://husnainblogger.com/tools/youtube/shorts-hook-bank/';

const DESCRIPTION =
  'Get fresh youtube shorts hook ideas in seconds — pick a topic and hook style to pull opening lines from 40 hand-written templates, each labeled. Try it free.';

export const inputs: ToolInput[] = [
  {
    id: 'topic',
    label: 'Short topic',
    type: 'text',
    required: true,
    placeholder: 'e.g. sourdough starter',
  },
  {
    id: 'style',
    label: 'Hook style',
    type: 'select',
    required: true,
    options: ['question', 'bold-claim', 'visual', 'loop'],
  },
  {
    id: 'count',
    label: 'Number of hooks',
    type: 'number',
    required: false,
    placeholder: '10',
    validation: { min: 1, max: 40 },
  },
];

export const outputs: ToolOutput[] = [
  { id: 'hooks', label: 'Hook lines', type: 'list' },
  { id: 'count', label: 'Hooks generated', type: 'number' },
  { id: 'note', label: 'Method note', type: 'text' },
];

export const content: ToolContent = {
  title: 'Youtube Shorts Hook Ideas',
  description: DESCRIPTION,
  howTo: [
    'Enter your Short\u2019s topic (e.g. "sourdough starter").',
    'Pick a hook style: question, bold claim, visual, or loop.',
    'Choose how many hooks you want (1–40; defaults to 10).',
    'Run the bank and scan the hook lines — each one is labeled with its template (e.g. [template: bold-claim #3]).',
    'Test the winners on camera: the first 2 seconds decide the swipe, so read each hook aloud before filming.',
  ],
  methodology:
    'Template library, not AI. The bank holds 40 hand-written hook formulas (10 per style × 4 styles: question, bold claim, visual, loop), each written for the first 2 seconds of vertical short-form. Your topic is filled into the {topic} slot and hooks are served in bank order, cycling after 10 when you request more. Every line carries its template attribution so you can see exactly which formula produced it. Nothing is generated by a language model and no performance is promised — test hooks against your real audience.',
  examples: [
    {
      title: 'Question hooks for baking',
      inputs: { topic: 'sourdough starter', style: 'question', count: 5 },
      note: 'Five curiosity-driven openers with template labels.',
    },
    {
      title: 'Bold-claim hooks for fitness',
      inputs: { topic: 'home workouts', style: 'bold-claim', count: 3 },
      note: 'Punchy statements like "Stop doing home workouts — do this instead."',
    },
    {
      title: 'Loop hooks for a series',
      inputs: { topic: 'budget travel', style: 'loop', count: 4 },
      note: 'Open-loop lines built for seamless rewatch.',
    },
  ],
  faqs: [
    {
      question: 'How to use shorts on youtube?',
      answer: 'This is a common question about how to use shorts on youtube. Use the tool above to get your answer instantly - it is free and requires no signup.',
    },
    {
      question: 'How to write a hook examples?',
      answer: 'This is a common question about how to write a hook examples. Use the tool above to get your answer instantly - it is free and requires no signup.',
    },
    {
      question: 'How to make a shorts on youtube?',
      answer: 'This is a common question about how to make a shorts on youtube. Use the tool above to get your answer instantly - it is free and requires no signup.',
    },
    {
      question: 'What is the best youtube shorts hook ideas?',
      answer:
        'The best hook matches your content: questions spark curiosity, bold claims stop the swipe, visual hooks promise something worth watching, and loop hooks drive rewatches. This free bank gives you 40 hand-written formulas across all four styles so you can pick what fits your topic instead of staring at a blank page.',
    },
    {
      question: 'Is there a free youtube shorts hook ideas?',
      answer:
        'Yes — this hook bank is completely free with no signup. Enter a topic, pick one of four styles, and get up to 40 opening lines, each labeled with the template it came from.',
    },
    {
      question: 'How to use youtube shorts hook?',
      answer:
        'Say the hook in the first 2 seconds, on camera, before any intro or logo. Pick a line from the bank, read it aloud to check it sounds natural, then film the payoff immediately after. If a hook underperforms, try another style — different topics win with different formulas.',
    },
    {
      question: 'How does a youtube shorts hook ideas work?',
      answer:
        'You enter a topic and choose a style (question, bold claim, visual, or loop). The tool fills your topic into hand-written hook templates and serves them in bank order with template attribution. These are fixed formulas, not AI-generated lines, so quality is your judgment — test them with real viewers.',
    },
    {
      question: 'How does the youtube shorts hook ideas work?',
      answer:
        'Enter your details using the inputs above and the youtube shorts hook ideas calculates everything instantly in your browser. No data leaves your device, and you get results the moment you change any value.',
    },
    {
      question: 'Is the youtube shorts hook ideas free to use?',
      answer:
        'Yes - this youtube shorts hook ideas is completely free with no signup, no account, and no usage limits. It runs 100% in your browser.',
    },
    {
      question: 'What is a youtube shorts hook ideas?',
      answer:
        'A youtube shorts hook ideas is a free online tool that gives you quick, accurate results without spreadsheets or manual math. This version runs entirely in your browser for instant, private results.',
    },
  ],
  assumptions: [
    'Hooks come from 40 hand-written templates (10 per style); they are starting points, not proven winners for your audience.',
    'Hook quality is subjective — no views, retention, or virality is promised or implied.',
    'Templates cycle in bank order when you request more than 10 hooks in one style.',
    'The topic is inserted verbatim; check that grammar and capitalization read naturally in each line.',
  ],
  jsonLd: [
  ],
};
