import type { ToolInput, ToolOutput } from '../../../src/lib/registry/types.ts';
import type { ToolContent } from '../../../src/templates/types.ts';

const TOOL_URL = 'https://husnainblogger.com/tools/youtube/competitor-gap-finder/';

const DESCRIPTION =
  'Use this free YouTube competitor analysis template as a worksheet — paste competitor topics, see your coverage matrix and get gap-angle prompts. Start now.';

export const inputs: ToolInput[] = [
  {
    id: 'competitorName',
    label: 'Competitor channel name (optional)',
    type: 'text',
    required: false,
    placeholder: 'e.g. Rival Channel',
  },
  {
    id: 'competitorTopics',
    label: 'Competitor video topics (one per line)',
    type: 'textarea',
    required: true,
    placeholder: 'Best budget microphones\nHow to start a podcast\nTop 5 video ideas',
  },
  {
    id: 'ownTopics',
    label: 'Your covered topics (one per line, optional)',
    type: 'textarea',
    required: false,
    placeholder: 'How to start a podcast\nMy gear tour',
  },
];

export const outputs: ToolOutput[] = [
  { id: 'coverageMatrix', label: 'Topic coverage matrix', type: 'table' },
  { id: 'uncoveredTopics', label: 'Uncovered topics', type: 'list' },
  { id: 'angleSuggestions', label: 'Angle suggestions', type: 'list' },
  { id: 'coveragePercent', label: 'Coverage percent', type: 'percent' },
  { id: 'coveredCount', label: 'Covered count', type: 'number' },
  { id: 'uncoveredCount', label: 'Uncovered count', type: 'number' },
  { id: 'honestyNote', label: 'Honesty note', type: 'text' },
  { id: 'isWorksheet', label: 'Worksheet flag', type: 'text' },
];

export const content: ToolContent = {
  title: 'Youtube Competitor Analysis Template',
  description: DESCRIPTION,
  howTo: [
    'Open a competitor channel and copy the titles of their recent videos (one per line).',
    'Paste those topics into the competitor-topics box, plus your own covered topics.',
    'Run the worksheet to get a coverage matrix: which topics you cover and which are gaps.',
    'Read the angle suggestions for each gap — 12 hand-written prompt patterns like mistakes, comparisons, and case studies.',
    'Validate any gap with your own demand research before filming — the worksheet ranks nothing.',
  ],
  methodology:
    'This is a manual worksheet, not automated analysis: it has no YouTube API access and performs no scraping (which YouTube\'s ToS forbids). It normalizes the topics you paste (lowercase, punctuation-insensitive), marks a competitor topic as covered when one of your topics matches exactly or contains it (minimum 8 characters), and attaches angle prompts by cycling through 12 hand-written templates in fixed order. Nothing is generated by AI and no competitor performance data is used.',
  examples: [
    {
      title: 'Podcast niche check',
      inputs: {
        competitorName: 'Rival Channel',
        competitorTopics: 'Best budget microphones\nHow to start a podcast\nTop 5 video ideas',
        ownTopics: 'How to start a podcast\nMy gear tour',
      },
      note: '2 gaps found ("Best budget microphones", "Top 5 video ideas") each with an angle prompt; 33% coverage.',
    },
    {
      title: 'No own topics yet',
      inputs: { competitorTopics: 'Sourdough starter guide\nBest bread flour' },
      note: 'Both topics are gaps with angle prompts — a starting map for a new channel.',
    },
  ],
  faqs: [
    {
      question: 'what is the best youtube competitor analysis template?',
      answer:
        'An honest one: it must not pretend to analyze competitors automatically. This free template is a manual worksheet — you paste competitor topics, it builds a coverage matrix and gap-angle prompts. Any tool claiming automated competitor analysis without YouTube API access is not doing real analysis.',
    },
    {
      question: 'is there a free youtube competitor analysis template?',
      answer:
        'Yes — this worksheet is completely free with no signup. Paste competitor video topics one per line, add your own topics, and get a coverage matrix, uncovered topics, and 12-pattern angle suggestions.',
    },
    {
      question: 'how to use youtube competitor analysis?',
      answer:
        'List a competitor\'s recent video topics, list the ones you have covered, and look for topics they do well that you have not made. This worksheet organizes that comparison — but always validate demand (search interest, comments asking for it) before filming a gap.',
    },
    {
      question: 'how does a youtube competitor analysis template work?',
      answer:
        'It is a structured comparison, not software analysis: you supply both topic lists manually. This tool normalizes them, marks exact or containing matches as covered, and attaches angle prompts to the gaps from a fixed 12-template bank.',
    },
    {
      question: 'How does the youtube competitor analysis template work?',
      answer:
        'Enter your details using the inputs above and the youtube competitor analysis template calculates everything instantly in your browser. No data leaves your device, and you get results the moment you change any value.',
    },
    {
      question: 'Is the youtube competitor analysis template free to use?',
      answer:
        'Yes - this youtube competitor analysis template is completely free with no signup, no account, and no usage limits. It runs 100% in your browser.',
    },
    {
      question: 'What is a youtube competitor analysis template?',
      answer:
        'A youtube competitor analysis template is a free online tool that gives you quick, accurate results without spreadsheets or manual math. This version runs entirely in your browser for instant, private results.',
    },
  ],
  assumptions: [
    'No automated competitor analysis is performed — the tool organizes only what you paste; it cannot see views, rankings, or channel data.',
    'Topic matching is simple text comparison (exact or containment), so paraphrased titles may be missed or mismatched.',
    'A gap is not a recommendation — uncovered topics may be uncovered because they perform badly; validate demand yourself.',
  ],
  jsonLd: [
    {
      '@type': 'SoftwareApplication',
      name: 'Youtube Competitor Analysis Template 2026 | HusnainBlogger',
      url: TOOL_URL,
      applicationCategory: 'Utilities',
      operatingSystem: 'Web',
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      description: DESCRIPTION,
    },
    {
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://husnainblogger.com/' },
        { '@type': 'ListItem', position: 2, name: 'Tools', item: 'https://husnainblogger.com/tools/' },
        { '@type': 'ListItem', position: 3, name: 'YouTube Tools', item: 'https://husnainblogger.com/tools/youtube/' },
        { '@type': 'ListItem', position: 4, name: 'Competitor Gap Finder', item: TOOL_URL },
      ],
    },
  ],
};
