import type { ToolInput, ToolOutput } from '../../../src/lib/registry/types.ts';
import type { ToolContent } from '../../../src/templates/types.ts';

export const inputs: ToolInput[] = [
  {
    id: 'labelBefore',
    label: 'Before label',
    type: 'text',
    required: true,
    placeholder: 'e.g. Original',
    validation: { max: 40 },
  },
  {
    id: 'labelAfter',
    label: 'After label',
    type: 'text',
    required: true,
    placeholder: 'e.g. Edited',
    validation: { max: 40 },
  },
  {
    id: 'orientation',
    label: 'Slider orientation',
    type: 'select',
    required: true,
    options: ['horizontal', 'vertical'],
  },
  {
    id: 'startPct',
    label: 'Divider start position (%)',
    type: 'number',
    required: false,
    placeholder: '50',
    validation: { min: 5, max: 95 },
  },
];

export const outputs: ToolOutput[] = [
  { id: 'htmlSnippet', label: 'HTML snippet', type: 'copy' },
  { id: 'cssSnippet', label: 'CSS snippet', type: 'copy' },
  { id: 'jsSnippet', label: 'JavaScript snippet', type: 'copy' },
  { id: 'embedParams', label: 'Embed parameters', type: 'text' },
];

const DESCRIPTION =
  'Add a before/after slider to any web page: enter your image URLs and custom labels, choose a horizontal or vertical layout, then paste the embed code.';

export const content: ToolContent = {
  title: 'Before After Slider Generator',
  description: DESCRIPTION,
  howTo: [
    'Type your BEFORE label and AFTER label (40 characters max each) — these appear as tags on the slider.',
    'Choose the slider orientation: horizontal for side-by-side reveals, vertical for top/bottom reveals.',
    'Set the divider start position (5–95%; defaults to 50) to control how much of the before image shows first.',
    'Copy the HTML, CSS, and JavaScript snippets with the copy buttons.',
    'In the HTML, replace YOUR_BEFORE_IMAGE_URL and YOUR_AFTER_IMAGE_URL with your own hosted image URLs, then paste all three snippets into your page.',
  ],
  methodology:
    'The tool fills fixed HTML/CSS/JS templates with your labels, orientation, and start position — nothing is generated by AI. The CSS includes a fixed bank of 4 handle styles (circle, ring, arrows, neon) with circle active by default; the drag transition is fixed pointer-follow with keyboard arrow support. No images are uploaded, processed, or hosted: the snippet only references URLs you supply.',
  examples: [
    {
      title: 'Product photo edit',
      inputs: { labelBefore: 'Original', labelAfter: 'Edited', orientation: 'horizontal', startPct: 50 },
      note: 'A classic side-by-side edit reveal starting at the halfway point.',
    },
    {
      title: 'Vertical restoration',
      inputs: { labelBefore: 'Old', labelAfter: 'Restored', orientation: 'vertical', startPct: 30 },
      note: 'A top/bottom slider that starts mostly on the restored version.',
    },
  ],
  faqs: [
    {
      question: 'What is the best before after slider generator?',
      answer:
        'The best one for a website is a lightweight embed you control — this free generator gives you copy-paste HTML, CSS, and JavaScript with no dependencies, so the slider works on any page without a plugin or subscription.',
    },
    {
      question: 'Is there a free before after slider generator?',
      answer:
        'Yes — this before after slider generator is completely free with no signup. You get the full embed code instantly; you only need your own hosted image URLs to plug in.',
    },
    {
      question: 'How to generate before after?',
      answer:
        'Enter your before/after labels, pick horizontal or vertical orientation, set the divider start position, and copy the three snippets. Replace the two placeholder image URLs with your own, paste the code into your page, and the draggable slider is live.',
    },
    {
      question: 'How does a before after slider generator work?',
      answer:
        'This generator fills fixed code templates with your labels, orientation, and start position. The output clips the before image with CSS and moves a drag handle with plain JavaScript — no libraries, no image processing, and no hosting on our side.',
    },
    {
      question: 'How does the before after slider generator work?',
      answer:
        'Enter your details using the inputs above and the before after slider generator calculates everything instantly in your browser. No data leaves your device, and you get results the moment you change any value.',
    },
    {
      question: 'Is the before after slider generator free to use?',
      answer:
        'Yes - this before after slider generator is completely free with no signup, no account, and no usage limits. It runs 100% in your browser.',
    },
    {
      question: 'What is a before after slider generator?',
      answer:
        'A before after slider generator is a free online tool that gives you quick, accurate results without spreadsheets or manual math. This version runs entirely in your browser for instant, private results.',
    },
  ],
  assumptions: [
    'Generates embed code only — you must supply your own hosted image URLs; the tool never uploads, processes, or stores images.',
    'Handle styles come from a fixed bank of 4 presets (circle, ring, arrows, neon); the drag transition is fixed pointer-follow and cannot be customized here.',
    'The snippet pattern is standard HTML/CSS/JS but is not tested in every browser — preview the embed on your own page before publishing.',
  ],
  jsonLd: [
    {
      '@type': 'SoftwareApplication',
      name: 'Before After Slider Generator 2026 – Free | HusnainBlogger',
      url: 'https://husnainblogger.com/tools/video-editing/before-after-slider-generator/',
      applicationCategory: 'Utilities',
      operatingSystem: 'Web',
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      description: DESCRIPTION,
    },
    {
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://husnainblogger.com/' },
        { '@type': 'ListItem', position: 2, name: 'Tools', item: 'https://husnainblogger.com/tools/' },
        {
          '@type': 'ListItem',
          position: 3,
          name: 'Video Editing Tools',
          item: 'https://husnainblogger.com/tools/video-editing/',
        },
        {
          '@type': 'ListItem',
          position: 4,
          name: 'Before/After Slider Generator',
          item: 'https://husnainblogger.com/tools/video-editing/before-after-slider-generator/',
        },
      ],
    },
  ],
};
