import type { ToolInput, ToolOutput } from '../../../src/lib/registry/types.ts';
import type { ToolContent } from '../../../src/templates/types.ts';

const TOOL_URL = 'https://husnainblogger.com/tools/blogging-seo/pros-cons-box-generator/';

export const inputs: ToolInput[] = [
  {
    id: 'pros',
    label: 'Pros (one per line, 1–10)',
    type: 'textarea',
    required: true,
    placeholder: 'Easy to set up\nFast support\nFree plan available',
  },
  {
    id: 'cons',
    label: 'Cons (one per line, 1–10)',
    type: 'textarea',
    required: true,
    placeholder: 'No mobile app\nLimited free tier',
  },
  {
    id: 'title',
    label: 'Box title (optional)',
    type: 'text',
    required: false,
    placeholder: 'Pros & Cons',
    validation: { pattern: '^.{1,100}$' },
  },
];

export const outputs: ToolOutput[] = [
  {
    id: 'boxHtml',
    label: 'Box HTML (copy)',
    type: 'copy',
    description:
    'Free pros and cons box generator 2026: Ready-to-paste pros & cons box with minimal inline styles — works in any blog theme. Fast, private.',
  },
  {
    id: 'boxCss',
    label: 'Box CSS (copy)',
    type: 'copy',
    description:
    'Optional matching CSS block — the HTML already carries inline styles, so this is skippable.',
  },
];

export const content: ToolContent = {
  title: 'Pros and Cons Box Generator',
  description:
    'Create a clean pros and cons box for your reviews in seconds. Type your pros and cons, copy the ready-to-paste HTML, and drop it into any post. Try it.',
  howTo: [
    'Type your pros in the "Pros" box — one per line, up to 10.',
    'Type your cons in the "Cons" box — one per line, up to 10.',
    'Optionally set a "Box title" (defaults to "Pros & Cons").',
    'Run the tool and review the box preview.',
    'Copy the "Box HTML" and paste it into your post\'s HTML or Custom HTML block. Add the "Box CSS" to your theme only if you want to restyle it.',
  ],
  methodology:
    'Your pros and cons are parsed as plain text, HTML-escaped (so nothing you type can inject markup), and assembled into a two-column pros/cons box that stacks on mobile. Styling is intentionally minimal and inline so the snippet works in any blog theme without edits. Nothing is generated by AI — the box contains only your own words.',
  examples: [
    {
      title: 'Plugin review box',
      inputs: { pros: 'Easy to set up\nFast support', cons: 'No mobile app', title: 'Plugin X Review' },
      note: 'A typical review box with a custom title.',
    },
    {
      title: 'Default title',
      inputs: { pros: 'Affordable', cons: 'Limited free tier' },
      note: 'Omitting the title uses the default "Pros & Cons" heading.',
    },
    {
      title: 'Longer lists',
      inputs: { pros: 'Fast\nCheap\nReliable\nGood docs', cons: 'No API\nWeak mobile', title: 'Service Y' },
      note: 'Up to 10 items per side; each item caps at 200 characters.',
    },
  ],
  faqs: [
    {
      question: 'What is the best pros and cons box generator?',
      answer:
        'The best pros and cons box generator turns your lists into clean, mobile-friendly HTML you can paste into any blog theme without edits. This tool does that — you get inline-styled box HTML plus an optional CSS block, free with no signup.',
    },
    {
      question: 'Is there a free pros and cons box generator?',
      answer:
        'Yes — this pros and cons box generator is completely free with no signup. Create boxes with 1–10 pros and 1–10 cons, and regenerate as often as you like.',
    },
    {
      question: 'How to generate pros and cons?',
      answer:
        'Type your pros one per line and your cons one per line, optionally set a box title, then run the tool. Copy the generated HTML into your post\'s HTML or Custom HTML block and the two-column box appears in your article.',
    },
    {
      question: 'How does a pros and cons box generator work?',
      answer:
        'It takes the lists you type, escapes them so they can\'t break your page, and assembles them into a styled two-column box with inline CSS that works in any blog theme. Nothing is written by AI — the box contains only your own words.',
    },
    {
      question: 'How does the pros and cons box generator work?',
      answer:
        'Enter your details using the inputs above and the pros and cons box generator calculates everything instantly in your browser. No data leaves your device, and you get results the moment you change any value.',
    },
    {
      question: 'Is the pros and cons box generator free to use?',
      answer:
        'Yes - this pros and cons box generator is completely free with no signup, no account, and no usage limits. It runs 100% in your browser.',
    },
    {
      question: 'What is a pros and cons box generator?',
      answer:
        'A pros and cons box generator is a free online tool that gives you quick, accurate results without spreadsheets or manual math. This version runs entirely in your browser for instant, private results.',
    },
  ],
  assumptions: [
    'Styling is intentionally minimal and inline so the snippet works in any blog theme — customize the CSS block for a branded look.',
    'All content is HTML-escaped; you cannot inject raw HTML, scripts, or attributes through this tool.',
    'The two columns stack vertically on screens under 600px.',
    '1–10 items per side; each item max 200 characters; title max 100 characters.',
  ],
  jsonLd: [],
};
