import type { ToolInput, ToolOutput } from '../../../src/lib/registry/types.ts';
import type { ToolContent } from '../../../src/templates/types.ts';

const TOOL_URL = 'https://husnainblogger.com/tools/instagram/reels-cover-title-generator/';

export const inputs: ToolInput[] = [
  {
    id: 'topic',
    label: 'Reel topic',
    type: 'text',
    required: true,
    placeholder: 'e.g. meal prep, morning routines',
  },
  {
    id: 'tone',
    label: 'Tone',
    type: 'select',
    required: true,
    options: ['bold', 'playful', 'professional', 'curious'],
  },
  {
    id: 'count',
    label: 'How many titles',
    type: 'number',
    required: true,
    validation: { min: 1, max: 20 },
  },
];

export const outputs: ToolOutput[] = [
  {
    id: 'titles',
    label: 'Cover titles',
    type: 'list',
    description:
    'Free reels cover text ideas 2026: Cover titles with character counts, built from fixed title formulas — no AI involved. Fast, private now.',
  },
  {
    id: 'safeZoneNote',
    label: 'Safe-zone guidance',
    type: 'text',
    description:
    '1080x1920 cover safe zones plus auto-truncation warnings for titles over 60 characters.',
  },
];

export const content: ToolContent = {
  title: 'Reels Cover Text Ideas',
  description:
    'Generate reels cover text ideas free. Enter your topic, pick a tone, and get short readable cover titles with safe-zone guidance. Create titles now.',
  howTo: [
    'Type your reel\'s topic in the "Reel topic" box (e.g. "meal prep").',
    'Pick a tone: bold, playful, professional, or curious.',
    'Choose how many titles you want (1–20) and run the tool.',
    'Each title shows its character count — aim for titles well under 60 characters for cover readability.',
    'Read the safe-zone guidance: keep key text in the middle vertical band of your 1080x1920 cover so the profile grid and UI overlays don\'t hide it.',
  ],
  methodology:
    'This tool assembles titles from a fixed bank of 48 hand-written cover-title formulas (12 per tone) — nothing is generated by AI. Selection is deterministic: a hash of your topic picks the start offset inside your tone\'s pool; if you request more than 12, the remainder cycles through the full bank with no duplicates, so up to 20 unique titles are returned. The readability rule is enforced honestly: any title over 60 characters is auto-truncated at the last word boundary (marked with …) and reported in the safe-zone note.',
  examples: [
    {
      title: 'Bold titles for meal prep',
      inputs: { topic: 'meal prep', tone: 'bold', count: 5 },
      note: 'Punchy covers like "STOP Ignoring meal prep", each with a char count.',
    },
    {
      title: 'Curious titles for skincare',
      inputs: { topic: 'skincare', tone: 'curious', count: 4 },
      note: 'Question-style covers such as "Is skincare Worth It?".',
    },
    {
      title: 'Professional titles for SEO',
      inputs: { topic: 'SEO', tone: 'professional', count: 3 },
      note: 'Authority-style covers like "The SEO Framework".',
    },
  ],
  faqs: [
    {
      question: 'What is the best reels cover text ideas?',
      answer:
        'The best reels cover text is 3–6 words, high contrast, and readable at thumbnail size — it should sell the click without repeating your caption. This tool generates tone-matched ideas free, each with a character count so you can pick the punchiest ones.',
    },
    {
      question: 'Is there a free reels cover text ideas?',
      answer:
        'Yes — this reels cover title generator is completely free with no signup. Enter your topic, pick a tone, and generate up to 20 titles in one click.',
    },
    {
      question: 'How to use reels cover text?',
      answer:
        'After uploading your reel, tap "Edit cover" and add your title as centered text in the middle vertical band of the 1080x1920 frame — the top is cropped in the profile grid and the bottom sits under the caption and buttons. Keep it under 60 characters so it stays readable as a thumbnail.',
    },
    {
      question: 'What is a reels cover text ideas?',
      answer:
        'A reels cover text ideas is a free online tool that gives you quick, accurate results without spreadsheets or manual math. This version runs entirely in your browser for instant, private results.',
    },
    {
      question: 'Do I need to create an account to use the reels cover text ideas?',
      answer:
        'No account needed. Open the reels cover text ideas, enter your values, and see results immediately - nothing is stored or sent anywhere.',
    },
  ],
  assumptions: [
    'The 60-character readability limit and the ~200px top / ~350px bottom safe zones are practical guidance, not Instagram-published specs — always preview on a real device.',
    'Titles come from 48 fixed formulas (12 per tone); they are starting points, not AI-written copy.',
    'Titles over 60 characters are auto-truncated at a word boundary and flagged — review them before use.',
  ],
  jsonLd: [],
};
