import type { ToolInput, ToolOutput } from '../../../src/lib/registry/types.ts';
import type { ToolContent, BuilderField } from '../../../src/templates/types.ts';

const SLUG = 'ugc-portfolio-page-builder';
const CANONICAL = `https://husnainblogger.com/tools/creator-business/${SLUG}/`;
const NAME = 'UGC Portfolio Page Builder';
const DESCRIPTION =
  'UGC portfolio builder: add your niches and work samples for a clean, structured portfolio profile that shows brands what you create. Free — start today.';

export const inputs: ToolInput[] = [];

export const itemFields: BuilderField[] = [
  {
    id: 'creatorName',
    label: 'Creator name',
    type: 'text',
    required: true,
    placeholder: 'e.g. Maya R.',
  },
  {
    id: 'niche',
    label: 'Niche',
    type: 'text',
    required: true,
    placeholder: 'e.g. Skincare',
  },
  {
    id: 'sampleUrl',
    label: 'Sample link (optional)',
    type: 'url',
    required: false,
    placeholder: 'https://…',
  },
  {
    id: 'sampleCaption',
    label: 'Sample caption (optional)',
    type: 'text',
    required: false,
    placeholder: 'e.g. Morning routine UGC',
  },
];

export const outputs: ToolOutput[] = [
  { id: 'portfolioData', label: 'Portfolio data', type: 'download' },
];

export const content: ToolContent = {
  title: 'UGC Portfolio Builder',
  description: DESCRIPTION,
  howTo: [
    'Add one entry per portfolio piece, using the same creator name on every entry.',
    'Set the niche for each entry (up to 10 unique niches).',
    'Paste the sample link starting with https:// and add an optional caption.',
    'Click build to generate your structured portfolio data.',
    'Download or share the result with brands.',
  ],
  methodology:
    'Your entries are validated and assembled into a structured portfolio data object (creator, niches, samples) — pure data, never rendered HTML. Niche names are de-duplicated, sample links must be valid http(s) URLs, and the same creator name must be used across all entries.',
  faqs: [
    {
      question: 'What is the best UGC portfolio builder?',
      answer:
        'The best one lets brands quickly see your niches and real work samples with clear captions. This free tool builds a structured portfolio from your entries — name, niches, and sample links — that you can share with brands.',
    },
    {
      question: 'Is there a free UGC portfolio builder?',
      answer:
        'Yes — this tool is completely free. Add your creator name, niches, and sample links, and it builds your portfolio data instantly with no sign-up.',
    },
    {
      question: 'How to build UGC portfolio?',
      answer:
        'Add one entry per sample: your creator name, the niche it belongs to, the link, and a short caption. Keep the same name across entries, cover up to 10 niches, and lead with your strongest work.',
    },
    {
      question: 'How does the ugc portfolio builder work?',
      answer:
        'Enter your details using the inputs above and the ugc portfolio builder calculates everything instantly in your browser. No data leaves your device, and you get results the moment you change any value.',
    },
    {
      question: 'Is the ugc portfolio builder free to use?',
      answer:
        'Yes - this ugc portfolio builder is completely free with no signup, no account, and no usage limits. It runs 100% in your browser.',
    },
    {
      question: 'What is an ugc portfolio builder?',
      answer:
        'An ugc portfolio builder is a free online tool that gives you quick, accurate results without spreadsheets or manual math. This version runs entirely in your browser for instant, private results.',
    },
    {
      question: 'Do I need to create an account to use the ugc portfolio builder?',
      answer:
        'No account needed. Open the ugc portfolio builder, enter your values, and see results immediately - nothing is stored or sent anywhere.',
    },
  ],
  assumptions: [
    'Output is structured portfolio data, not a designed page — the app shell renders it.',
    'Links, captions, and niches are your own content; nothing is fetched or verified.',
    'All user text is kept as plain data strings; no HTML is generated by this tool.',
  ],
  jsonLd: [
    {
      '@type': 'SoftwareApplication',
      name: NAME,
      url: CANONICAL,
      applicationCategory: 'Utilities',
      operatingSystem: 'Web',
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      description: DESCRIPTION,
    },
    {
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'UGC Portfolio Builder 2026 – Free Tool | HusnainBlogger', item: 'https://husnainblogger.com/' },
        { '@type': 'ListItem', position: 2, name: 'Tools', item: 'https://husnainblogger.com/tools/' },
        {
          '@type': 'ListItem',
          position: 3,
          name: 'Creator Business Tools',
          item: 'https://husnainblogger.com/tools/creator-business/',
        },
        { '@type': 'ListItem', position: 4, name: NAME, item: CANONICAL },
      ],
    },
  ],
};
