/**
 * Article Schema Generator — pure logic (zero imports, zero network, zero DOM).
 *
 * Builds a valid schema.org Article JSON-LD block from article metadata.
 *
 * Honesty contract (from spec honestyNote):
 * - This tool only FORMATS the user's own metadata into schema.org
 *   Article JSON-LD. Nothing is generated by AI; no content is invented.
 * - dateModified is emitted equal to datePublished (there is no separate
 *   input); update it yourself if the article changes after publishing.
 * - The markup is a minimal, valid Article block. Some Google rich-result
 *   features need extra fields (e.g. publisher logo) that this tool does
 *   not collect — valid markup is not a guarantee of rich results.
 * - Deterministic: same inputs always produce the same JSON-LD.
 */

export interface ArticleSchemaRunValues {
  jsonLd: string;
  errors: string[];
}

export interface RunToolResult {
  ok: boolean;
  values?: Record<string, unknown>;
  error?: string;
}

export const MAX_HEADLINE_CHARS = 200;
export const MAX_AUTHOR_CHARS = 100;
export const MAX_DESCRIPTION_CHARS = 500;

const DATE_RE = /^\d{4}-\d{2}-\d{2}$/;

/** True for a real calendar date in YYYY-MM-DD form (no timezones involved). */
export function isValidDate(value: string): boolean {
  if (!DATE_RE.test(value)) return false;
  const [y, m, d] = value.split("-").map(Number);
  if (m < 1 || m > 12 || d < 1 || d > 31) return false;
  const dt = new Date(Date.UTC(y, m - 1, d));
  return (
    dt.getUTCFullYear() === y && dt.getUTCMonth() === m - 1 && dt.getUTCDate() === d
  );
}

/**
 * True for an absolute http(s) URL. Pure parse — no network, no DOM.
 * Uses the WHATWG URL global (available in Node and browsers), never
 * fetching anything.
 */
export function isAbsoluteHttpUrl(value: string): boolean {
  try {
    const u = new URL(value.trim());
    return u.protocol === "http:" || u.protocol === "https:";
  } catch {
    return false;
  }
}

/** Today's date as YYYY-MM-DD in UTC — used only for the future-date warning. */
function todayUtc(): string {
  const n = new Date();
  const y = n.getUTCFullYear();
  const m = String(n.getUTCMonth() + 1).padStart(2, "0");
  const d = String(n.getUTCDate()).padStart(2, "0");
  return `${y}-${m}-${d}`;
}

/**
 * Tool-logic slot. Values keys: headline, author, datePublished, image?,
 * description?. Returns values: { jsonLd, errors } (match meta.ts ids).
 * A future publish date is a non-fatal warning in errors, not a failure.
 */
export function runTool(values: Record<string, unknown>): RunToolResult {
  if (!values || typeof values !== "object") {
    return { ok: false, error: "Please enter your article details first." };
  }

  const headline = typeof values["headline"] === "string" ? values["headline"].trim() : "";
  const author = typeof values["author"] === "string" ? values["author"].trim() : "";
  const datePublished =
    typeof values["datePublished"] === "string" ? values["datePublished"].trim() : "";
  const imageRaw = values["image"];
  const image = typeof imageRaw === "string" ? imageRaw.trim() : "";
  const descRaw = values["description"];
  const description = typeof descRaw === "string" ? descRaw.trim() : "";

  if (headline.length === 0) {
    return { ok: false, error: "Please enter the article headline." };
  }
  if (headline.length > MAX_HEADLINE_CHARS) {
    return {
      ok: false,
      error: `Headline is ${headline.length} characters (max ${MAX_HEADLINE_CHARS}).`,
    };
  }
  if (author.length === 0) {
    return { ok: false, error: "Please enter the author name." };
  }
  if (author.length > MAX_AUTHOR_CHARS) {
    return {
      ok: false,
      error: `Author name is ${author.length} characters (max ${MAX_AUTHOR_CHARS}).`,
    };
  }
  if (datePublished.length === 0) {
    return { ok: false, error: "Please enter the publish date (YYYY-MM-DD)." };
  }
  if (!isValidDate(datePublished)) {
    return {
      ok: false,
      error: `"${datePublished}" is not a valid date. Use YYYY-MM-DD, e.g. 2026-10-01.`,
    };
  }
  if (image !== "" && !isAbsoluteHttpUrl(image)) {
    return {
      ok: false,
      error: "Image must be an absolute URL starting with http:// or https://.",
    };
  }
  if (description.length > MAX_DESCRIPTION_CHARS) {
    return {
      ok: false,
      error: `Description is ${description.length} characters (max ${MAX_DESCRIPTION_CHARS}).`,
    };
  }

  const errors: string[] = [];
  if (datePublished > todayUtc()) {
    errors.push(
      "Warning: the publish date is in the future. It should reflect when the article actually went live."
    );
  }

  const article: Record<string, unknown> = {
    "@context": "https://schema.org",
    "@type": "Article",
    headline,
    author: { "@type": "Person", name: author },
    datePublished,
    // No separate input — emitted equal to datePublished (documented above).
    dateModified: datePublished,
  };
  if (image !== "") article["image"] = image;
  if (description !== "") article["description"] = description;

  const out: ArticleSchemaRunValues = {
    jsonLd: JSON.stringify(article, null, 2),
    errors,
  };
  return { ok: true, values: out as unknown as Record<string, unknown> };
}
