import type { ToolInput, ToolOutput } from '../../../src/lib/registry/types.ts';
import type { ToolContent } from '../../../src/templates/types.ts';

const TOOL_URL = 'https://husnainblogger.com/tools/blogging-seo/article-schema-generator/';

export const inputs: ToolInput[] = [
  {
    id: 'headline',
    label: 'Headline',
    type: 'text',
    required: true,
    placeholder: 'How to Brew Pour-Over Coffee',
  },
  {
    id: 'author',
    label: 'Author name',
    type: 'text',
    required: true,
    placeholder: 'Jane Doe',
  },
  {
    id: 'datePublished',
    label: 'Publish date',
    type: 'date',
    required: true,
  },
  {
    id: 'image',
    label: 'Image URL (optional)',
    type: 'url',
    required: false,
    placeholder: 'https://example.com/images/pour-over.jpg',
  },
  {
    id: 'description',
    label: 'Description (optional)',
    type: 'textarea',
    required: false,
    placeholder: 'A short summary of the article (max 500 characters).',
  },
];

export const outputs: ToolOutput[] = [
  {
    id: 'jsonLd',
    label: 'JSON-LD markup (copy)',
    type: 'copy',
    description:
    'Free article schema generator 2026: Valid schema.org Article JSON-LD — paste it into your article page. Get instant results. free now.',
  },
  {
    id: 'errors',
    label: 'Validation notes',
    type: 'list',
    description:
    'Warnings about the input (e.g. a future publish date).',
  },
];

export const content: ToolContent = {
  title: 'Article Schema Generator',
  description:
    'Generate clean article schema JSON-LD for blog posts in seconds. Enter headline, author, date, and image, then copy the valid markup. Try it free now.',
  howTo: [
    'Enter the article "Headline" and "Author name" (both required).',
    'Pick the "Publish date" — use the date the article actually went live.',
    'Optionally add an "Image URL" (must start with http:// or https://) and a short "Description".',
    'Run the tool and check "Validation notes" for warnings like a future date.',
    'Copy the "JSON-LD markup" and paste it into your article page, then test it in Google\'s Rich Results Test.',
  ],
  methodology:
    'This tool formats your metadata into a minimal, valid schema.org Article JSON-LD block: headline, author (as a Person), datePublished, dateModified (emitted equal to datePublished since there is no separate input), plus image and description when provided. Inputs are validated — headline 1–200 chars, author 1–100 chars, a real YYYY-MM-DD calendar date, and an absolute http(s) image URL. Nothing is generated by AI and no article content is invented.',
  examples: [
    {
      title: 'Blog post with image',
      inputs: {
        headline: 'How to Brew Pour-Over Coffee',
        author: 'Jane Doe',
        datePublished: '2026-09-15',
        image: 'https://example.com/images/pour-over.jpg',
        description:
    'A step-by-step guide to brewing pour-over coffee at home.',
      },
      note: 'Full metadata producing a complete Article block with image and description.',
    },
    {
      title: 'Minimal article',
      inputs: {
        headline: 'My Morning Routine',
        author: 'Jane Doe',
        datePublished: '2026-08-01',
      },
      note: 'Only the required fields — image and description are left out of the markup.',
    },
    {
      title: 'Future date flagged',
      inputs: {
        headline: 'Upcoming Trends',
        author: 'Jane Doe',
        datePublished: '2099-01-01',
      },
      note: 'Markup is still generated, but Validation notes warn that the date is in the future.',
    },
  ],
  faqs: [
    {
      question: 'What is the best article schema generator?',
      answer:
        'The best article schema generator produces valid schema.org Article JSON-LD with headline, author, and publish date, validates your inputs, and needs no signup. This tool does all three — fill in the fields, copy the markup, and test it in Google\'s Rich Results Test.',
    },
    {
      question: 'Is there a free article schema generator?',
      answer:
        'Yes — this article schema generator is completely free with no signup. Enter your headline, author, date, image, and description, and copy the ready-to-paste JSON-LD.',
    },
    {
      question: 'How to generate article schema?',
      answer:
        'Enter your article headline, author name, and publish date (plus an image URL and description if you have them), run the tool, then copy the generated JSON-LD into your article page. Test the live page in Google\'s Rich Results Test to confirm it is detected.',
    },
    {
      question: 'How does an article schema generator work?',
      answer:
        'It takes your article metadata and assembles it into a schema.org Article JSON-LD block with the correct headline, author, and date fields. Nothing is written by AI — the tool only formats the metadata you provide into valid markup.',
    },
    {
      question: 'How does the article schema generator work?',
      answer:
        'Enter your details using the inputs above and the article schema generator calculates everything instantly in your browser. No data leaves your device, and you get results the moment you change any value.',
    },
    {
      question: 'Is the article schema generator free to use?',
      answer:
        'Yes - this article schema generator is completely free with no signup, no account, and no usage limits. It runs 100% in your browser.',
    },
    {
      question: 'What is an article schema generator?',
      answer:
        'An article schema generator is a free online tool that gives you quick, accurate results without spreadsheets or manual math. This version runs entirely in your browser for instant, private results.',
    },
  ],
  assumptions: [
    'Google\'s article rich-result features may need extra fields (like a publisher logo) that this tool does not collect — the markup is valid schema.org Article but minimal.',
    'dateModified is emitted equal to datePublished; update it yourself if the article changes after publishing.',
    'A future publish date is flagged as a warning — the date should reflect when the article actually went live.',
  ],
  jsonLd: [
  ],
};
