/**
 * Booking Page Copy Generator (tool-498) — pure logic, zero imports.
 *
 * FIXED TEMPLATE + FIXED WORD BANKS, NO AI: assembles a booking-page copy
 * deck (headline, subhead, who-it's-for, benefits, process, optional price
 * anchor, FAQ stub, final CTA) from the user's own inputs using preset
 * phrase banks. Nothing is generated by a model; the price anchor is
 * echoed verbatim as user-provided; FAQ answers are [bracketed] prompts
 * for the user to fill in.
 *
 * Word banks (sizes documented for honest UI copy):
 *   HEADLINES — 4 tones × 3 headlines = 12 entries
 *   SUBHEADS  — 4 templates
 *   CTAS      — 4 tones × 3 CTA lines = 12 entries
 *   FAQ_STUB  — 3 fixed questions with [bracketed] answer prompts
 *
 * Selection is deterministic: a small string hash of
 * serviceName|targetClient|tone picks the headline/subhead/CTA, so
 * identical inputs always give identical copy.
 *
 * Rules:
 *   - serviceName and targetClient are required (non-empty).
 *   - benefits / processSteps: optional lists (one per line, or ";"
 *     separated); empty sections render an honest [bracketed] placeholder.
 *   - tone: friendly | professional | bold | warm (case-insensitive);
 *     empty defaults to "professional"; unknown values are rejected.
 */

export const TONES = ["friendly", "professional", "bold", "warm"] as const;
export type Tone = (typeof TONES)[number];
export const DEFAULT_TONE: Tone = "professional";
export const MAX_LIST_ITEMS = 12;
export const MAX_FIELD = 300;
export const MAX_LIST_ITEM = 200;

const HEADLINES: Record<Tone, string[]> = {
  professional: [
    "{service} for {client} — book your intro call",
    "Get {service} that actually moves the needle",
    "Your {service} partner for {client}",
  ],
  friendly: [
    "Let's talk {service} for your {client} goals",
    "Ready when you are: {service} made simple",
    "Hey {client} — let's sort out your {service}",
  ],
  bold: [
    "Stop guessing. Book {service} that delivers",
    "{service} for {client} who want results, not excuses",
    "Book now: serious {service} for serious {client}",
  ],
  warm: [
    "A friendly {service} partner for {client}",
    "Let's make {service} feel easy — together",
    "Welcome, {client}: your {service} journey starts here",
  ],
};

const SUBHEADS: string[] = [
  "On this intro call, we'll map your goals and see if we're a fit — no pressure, no hard pitch.",
  "Tell me where you are and where you want to be; I'll show you the fastest path there.",
  "A focused 1:1 conversation about your needs as {client} and how {service} can help.",
  "Bring your questions — you'll leave with a clear plan whether we work together or not.",
];

const CTAS: Record<Tone, string[]> = {
  professional: ["Book your intro call", "Schedule your consultation", "Reserve your spot"],
  friendly: ["Grab a time that suits you", "Let's find a time to chat", "Pick your slot below"],
  bold: ["Claim your call now", "Book before the slots fill", "Lock in your session"],
  warm: ["Choose a time that feels right", "I'd love to hear from you — pick a time", "Save your spot"],
};

const FAQ_STUB: Array<[string, string]> = [
  ["How do we start?", "[Your answer — e.g. pick a time below and you'll get a confirmation email.]"],
  ["What happens after I book?", "[Your answer — e.g. you'll receive a short prep form before our call.]"],
  ["What if I need to reschedule?", "[Your answer — e.g. your rescheduling policy.]"],
];

export interface CopyValues {
  bookingPageCopy: string;
}

export interface RunResult {
  ok: boolean;
  values?: CopyValues;
  error?: string;
}

/** Trim, strip control chars, collapse whitespace, cap length. */
export function sanitize(value: unknown, max: number): string {
  if (typeof value !== "string") return "";
  return value
    .replace(/[\x00-\x1f\x7f]/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, max);
}

/** Parse a list input: array or newline/semicolon-separated string → cleaned items. */
export function parseList(value: unknown): string[] {
  let parts: string[];
  if (Array.isArray(value)) {
    parts = value.map((v) => sanitize(v, MAX_LIST_ITEM));
  } else if (typeof value === "string") {
    parts = value
      .split(/[\r\n;]+/)
      .map((p) => sanitize(p, MAX_LIST_ITEM));
  } else {
    return [];
  }
  const seen = new Set<string>();
  const out: string[] = [];
  for (const p of parts) {
    if (p === "" || seen.has(p.toLowerCase())) continue;
    seen.add(p.toLowerCase());
    out.push(p);
    if (out.length >= MAX_LIST_ITEMS) break;
  }
  return out;
}

/** Case-insensitive tone match; null when not a valid tone. */
export function matchTone(value: string): Tone | null {
  const v = value.toLowerCase();
  return (TONES as readonly string[]).includes(v) ? (v as Tone) : null;
}

/** Deterministic 32-bit string hash (FNV-1a style, no Math.random anywhere). */
export function hashString(s: string): number {
  let h = 0x811c9dc5;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return h >>> 0;
}

/** Fill {service} / {client} placeholders. */
export function fill(template: string, service: string, client: string): string {
  return template.replaceAll("{service}", service).replaceAll("{client}", client);
}

/** Deterministic bank pick driven by the inputs. */
export function pick<T>(bank: readonly T[], seed: string): T {
  return bank[hashString(seed) % bank.length];
}

export function buildCopy(
  service: string,
  client: string,
  benefits: string[],
  steps: string[],
  priceAnchor: string,
  tone: Tone,
): string {
  const seed = `${service}|${client}|${tone}`;
  const headline = fill(pick(HEADLINES[tone], seed), service, client);
  const subhead = fill(pick(SUBHEADS, seed), service, client);
  const cta = pick(CTAS[tone], seed);

  const lines: string[] = [];
  lines.push(headline.toUpperCase(), "", subhead, "");
  lines.push("WHO THIS IS FOR", `This is for ${client} looking for ${service}.`, "");

  lines.push("WHAT YOU GET");
  if (benefits.length === 0) {
    lines.push("[Add your benefits above — they will appear here as bullet points.]");
  } else {
    for (const b of benefits) lines.push(`• ${b}`);
  }
  lines.push("");

  lines.push("HOW IT WORKS");
  if (steps.length === 0) {
    lines.push("[Add your process steps above — they will appear here as numbered steps.]");
  } else {
    steps.forEach((s, i) => lines.push(`${i + 1}. ${s}`));
  }
  lines.push("");

  if (priceAnchor !== "") {
    lines.push("INVESTMENT", `${priceAnchor} — shown exactly as you entered it.`, "");
  }

  lines.push("QUESTIONS, ANSWERED");
  for (const [q, a] of FAQ_STUB) {
    lines.push(`Q: ${q}`, `A: ${a}`, "");
  }

  lines.push(`${cta} — ${service} for ${client}.`);
  return lines.join("\n");
}

export function runTool(values: Record<string, unknown>): RunResult {
  if (!values || typeof values !== "object")
    return { ok: false, error: "No inputs were provided." };

  const serviceName = sanitize(values.serviceName, MAX_FIELD);
  if (serviceName === "") return { ok: false, error: "Service name is required." };

  const targetClient = sanitize(values.targetClient, MAX_FIELD);
  if (targetClient === "") return { ok: false, error: "Target client is required." };

  const toneRaw = sanitize(values.tone, 20);
  let tone = DEFAULT_TONE;
  if (toneRaw !== "") {
    const matched = matchTone(toneRaw);
    if (matched === null)
      return { ok: false, error: `Tone must be one of: ${TONES.join(", ")}.` };
    tone = matched;
  }

  const benefits = parseList(values.benefits);
  const processSteps = parseList(values.processSteps);
  const priceAnchor = sanitize(values.priceAnchor, MAX_FIELD);

  return {
    ok: true,
    values: { bookingPageCopy: buildCopy(serviceName, targetClient, benefits, processSteps, priceAnchor, tone) },
  };
}
