import type { ToolInput, ToolOutput } from '../../../src/lib/registry/types.ts';
import type { ToolContent } from '../../../src/templates/types.ts';

const TOOL_URL = 'https://husnainblogger.com/tools/instagram/pinned-post-strategy-planner/';

const GOAL_OPTIONS = [
  'Get more followers',
  'Drive sales',
  'Book more clients',
  'Build authority',
  'Promote a launch',
];

export const inputs: ToolInput[] = [
  {
    id: 'goal',
    label: 'Your goal for the pinned row',
    type: 'select',
    required: true,
    options: GOAL_OPTIONS,
  },
  {
    id: 'offers',
    label: 'Your offers (one per line, optional)',
    type: 'textarea',
    required: false,
    placeholder: '1:1 coaching program\nBrand audit',
  },
];

export const outputs: ToolOutput[] = [
  {
    id: 'pinnedPlan',
    label: 'Your 3-slot pinned plan',
    type: 'list',
    description:
    'Free what to pin on instagram 2026: What to put in slot 1, 2, and 3 — plus why the strategy works. Get instant results. free now.',
  },
  {
    id: 'copyAll',
    label: 'Copy full plan',
    type: 'copy',
    description:
    'The complete plan as text, ready to paste into your notes.',
  },
];

export const content: ToolContent = {
  title: 'Instagram Pinned Post Planner',
  description:
    "Decide what to pin on Instagram with this Instagram pinned post planner — what to put in slots 1, 2, and 3, plus why it works. Try it now!",
  howTo: [
    'Choose your "Your goal for the pinned row" — followers, sales, clients, authority, or a launch.',
    'Optionally list your offers in the "Your offers" box, one per line — your first offer is woven into the slot-3 pin.',
    'Run the tool to get your 3-slot plan: what each pin should do and concrete post ideas for it.',
    'Read the "Why this works" rationale so you understand the order.',
    'Open Instagram, tap the ••• on each chosen post, and pin them manually in slot order — the tool plans, you pin.',
  ],
  methodology:
    'This planner holds 5 fixed goal strategies, each with 3 fixed slot templates (15 slot templates total) and a fixed rationale explaining the order. It selects the strategy matching your goal and, when you list offers, inserts your first offer into the slot-3 pin. Nothing is generated by AI — every recommendation comes from the fixed strategy bank. The tool cannot pin posts for you: Instagram offers no public pinning API, so pinning stays a manual step.',
  examples: [
    {
      title: 'Sales goal with an offer',
      inputs: { goal: 'Drive sales', offers: '1:1 coaching program' },
      note: 'A 3-pin sales funnel: offer intro, proof post, and a CTA pin featuring the coaching program.',
    },
    {
      title: 'Follower growth',
      inputs: { goal: 'Get more followers', offers: '' },
      note: 'Intro post, best-performing post, and a follow-for promise pin — no offer needed.',
    },
    {
      title: 'Launch push',
      inputs: { goal: 'Promote a launch', offers: 'Email masterclass' },
      note: 'Announcement, behind-the-scenes, and urgency pins built around the masterclass launch.',
    },
  ],
  faqs: [
    {
      question: 'What is the best what to pin on instagram?',
      answer:
        'The best pinned row matches your goal: for followers, pin an intro, your best post, and a follow-promise; for sales, pin the offer intro, proof, and a buy CTA; for clients, pin who-you-help, a testimonial, and a booking CTA. This planner builds the exact row for five common goals.',
    },
    {
      question: 'Is there a free what to pin on instagram?',
      answer:
        'Yes — this Pinned Post Strategy Planner is completely free with no signup. Pick your goal, optionally add your offers, and get a 3-slot strategy with post ideas and the reasoning behind it.',
    },
    {
      question: 'How to use what to pin on instagram?',
      answer:
        'Select the goal your pinned row should serve and list your offers (optional). Run the tool, read the 3-slot plan and its rationale, then pin the matching posts yourself in the Instagram app under ••• → "Pin to your profile".',
    },
    {
      question: 'How does a what to pin on instagram work?',
      answer:
        'Instagram gives you 3 pinned slots at the top of your grid. This tool picks a fixed 3-slot strategy for your goal — what each pin should accomplish, with post ideas — and weaves your first offer into the final pin. It plans the strategy only; pinning itself is manual because Instagram has no pinning API.',
    },
    {
      question: 'What is a what to pin on instagram?',
      answer:
        'A what to pin on instagram is a free online tool that gives you quick, accurate results without spreadsheets or manual math. This version runs entirely in your browser for instant, private results.',
    },
      {
      question: 'How do I plan instagram pinned post planner?',
      answer: 'Start by entering your goals and constraints above. The planner organizes everything into a step-by-step plan you can follow or share with your team.',
    },
    {
      question: 'What should I include in my instagram pinned post planner plan?',
      answer: 'Cover your objectives, timeline, resources needed, and success metrics. This tool prompts you for each element so nothing gets missed.',
    },
  ],
  assumptions: [
    'The tool plans your pinned-post strategy — it cannot pin posts for you (no API exists for pinning).',
    'Strategies are fixed per goal, not AI-generated; adapt the post ideas to your niche and voice.',
    'Your first listed offer is used in the slot-3 pin; later offers appear only in the copied full plan.',
    'Pin order matters: use slot 1 → 3 as shown, left to right.',
  ],
  jsonLd: [],
};
