/**
 * Video Series Planner (tool-122) — pure logic, zero imports, zero network,
 * zero DOM, no Math.random, no Date.now().
 *
 * DATE MATH + FIXED ARC TEMPLATE, NOT AI: given a series title, episode
 * count, publishing cadence, and a start date, this module computes a dated
 * episode calendar and assigns every episode one of three fixed arc phases:
 *   episode 1        -> "Intro"   (series premiere slot)
 *   episodes 2..N-1  -> "Deep dive" (one working-title slot per episode)
 *   episode N        -> "Finale"  (wrap-up slot)
 * Working titles are fixed template strings with a "[your topic]" slot the
 * creator fills in — nothing is generated by a language model.
 *
 * Cadence steps (documented, fixed):
 *   daily         = +1 day
 *   twice-weekly  = +3 days
 *   weekly        = +7 days
 *   biweekly      = +14 days
 *   monthly       = +1 calendar month (same calendar day; Jan 31 -> Feb 28)
 *
 * All date arithmetic is done in UTC so results never shift with the
 * viewer's timezone. Deterministic: same inputs -> same calendar, always.
 */

/** Allowed cadences, in canonical order. */
export const CADENCES = [
  "daily",
  "twice-weekly",
  "weekly",
  "biweekly",
  "monthly",
] as const;

export type Cadence = (typeof CADENCES)[number];

/** Minimum / maximum episode count (from the tool's validation rules). */
export const MIN_EPISODES = 2;
export const MAX_EPISODES = 52;

/** One row of the planned calendar. */
export interface SeriesEpisode {
  /** 1-based episode number. */
  episode: number;
  /** Planned publish date, YYYY-MM-DD. */
  date: string;
  /** Fixed arc phase: "Intro" | "Deep dive" | "Finale". */
  phase: "Intro" | "Deep dive" | "Finale";
  /** Fixed template working title with a fill-in slot. */
  workingTitle: string;
}

/** Structured result of the planner. */
export interface SeriesPlan {
  episodes: SeriesEpisode[];
  /** Planned date of the final episode, YYYY-MM-DD. */
  endDate: string;
  /** Total span of the series in days (end - start). */
  spanDays: number;
}

export interface RunToolResult {
  ok: boolean;
  values?: Record<string, unknown>;
  error?: string;
}

const DATE_RE = /^(\d{4})-(\d{2})-(\d{2})$/;

/** Parse a strict YYYY-MM-DD date; null when invalid (bad format or impossible date). */
export function parseStartDate(value: unknown): Date | null {
  if (typeof value !== "string") return null;
  const m = DATE_RE.exec(value.trim());
  if (!m) return null;
  const y = Number(m[1]);
  const mo = Number(m[2]);
  const d = Number(m[3]);
  if (mo < 1 || mo > 12 || d < 1 || d > 31) return null;
  const dt = new Date(Date.UTC(y, mo - 1, d));
  // Guard impossible dates such as 2026-02-30 (Date rolls over silently).
  if (
    dt.getUTCFullYear() !== y ||
    dt.getUTCMonth() !== mo - 1 ||
    dt.getUTCDate() !== d
  ) {
    return null;
  }
  return dt;
}

/** Format a Date as YYYY-MM-DD (UTC). */
export function formatDateUTC(dt: Date): string {
  const y = dt.getUTCFullYear();
  const m = String(dt.getUTCMonth() + 1).padStart(2, "0");
  const d = String(dt.getUTCDate()).padStart(2, "0");
  return `${y}-${m}-${d}`;
}

/** Step forward one cadence tick from `dt`, returning a new Date. */
function stepDate(dt: Date, cadence: Cadence): Date {
  const next = new Date(dt.getTime());
  if (cadence === "monthly") {
    // Calendar-month stepping with clamping: Jan 31 -> Feb 28 (never rolls
    // into March the way naive setUTCMonth does).
    const day = next.getUTCDate();
    next.setUTCDate(1);
    next.setUTCMonth(next.getUTCMonth() + 1);
    const daysInMonth = new Date(
      Date.UTC(next.getUTCFullYear(), next.getUTCMonth() + 1, 0),
    ).getUTCDate();
    next.setUTCDate(Math.min(day, daysInMonth));
    return next;
  }
  const days =
    cadence === "daily"
      ? 1
      : cadence === "twice-weekly"
        ? 3
        : cadence === "weekly"
          ? 7
          : 14; // biweekly
  next.setUTCDate(next.getUTCDate() + days);
  return next;
}

/**
 * Build the episode calendar. Assumes validated inputs.
 * Exported so the schedule math is unit-testable without runTool.
 */
export function buildSeriesPlan(
  seriesTitle: string,
  episodeCount: number,
  cadence: Cadence,
  start: Date,
): SeriesPlan {
  const episodes: SeriesEpisode[] = [];
  let current = new Date(start.getTime());
  for (let i = 1; i <= episodeCount; i++) {
    const isFirst = i === 1;
    const isLast = i === episodeCount;
    const phase: SeriesEpisode["phase"] = isFirst
      ? "Intro"
      : isLast
        ? "Finale"
        : "Deep dive";
    const workingTitle = isFirst
      ? `EP1 Premiere — Introduce the "${seriesTitle}" series and what's coming`
      : isLast
        ? `EP${episodeCount} Finale — Wrap up "${seriesTitle}" + what's next`
        : `EP${i} — Deep dive #${i - 1}: [your topic here]`;
    episodes.push({
      episode: i,
      date: formatDateUTC(current),
      phase,
      workingTitle,
    });
    current = stepDate(current, cadence);
  }
  const endDate = episodes[episodes.length - 1].date;
  const spanDays = Math.round(
    (new Date(endDate + "T00:00:00Z").getTime() -
      new Date(formatDateUTC(start) + "T00:00:00Z").getTime()) /
      86400000,
  );
  return { episodes, endDate, spanDays };
}

/**
 * runTool — planner dispatch shape.
 * values in:  { seriesTitle, episodeCount, cadence, startDate }
 * values out: { schedule, summary, endDate }
 */
export function runTool(values: Record<string, unknown>): RunToolResult {
  const rawTitle = values["seriesTitle"];
  const title =
    typeof rawTitle === "string" ? rawTitle.trim() : "";
  if (!title) {
    return { ok: false, error: "Enter a series title (e.g. \"30-day drawing challenge\")." };
  }

  const rawCount = values["episodeCount"];
  const count =
    typeof rawCount === "number"
      ? rawCount
      : typeof rawCount === "string" && rawCount.trim() !== ""
        ? Number(rawCount.trim())
        : NaN;
  if (!Number.isInteger(count) || count < MIN_EPISODES || count > MAX_EPISODES) {
    return {
      ok: false,
      error: `Episode count must be a whole number between ${MIN_EPISODES} and ${MAX_EPISODES}.`,
    };
  }

  const rawCadence = values["cadence"];
  const cadence = typeof rawCadence === "string" ? rawCadence.trim().toLowerCase() : "";
  if (!(CADENCES as readonly string[]).includes(cadence)) {
    return {
      ok: false,
      error: `Pick a cadence: ${CADENCES.join(", ")}.`,
    };
  }

  const start = parseStartDate(values["startDate"]);
  if (!start) {
    return {
      ok: false,
      error: "Enter a valid start date (YYYY-MM-DD), e.g. 2026-11-02.",
    };
  }

  const plan = buildSeriesPlan(title, count, cadence as Cadence, start);
  const deepDives = plan.episodes.filter((e) => e.phase === "Deep dive").length;
  const summary =
    `${count}-episode "${title}" series · ${cadence} · ` +
    `${plan.episodes[0].date} → ${plan.endDate} (${plan.spanDays} days). ` +
    `Arc: 1 intro · ${deepDives} deep dive${deepDives === 1 ? "" : "s"} · 1 finale.`;

  return {
    ok: true,
    values: {
      schedule: plan.episodes,
      summary,
      endDate: plan.endDate,
    },
  };
}
