/**
 * Review Schema Generator — pure logic (zero imports, zero network, zero DOM).
 *
 * Builds a valid schema.org Review JSON-LD block from user-supplied review data.
 *
 * Honesty contract (from spec honestyNote):
 * - This tool only FORMATS the user's own review data into schema.org
 *   Review JSON-LD. Nothing is generated by AI; no review text or rating
 *   is invented.
 * - The user is responsible for the review being genuine. Google prohibits
 *   self-serving review markup (e.g. marking up reviews of your own
 *   business or employer), and this tool cannot verify authenticity —
 *   see assumptions in meta.ts.
 * - Deterministic: same inputs always produce the same JSON-LD.
 */

export interface ReviewSchemaRunValues {
  jsonLd: string;
  errors: string[];
}

export interface RunToolResult {
  ok: boolean;
  values?: Record<string, unknown>;
  error?: string;
}

export const MAX_ITEM_NAME_CHARS = 200;
export const MAX_AUTHOR_CHARS = 100;
export const MAX_REVIEW_BODY_CHARS = 5000;
export const DEFAULT_BEST_RATING = 5;

/** Coerce a number input (number or numeric string) — NaN when not numeric. */
function toFiniteNumber(raw: unknown): number {
  if (typeof raw === "number") return raw;
  if (typeof raw === "string" && raw.trim() !== "") {
    const n = Number(raw.trim());
    return n;
  }
  return NaN;
}

/**
 * Tool-logic slot. Values keys: itemName, author, ratingValue, bestRating?,
 * reviewBody?. Returns values: { jsonLd, errors } (match meta.ts ids).
 * Rating 0 is allowed and rendered; a missing review body is a warning.
 */
export function runTool(values: Record<string, unknown>): RunToolResult {
  if (!values || typeof values !== "object") {
    return { ok: false, error: "Please enter your review details first." };
  }

  const itemName =
    typeof values["itemName"] === "string" ? values["itemName"].trim() : "";
  const author =
    typeof values["author"] === "string" ? values["author"].trim() : "";
  const bodyRaw = values["reviewBody"];
  const reviewBody = typeof bodyRaw === "string" ? bodyRaw.trim() : "";

  if (itemName.length === 0) {
    return { ok: false, error: "Please enter the name of the item being reviewed." };
  }
  if (itemName.length > MAX_ITEM_NAME_CHARS) {
    return {
      ok: false,
      error: `Item name is ${itemName.length} characters (max ${MAX_ITEM_NAME_CHARS}).`,
    };
  }
  if (author.length === 0) {
    return { ok: false, error: "Please enter the reviewer name." };
  }
  if (author.length > MAX_AUTHOR_CHARS) {
    return {
      ok: false,
      error: `Reviewer name is ${author.length} characters (max ${MAX_AUTHOR_CHARS}).`,
    };
  }

  const bestRating = values["bestRating"] === undefined ? DEFAULT_BEST_RATING : toFiniteNumber(values["bestRating"]);
  if (!Number.isFinite(bestRating) || bestRating <= 0) {
    return {
      ok: false,
      error: "Best rating must be a number greater than 0 (default 5).",
    };
  }

  const ratingValue = values["ratingValue"] === undefined ? NaN : toFiniteNumber(values["ratingValue"]);
  if (!Number.isFinite(ratingValue)) {
    return { ok: false, error: "Please enter a numeric rating." };
  }
  if (ratingValue < 0 || ratingValue > bestRating) {
    return {
      ok: false,
      error: `Rating must be between 0 and ${bestRating}.`,
    };
  }

  if (reviewBody.length > MAX_REVIEW_BODY_CHARS) {
    return {
      ok: false,
      error: `Review text is ${reviewBody.length} characters (max ${MAX_REVIEW_BODY_CHARS}).`,
    };
  }

  const errors: string[] = [];
  if (reviewBody === "") {
    errors.push(
      "Note: no review text was entered. Markup is still valid, but reviews with written text are more useful to readers and search engines."
    );
  }

  const review: Record<string, unknown> = {
    "@context": "https://schema.org",
    "@type": "Review",
    itemReviewed: { "@type": "Thing", name: itemName },
    author: { "@type": "Person", name: author },
    reviewRating: {
      "@type": "Rating",
      ratingValue,
      bestRating,
    },
  };
  if (reviewBody !== "") review["reviewBody"] = reviewBody;

  const out: ReviewSchemaRunValues = {
    jsonLd: JSON.stringify(review, null, 2),
    errors,
  };
  return { ok: true, values: out as unknown as Record<string, unknown> };
}
