import type { ToolInput, ToolOutput } from '../../../src/lib/registry/types.ts';
import type { ToolContent } from '../../../src/templates/types.ts';

const TOOL_URL = 'https://husnainblogger.com/tools/blogging-seo/review-schema-generator/';

export const inputs: ToolInput[] = [
  {
    id: 'itemName',
    label: 'Item being reviewed',
    type: 'text',
    required: true,
    placeholder: 'Acme Pour-Over Dripper',
  },
  {
    id: 'author',
    label: 'Reviewer name',
    type: 'text',
    required: true,
    placeholder: 'Jane Doe',
  },
  {
    id: 'ratingValue',
    label: 'Rating',
    type: 'number',
    required: true,
    placeholder: '4.5',
    validation: { min: 0 },
  },
  {
    id: 'bestRating',
    label: 'Best rating (optional)',
    type: 'number',
    required: false,
    placeholder: '5',
    validation: { min: 1 },
  },
  {
    id: 'reviewBody',
    label: 'Review text (optional)',
    type: 'textarea',
    required: false,
    placeholder: 'What did you like or dislike about it?',
  },
];

export const outputs: ToolOutput[] = [
  {
    id: 'jsonLd',
    label: 'JSON-LD markup (copy)',
    type: 'copy',
    description:
    'Valid schema.org Review JSON-LD — paste it into your review page.',
  keywords: ['review rating schema generator', 'review schema markup generator'],
  },
  {
    id: 'errors',
    label: 'Validation notes',
    type: 'list',
    description:
    'Warnings about the input (e.g. missing review text).',
  },
];

export const content: ToolContent = {
  title: 'Review Schema Generator – Free JSON-LD',
  description:
    'Free review schema generator 2026: build valid JSON-LD review markup with item, author and rating for rich snippets. — copy your code today.',
  howTo: [
    'Enter the "Item being reviewed" and the "Reviewer name" (both required).',
    'Set the "Rating" (0 up to the best rating) and optionally change "Best rating" if your scale is not 5.',
    'Optionally paste your "Review text" — written reviews are more useful to readers and search engines.',
    'Run the tool and check "Validation notes" for warnings.',
    'Copy the "JSON-LD markup" into your review page, then test it in Google\'s Rich Results Test.',
  ],
  methodology:
    'This tool formats your review data into a valid schema.org Review JSON-LD block: the item as a Thing, the reviewer as a Person, and the score as a Rating with ratingValue and bestRating (default 5). The rating must be numeric and fall between 0 and the best rating — a 0 rating is allowed and rendered. Nothing is generated by AI; no review text or score is invented, and the tool cannot verify that a review is genuine.',
  examples: [
    {
      title: 'Product review with text',
      inputs: {
        itemName: 'Acme Pour-Over Dripper',
        author: 'Jane Doe',
        ratingValue: 4.5,
        reviewBody: 'Excellent build quality and a clean cup. Highly recommended.',
      },
      note: 'Full review producing a complete Review block with reviewBody.',
    },
    {
      title: 'Rating only, 10-point scale',
      inputs: {
        itemName: 'Acme Grinder',
        author: 'Jane Doe',
        ratingValue: 8,
        bestRating: 10,
      },
      note: 'No review text — markup is still valid, and Validation notes say so.',
    },
    {
      title: 'Zero-star review',
      inputs: {
        itemName: 'Broken Kettle',
        author: 'John Smith',
        ratingValue: 0,
      },
      note: 'A 0 rating is allowed and rendered as ratingValue 0.',
    },
  ],
  faqs: [
    {
      question: 'What is the best review schema generator?',
      answer:
        'The best review schema generator builds valid schema.org Review JSON-LD with the item, reviewer, and a correctly scaled rating, and needs no signup. This tool does that — enter your review details, copy the markup, and test it in Google\'s Rich Results Test.',
    },
    {
      question: 'Is there a free review schema generator?',
      answer:
        'Yes — this review schema generator is completely free with no signup. Enter the item, reviewer, rating, and optional review text, then copy the ready-to-paste JSON-LD.',
    },
    {
      question: 'How to generate review schema?',
      answer:
        'Enter the reviewed item, the reviewer name, and a rating between 0 and your best rating (5 by default), add your review text if you have it, then copy the generated JSON-LD into your review page. Only mark up genuine reviews — Google prohibits self-serving review markup.',
    },
    {
      question: 'How does a review schema generator work?',
      answer:
        'It takes your review data and assembles it into a schema.org Review JSON-LD block with the item, author, and rating fields. Nothing is written by AI — the tool only formats the review you provide into valid markup.',
    },
    {
      question: 'How do I add review schema to a WordPress page?',
      answer:
        'Copy the JSON-LD markup the tool gives you and paste it into your review page\'s HTML. In WordPress you can add it through a Custom HTML block, a schema or SEO plugin, or your theme\'s header section — then verify it with Google\'s Rich Results Test.',
    },
    {
      question: 'What rating scale does the review schema generator support?',
      answer:
        'The best rating defaults to 5 but you can set any scale, for example 10 for a ten-point review. Your rating must be a number between 0 and your best rating — a 0 rating is allowed and rendered as ratingValue 0.',
    },
    {
      question: 'Will review schema guarantee star ratings in Google search?',
      answer:
        'No — emitting Review markup does not guarantee star ratings in search results; Google decides eligibility itself. Also remember to mark up only genuine reviews: Google prohibits self-serving review markup, such as marking up reviews of your own business.',
    },
  ],
  assumptions: [
    'Only mark up genuine reviews — Google prohibits self-serving review markup (for example, marking up reviews of your own business), and this tool cannot verify authenticity.',
    'The rating scale is whatever you set as Best rating (default 5); the rating must be a number between 0 and that value.',
    'Emitting Review markup does not guarantee star ratings in search results — Google decides eligibility.',
  ],
  jsonLd: [],
};
