import type { ToolInput, ToolOutput } from '../../../src/lib/registry/types.ts';
import type { ToolContent } from '../../../src/templates/types.ts';
import { TRACKER_ITEMS } from './logic.ts';

export const inputs: ToolInput[] = [];

export const outputs: ToolOutput[] = [];

export const trackerMode: 'checklist' | 'library' = 'library';

export const trackerItems = TRACKER_ITEMS;

export const content: ToolContent = {
  title: 'AI Prompts for Blogging',
  description:
    'Browse a free library of AI prompts for blogging: 48 human-written templates for ideas, outlines, drafts, and SEO. Copy any prompt and start writing today.',
  howTo: [
    'Browse the 8 categories: ideas, outlining, drafting, headlines, SEO, editing, repurposing, and promotion.',
    'Click any prompt to see its full text with placeholders like [TOPIC] highlighted.',
    'Replace the placeholders with your own topic, keyword, or draft text.',
    'Copy the finished prompt and paste it into your own AI tool (ChatGPT, Claude, Gemini, etc.).',
    'Mark prompts you have tried so you can track which ones work best for your blog.',
  ],
  methodology:
    'This is a fixed, curated library of 48 human-written prompt templates in 8 categories. Nothing is generated by an AI model at runtime — the page simply displays the templates, and you run them in your own AI tool.',
  faqs: [
    {
      question: 'What is the best AI prompts for blogging?',
      answer:
        'The best prompts are specific ones that name your topic, audience, tone, and desired format. This library gives you 48 human-written templates covering ideas, outlines, drafts, SEO, and repurposing — pick the category you need and fill in the placeholders.',
    },
    {
      question: 'Is there a free AI prompts for blogging?',
      answer:
        'Yes — this entire library of 48 prompt templates is free to browse and copy. You paste the prompts into your own AI tool, so there is no cost on this site.',
    },
    {
      question: 'How to use AI prompts for blogging?',
      answer:
        'Choose a template from the category you need, replace placeholders like [TOPIC] or [KEYWORD] with your details, copy the finished prompt, and paste it into your AI tool of choice. Review and edit the output before publishing — AI drafts always need a human pass.',
    },
    {
      question: 'How does an AI prompts for blogging work?',
      answer:
        'A prompt is the instruction you give an AI tool. This library does not run any AI itself — it is a fixed collection of ready-made instructions you copy, customize, and run in tools like ChatGPT, Claude, or Gemini.',
    },
    {
      question: 'What is an ai prompts for blogging?',
      answer:
        'An ai prompts for blogging is a free online tool that gives you quick, accurate results without spreadsheets or manual math. This version runs entirely in your browser for instant, private results.',
    },
  ],
  assumptions: [
    'Fixed library of 48 human-written templates — nothing is generated or personalized at runtime.',
    'Templates use placeholders (e.g. [TOPIC]); you fill them in before use.',
    'You need your own AI tool account to run the copied prompts.',
    'Prompts are general-purpose blogging guidance, not niche-specific advice.',
  ],
  jsonLd: [
    {
      '@type': 'WebPage',
      name: 'AI Prompts for Blogging 2026',
      url: 'https://husnainblogger.com/tools/ai-workflows/ai-prompt-library-for-bloggers/',
      description:
    'Browse a free library of AI prompts for blogging: 48 human-written templates for ideas, outlines, drafts, and SEO. Copy any prompt and start writing today.',
    },
  ],
};
