/**
 * Pinterest Fresh Pin Checklist — pure logic (tool-362). Zero imports,
 * zero network, zero DOM.
 *
 * WHAT THIS IS: a static checklist assembled from a curated
 * best-practice bank — 3 pin-type banks (standard, idea, video),
 * 8 checklist items each, for a total of 24 hand-written items.
 * Nothing is generated by AI and no Pinterest data is read.
 *
 * HONESTY: "freshness" here is framed as creator best practice
 * (new creative per URL, unique titles/descriptions, correct ratio,
 * keyword coverage). The tool does NOT claim to know Pinterest's
 * internal freshness detection — a disclaimer is returned with every
 * run, and the spec edge case ("user expects guaranteed distribution
 * boost") is answered by that disclaimer.
 *
 * Deterministic: same inputs -> same outputs.
 */

export type PinType = "standard" | "idea" | "video";

/** Supported pin types, in canonical order. */
export const PIN_TYPES: PinType[] = ["standard", "idea", "video"];

export interface ChecklistItem {
  item: string;
  why: string;
}

/**
 * The curated best-practice bank.
 * 3 banks x 8 items = 24 items total.
 */
export const CHECKLIST_BANK: Record<PinType, ChecklistItem[]> = {
  standard: [
    {
      item: "Use a brand-new image — not a reused creative",
      why: "Re-uploading the exact same image for a URL is the most common way pins get treated as duplicates.",
    },
    {
      item: "Give the pin a unique title for this URL",
      why: "A fresh, keyword-rich title helps the pin stand apart from older pins pointing at the same page.",
    },
    {
      item: "Write a unique description (don't copy-paste)",
      why: "Duplicate descriptions across pins are a signal the creative isn't new; rewrite in your own words.",
    },
    {
      item: "Use the 2:3 ratio (e.g. 1000 x 1500 px)",
      why: "Tall 2:3 pins take the most feed space and display fully without cropping.",
    },
    {
      item: "Cover your target keywords in title, description, and on-image text",
      why: "Pinterest is a search engine — keywords are what connect a new pin to searchers.",
    },
    {
      item: "Change the layout, colors, or photo — not just the text",
      why: "Swapping only the headline text on an identical background still reads as the same creative.",
    },
    {
      item: "Link to the exact page the pin promises",
      why: "Mismatched destinations erode trust and can get the pin flagged, no matter how fresh the image is.",
    },
    {
      item: "Check the pin isn't already saved to your boards",
      why: "Saving the same image to many of your own boards first is an easy way to dilute a fresh pin.",
    },
  ],
  idea: [
    {
      item: "Build the idea pin from new clips or pages",
      why: "Idea pins are multi-page stories — reusing old story pages makes the whole pin feel recycled.",
    },
    {
      item: "Give every page its own on-screen headline",
      why: "Distinct headlines per page keep viewers swiping and make each page indexable for search.",
    },
    {
      item: "Record fresh voiceover or text overlay (don't reuse audio verbatim)",
      why: "Reused audio across idea pins is one of the easiest duplicates for viewers — and systems — to spot.",
    },
    {
      item: "Design a unique cover page in 9:16",
      why: "The cover is the thumbnail in feeds; a new cover is what makes the pin look new at first glance.",
    },
    {
      item: "Write a keyword-rich idea pin title and notes",
      why: "Idea pins surface in search through their title and notes, so fresh copy matters as much as fresh visuals.",
    },
    {
      item: "Keep it 5+ pages or 30+ seconds where it fits the topic",
      why: "Longer, structured stories get more watch time, which is the main signal for idea pins.",
    },
    {
      item: "Add topic tags from Pinterest's suggested list",
      why: "Suggested topic tags are the platform's own categorization — they help a new pin find its audience.",
    },
    {
      item: "End with a clear next step (save, follow, or visit the linked topic)",
      why: "A call to action converts views into saves, which is the engagement that matters most on Pinterest.",
    },
  ],
  video: [
    {
      item: "Upload a newly edited video — not a re-export of an old one",
      why: "Re-exporting identical footage is the video equivalent of reusing a static creative.",
    },
    {
      item: "Open with a new hook in the first 2 seconds",
      why: "The hook is what stops the scroll; a recycled opening makes the pin feel like a repost.",
    },
    {
      item: "Burn in captions or on-screen text unique to this pin",
      why: "Fresh captions make the video accessible and give each upload its own searchable text layer.",
    },
    {
      item: "Use vertical 9:16 framing (or 2:3 minimum)",
      why: "Vertical video fills the mobile feed; horizontal or square video is shown small.",
    },
    {
      item: "Write a unique title and description with keywords",
      why: "Video pins are discovered through search too — don't paste the same description across uploads.",
    },
    {
      item: "Trim the length to the point — cut filler from older edits",
      why: "A tighter re-edit keeps retention high; retention is the main quality signal for video pins.",
    },
    {
      item: "Change the thumbnail/cover frame",
      why: "Viewers judge a video pin by its cover frame before pressing play — a new frame means a new first impression.",
    },
    {
      item: "Link the video to the page it actually demonstrates",
      why: "A fresh video pointing at a mismatched page still fails the viewer's expectation.",
    },
  ],
};

/** Total items across all banks (documented for the honesty contract). */
export const TOTAL_CHECKLIST_ITEMS = 24;

/** Returned with every run — answers the spec edge case about guaranteed boosts. */
export const FRESHNESS_DISCLAIMER =
  "This checklist reflects creator best practice for making pins that look and read as new. " +
  "It does not describe Pinterest's internal freshness detection, and following it does not " +
  "guarantee a distribution boost — only Pinterest's systems decide how a pin is distributed.";

export interface FreshPinChecklistValues {
  ok: boolean;
  values?: {
    checklist: { columns: string[]; rows: string[][] };
    itemCount: number;
    pinTypeUsed: string;
    disclaimer: string;
  };
  error?: string;
}

export function runTool(values: Record<string, unknown>): FreshPinChecklistValues {
  let pinType: PinType = "standard"; // default per spec
  const raw = values["pinType"];
  if (typeof raw === "string" && raw.trim().length > 0) {
    const t = raw.trim().toLowerCase();
    if (t === "standard" || t === "idea" || t === "video") {
      pinType = t;
    } else {
      return { ok: false, error: "Pin type must be 'standard', 'idea', or 'video'." };
    }
  }

  const items = CHECKLIST_BANK[pinType];
  const rows = items.map((it) => [it.item, it.why]);
  const labels: Record<PinType, string> = {
    standard: "Standard pin",
    idea: "Idea pin",
    video: "Video pin",
  };

  return {
    ok: true,
    values: {
      checklist: { columns: ["Checklist item", "Why it matters"], rows },
      itemCount: items.length,
      pinTypeUsed: labels[pinType],
      disclaimer: FRESHNESS_DISCLAIMER,
    },
  };
}
