import type { ToolInput, ToolOutput } from '../../../src/lib/registry/types.ts';
import type { ToolContent } from '../../../src/templates/types.ts';

const TOOL_URL = 'https://husnainblogger.com/tools/instagram/story-highlight-name-generator/';

export const inputs: ToolInput[] = [
  {
    id: 'niche',
    label: 'Your niche',
    type: 'text',
    required: true,
    placeholder: 'e.g. fitness, bakeries, travel',
  },
  {
    id: 'tone',
    label: 'Tone',
    type: 'select',
    required: true,
    options: ['playful', 'professional', 'minimal', 'bold'],
  },
  {
    id: 'count',
    label: 'How many names',
    type: 'number',
    required: true,
    validation: { min: 1, max: 20 },
  },
];

export const outputs: ToolOutput[] = [
  {
    id: 'names',
    label: 'Highlight names',
    type: 'list',
    description:
    'Free instagram highlight names ideas 2026: Short highlight titles built from fixed name patterns — no AI involved. Fast, private now.',
  },
  {
    id: 'note',
    label: 'Usage note',
    type: 'text',
    description:
    'Tone confirmation, truncation guidance, and flags for names over 15 characters.',
  },
];

export const content: ToolContent = {
  title: 'Instagram Highlight Names Ideas',
  description:
    'Generate Instagram story highlight name ideas free. Enter your niche, pick a tone, and get short on-brand highlight titles with length warnings. Get.',
  howTo: [
    'Type your niche in the "Your niche" box (e.g. "fitness", "bakeries").',
    'Pick a tone: playful, professional, minimal, or bold.',
    'Choose how many names you want (1–20) and run the tool.',
    'Copy your favorites — prefer the shortest ones, since Instagram truncates highlight names around 10–11 characters.',
    'Check the usage note: any name over 15 characters is flagged as likely to be cut off.',
  ],
  methodology:
    'This tool assembles names from a fixed bank of 48 hand-written name patterns — nothing is generated by AI. Each pattern suits exactly 2 of the 4 tones, giving every tone a pool of 24 patterns. Selection is deterministic: a hash of your niche picks the start offset, then patterns are taken in bank order with no repeats (pools hold 24, max count is 20). Your niche is inserted verbatim into the {niche} slot. Names longer than 15 characters are flagged in the output note.',
  examples: [
    {
      title: 'Playful names for a bakery',
      inputs: { niche: 'bakeries', tone: 'playful', count: 5 },
      note: 'Short playful titles like "bakeries 101" and "Daily bakeries".',
    },
    {
      title: 'Minimal names for travel',
      inputs: { niche: 'travel', tone: 'minimal', count: 4 },
      note: 'Clean minimal titles; the plain-niche pattern stays very short.',
    },
    {
      title: 'Professional names for fitness',
      inputs: { niche: 'fitness', tone: 'professional', count: 6 },
      note: 'Authority-style titles such as "fitness Guide" and "fitness Playbook".',
    },
  ],
  faqs: [
    {
      question: 'What is the best Instagram highlight names ideas?',
      answer:
        'The best Instagram highlight names are short (Instagram truncates around 10–11 characters), match your profile\'s tone, and say what\'s inside at a glance. This tool generates tone-matched ideas free — pick the shortest ones that still describe the content.',
    },
    {
      question: 'Is there a free Instagram highlight names ideas?',
      answer:
        'Yes — this highlight name generator is completely free with no signup. Enter your niche, pick a tone, and generate up to 20 names in one click.',
    },
    {
      question: 'How to use Instagram highlight?',
      answer:
        'Post stories as usual, then tap the heart icon to save them into a highlight, give the highlight a short clear name, and add a cover. Keep highlights to 5–10 so your profile stays scannable, and refresh stale ones monthly.',
    },
    {
      question: 'How does an Instagram highlight names ideas work?',
      answer:
        'It combines your niche with fixed name patterns in your chosen tone — for example "fitness 101" or "About fitness". This tool picks patterns deterministically from a hand-written bank of 48, never AI-generated, and flags any name over 15 characters that Instagram would truncate.',
    },
    {
      question: 'How does the instagram highlight names ideas work?',
      answer:
        'Enter your details using the inputs above and the instagram highlight names ideas calculates everything instantly in your browser. No data leaves your device, and you get results the moment you change any value.',
    },
    {
      question: 'Is the instagram highlight names ideas free to use?',
      answer:
        'Yes - this instagram highlight names ideas is completely free with no signup, no account, and no usage limits. It runs 100% in your browser.',
    },
    {
      question: 'What is an instagram highlight names ideas?',
      answer:
        'An instagram highlight names ideas is a free online tool that gives you quick, accurate results without spreadsheets or manual math. This version runs entirely in your browser for instant, private results.',
    },
  ],
  assumptions: [
    'Instagram truncates highlight names around 10–11 characters — the tool flags names over 15 characters but display width varies by device and font.',
    'Names come from 48 fixed patterns (24 per tone pool); they are starting points, not AI-written copy.',
    'Selection is deterministic per niche — the same inputs always return the same names.',
  ],
  jsonLd: [],
};
