import type { ToolInput, ToolOutput } from '../../../src/lib/registry/types.ts';
import type { ToolContent } from '../../../src/templates/types.ts';

const TOOL_URL = 'https://husnainblogger.com/tools/instagram/carousel-slide-outline-generator/';

export const inputs: ToolInput[] = [
  {
    id: 'topic',
    label: 'Carousel topic',
    type: 'text',
    required: true,
    placeholder: 'e.g. email marketing, sourdough baking',
  },
  {
    id: 'slideCount',
    label: 'Number of slides',
    type: 'number',
    required: true,
    validation: { min: 3, max: 20 },
  },
  {
    id: 'goal',
    label: 'Post goal',
    type: 'select',
    required: true,
    options: ['educate', 'sell', 'grow', 'engage'],
  },
];

export const outputs: ToolOutput[] = [
  {
    id: 'outline',
    label: 'Slide outline',
    type: 'table',
    description:
    'Free instagram carousel ideas generator 2026: Slide-by-slide outline: number, role (hook/value/proof/CTA), text, and visual note. Fast, private -.',
  },
  {
    id: 'copyAll',
    label: 'Copy full outline',
    type: 'copy',
    description:
    'The complete outline as plain text, ready to paste into your design tool or notes.',
  },
];

export const content: ToolContent = {
  title: 'Instagram Carousel Ideas Generator',
  description:
    'Generate Instagram carousel post ideas free. Enter a topic, pick a goal and slide count, and get a slide-by-slide outline with visual notes. Build it now.',
  howTo: [
    'Type your carousel topic in the "Carousel topic" box (e.g. "email marketing").',
    'Pick a post goal: educate, sell, grow, or engage — each goal uses its own slide formulas.',
    'Choose the number of slides (3–10; requests above 10 are clamped to 10 with a note).',
    'Run the tool to get a slide-by-slide outline: hook first, proof near the end, CTA last, with a visual note per slide.',
    'Copy the full outline and adapt the wording, examples, and CTA to your voice before designing.',
  ],
  methodology:
    'This tool assembles outlines from a fixed bank of 76 hand-written slide templates — 19 per goal (3 hooks, 10 value slides, 3 proof slides, 3 CTAs) — nothing is generated by AI. Selection is deterministic: a hash of your topic picks the hook, proof, and CTA and the start offset for the value slides, which cycle in bank order with no repeats. Slide 1 is always the hook and the last slide is always the CTA; with 4+ slides the second-to-last slide is a proof slide. Slide counts above 10 are clamped to 10 with a note, since 3–10 is the readable carousel range.',
  examples: [
    {
      title: 'Educate: 5-slide email marketing carousel',
      inputs: { topic: 'email marketing', slideCount: 5, goal: 'educate' },
      note: 'Hook, 2 value slides, proof, CTA — a complete teaching arc.',
    },
    {
      title: 'Sell: 4-slide offer carousel',
      inputs: { topic: 'fitness coaching', slideCount: 4, goal: 'sell' },
      note: 'Hook, value, proof, CTA — problem, offer, evidence, action.',
    },
    {
      title: 'Grow: 10-slide listicle',
      inputs: { topic: 'houseplants', slideCount: 10, goal: 'grow' },
      note: 'Maximum 10 slides: hook, 7 value tips, proof, CTA.',
    },
  ],
  faqs: [
    {
      question: 'What is the best Instagram carousel ideas generator?',
      answer:
        'The best Instagram carousel generator gives you a real slide-by-slide structure — hook, value, proof, CTA — not just a topic list. This tool is free: enter your topic, pick a goal, and get a complete outline with visual notes for every slide.',
    },
    {
      question: 'Is there a free Instagram carousel ideas generator?',
      answer:
        'Yes — this carousel slide outline generator is completely free with no signup. Generate outlines of 3–10 slides across 4 goals (educate, sell, grow, engage) and copy the full text in one click.',
    },
    {
      question: 'How to generate Instagram carousel?',
      answer:
        'Start with a topic and a goal, then outline slide 1 as the hook, middle slides as one idea each, a proof slide, and a final CTA. This tool does the outlining for you from 76 hand-written templates — your job is rewriting it in your voice and designing the slides.',
    },
    {
      question: 'How does the instagram carousel ideas generator work?',
      answer:
        'Enter your details using the inputs above and the instagram carousel ideas generator calculates everything instantly in your browser. No data leaves your device, and you get results the moment you change any value.',
    },
    {
      question: 'Is the instagram carousel ideas generator free to use?',
      answer:
        'Yes - this instagram carousel ideas generator is completely free with no signup, no account, and no usage limits. It runs 100% in your browser.',
    },
    {
      question: 'What is an instagram carousel ideas generator?',
      answer:
        'An instagram carousel ideas generator is a free online tool that gives you quick, accurate results without spreadsheets or manual math. This version runs entirely in your browser for instant, private results.',
    },
    {
      question: 'Do I need to create an account to use the instagram carousel ideas generator?',
      answer:
        'No account needed. Open the instagram carousel ideas generator, enter your values, and see results immediately - nothing is stored or sent anywhere.',
    },
  ],
  assumptions: [
    'Outlines come from 76 fixed templates (19 per goal) — they are starting structures, not AI-written copy; rewrite them in your voice.',
    'Slide counts above 10 are clamped to 10 with a note; 3–10 is treated as the readable carousel range.',
    'Value slides cycle in bank order when the slide count exceeds an angle\'s value bank.',
  ],
  jsonLd: [
    {
      '@type': 'SoftwareApplication',
      name: 'Instagram Carousel Ideas Generator 2026 | HusnainBlogger',
      url: TOOL_URL,
      applicationCategory: 'Utilities',
      operatingSystem: 'Web',
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      description:
    'Free instagram carousel ideas generator 2026: Slide-by-slide outline: number, role (hook/value/proof/CTA), text, and visual note. Fast, private -.',
    },
    {
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://husnainblogger.com/' },
        { '@type': 'ListItem', position: 2, name: 'Tools', item: 'https://husnainblogger.com/tools/' },
        {
          '@type': 'ListItem',
          position: 3,
          name: 'Instagram Tools',
          item: 'https://husnainblogger.com/tools/instagram/',
        },
        {
          '@type': 'ListItem',
          position: 4,
          name: 'Carousel Slide Outline Generator',
          item: TOOL_URL,
        },
      ],
    },
  ],
};
