/**
 * Breadcrumb Schema Generator — pure logic (zero imports, zero network, zero DOM).
 *
 * Builds a valid schema.org BreadcrumbList JSON-LD block with positions.
 *
 * Honesty contract (from spec honestyNote):
 * - This tool only FORMATS the user's own crumbs into schema.org
 *   BreadcrumbList JSON-LD. Nothing is generated by AI; no URLs are
 *   checked over the network.
 * - URLs must be absolute, or relative URLs are resolved against the
 *   optional Base URL. A relative URL with no Base URL is skipped and
 *   reported — the tool never guesses a domain.
 * - Deterministic: same inputs always produce the same JSON-LD.
 *
 * Input shape for runTool values["crumbs"]:
 *   - preferred: { name, url }[] (1–10 crumbs)
 *   - also accepted: a textarea string in the documented format —
 *     one crumb per line as:  Name ||| URL
 */

export interface CrumbInput {
  name: string;
  url: string;
}

export interface BreadcrumbSchemaRunValues {
  jsonLd: string;
  errors: string[];
}

export interface RunToolResult {
  ok: boolean;
  values?: Record<string, unknown>;
  error?: string;
}

export const MAX_CRUMBS = 10;
const CRUMB_SEPARATOR = "|||";

/** Pure absolute http(s) URL check — no network, no DOM. */
export function isAbsoluteHttpUrl(value: string): boolean {
  try {
    const u = new URL(value.trim());
    return u.protocol === "http:" || u.protocol === "https:";
  } catch {
    return false;
  }
}

/**
 * Resolve a crumb URL: absolute http(s) URLs pass through; relative URLs
 * resolve against baseUrl when given. Returns null when unresolvable.
 */
export function resolveCrumbUrl(rawUrl: string, baseUrl: string): string | null {
  const u = rawUrl.trim();
  if (u === "") return null;
  if (isAbsoluteHttpUrl(u)) return u;
  if (baseUrl === "") return null;
  try {
    const resolved = new URL(u, baseUrl);
    return resolved.protocol === "http:" || resolved.protocol === "https:"
      ? resolved.toString()
      : null;
  } catch {
    return null;
  }
}

/**
 * Parse the textarea format into crumbs: one crumb per line,
 * "Name ||| URL". Lines without the separator are ignored as notes.
 */
export function parseCrumbsText(text: string): CrumbInput[] {
  const crumbs: CrumbInput[] = [];
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (trimmed === "") continue;
    const sepIdx = trimmed.indexOf(CRUMB_SEPARATOR);
    if (sepIdx === -1) continue;
    const name = trimmed.slice(0, sepIdx).trim();
    const url = trimmed.slice(sepIdx + CRUMB_SEPARATOR.length).trim();
    crumbs.push({ name, url });
  }
  return crumbs;
}

/**
 * Tool-logic slot. Values keys: crumbs, baseUrl?.
 * Returns values: { jsonLd, errors } (match meta.ts ids).
 */
export function runTool(values: Record<string, unknown>): RunToolResult {
  if (!values || typeof values !== "object") {
    return { ok: false, error: "Please add your breadcrumb trail first." };
  }

  const baseRaw = values["baseUrl"];
  const baseUrl = typeof baseRaw === "string" ? baseRaw.trim() : "";
  if (baseUrl !== "" && !isAbsoluteHttpUrl(baseUrl)) {
    return {
      ok: false,
      error: "Base URL must be an absolute URL starting with http:// or https://.",
    };
  }

  const rawCrumbs = values["crumbs"];
  let crumbs: CrumbInput[];
  if (Array.isArray(rawCrumbs)) {
    crumbs = rawCrumbs as CrumbInput[];
  } else if (typeof rawCrumbs === "string") {
    crumbs = parseCrumbsText(rawCrumbs);
  } else {
    return { ok: false, error: "Please add at least one breadcrumb." };
  }

  if (crumbs.length === 0) {
    return { ok: false, error: "Please add at least one breadcrumb." };
  }
  if (crumbs.length > MAX_CRUMBS) {
    return {
      ok: false,
      error: `Too many breadcrumbs: ${crumbs.length} (max ${MAX_CRUMBS}). Keep the trail to 10 or fewer.`,
    };
  }

  const errors: string[] = [];
  const itemListElement: object[] = [];
  let position = 1;
  for (let i = 0; i < crumbs.length; i++) {
    const c = crumbs[i];
    const cName = c && typeof c.name === "string" ? c.name.trim() : "";
    const cUrl = c && typeof c.url === "string" ? c.url.trim() : "";
    if (cName === "") {
      return { ok: false, error: `Breadcrumb ${i + 1}: name is required.` };
    }
    const resolved = resolveCrumbUrl(cUrl, baseUrl);
    if (resolved === null) {
      if (cUrl === "") {
        errors.push(`Breadcrumb ${i + 1} ("${cName}"): no URL given — crumb skipped.`);
      } else if (baseUrl === "") {
        errors.push(
          `Breadcrumb ${i + 1} ("${cName}"): "${cUrl}" is relative and no Base URL was given — crumb skipped. Add a Base URL or use an absolute URL.`
        );
      } else {
        errors.push(`Breadcrumb ${i + 1} ("${cName}"): "${cUrl}" is not a valid URL — crumb skipped.`);
      }
      continue;
    }
    itemListElement.push({
      "@type": "ListItem",
      position: position++,
      name: cName,
      item: resolved,
    });
  }

  if (itemListElement.length === 0) {
    return {
      ok: false,
      error: errors[0] ?? "No valid breadcrumbs to emit.",
    };
  }

  const out: BreadcrumbSchemaRunValues = {
    jsonLd: JSON.stringify(
      {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        itemListElement,
      },
      null,
      2
    ),
    errors,
  };
  return { ok: true, values: out as unknown as Record<string, unknown> };
}
