import type { ToolInput, ToolOutput } from '../../../src/lib/registry/types.ts';
import type { ToolContent } from '../../../src/templates/types.ts';

const TOOL_URL = 'https://husnainblogger.com/tools/blogging-seo/breadcrumb-schema-generator/';

export const inputs: ToolInput[] = [
  {
    id: 'crumbs',
    label: 'Breadcrumb trail',
    type: 'textarea',
    required: true,
    placeholder: 'Home ||| https://example.com/\nBlog ||| https://example.com/blog/',
  },
  {
    id: 'baseUrl',
    label: 'Base URL (optional)',
    type: 'url',
    required: false,
    placeholder: 'https://example.com (resolves relative crumb URLs)',
  },
];

export const outputs: ToolOutput[] = [
  {
    id: 'jsonLd',
    label: 'JSON-LD markup (copy)',
    type: 'copy',
    description: 'Free breadcrumb schema generator 2026: Valid schema.org BreadcrumbList JSON-LD with positions. Instant, private, and mobile-friendly. No signup - try it free!',
  },
  {
    id: 'errors',
    label: 'Validation notes',
    type: 'list',
    description: 'Crumbs that were skipped and why (bad or relative URLs).',
  },
];

export const content: ToolContent = {
  title: 'Breadcrumb Schema Generator',
  description:
    'Generate valid breadcrumb schema JSON-LD for your pages in seconds. Enter names and URLs, then copy the markup with correct positions. Try it free now!',
  howTo: [
    'Enter your "Breadcrumb trail" — one crumb per line as: Name ||| URL.',
    'Optionally add a "Base URL" so relative crumb URLs (like /blog/) resolve to absolute URLs.',
    'Run the tool (up to 10 crumbs) and check "Validation notes" for skipped crumbs.',
    'Copy the "JSON-LD markup" into your page and test it in Google\'s Rich Results Test.',
  ],
  methodology:
    'This tool formats your crumbs into a schema.org BreadcrumbList JSON-LD block, assigning sequential positions starting at 1 (positions stay sequential even when a crumb is skipped). Absolute http(s) URLs pass through; relative URLs resolve against the optional Base URL; a relative URL with no Base URL is skipped and reported. No URLs are fetched or checked over the network, and nothing is generated by AI.',
  examples: [
    {
      title: 'Three-level trail',
      inputs: {
        crumbs: 'Home ||| https://example.com/\nBlog ||| https://example.com/blog/\nSEO Guide ||| https://example.com/blog/seo-guide/',
      },
      note: 'Classic Home → Blog → Post trail with positions 1–3.',
    },
    {
      title: 'Relative URLs with base',
      inputs: {
        crumbs: 'Home ||| /\nBlog ||| /blog/',
        baseUrl: 'https://example.com',
      },
      note: 'Relative paths resolve against the Base URL into absolute URLs.',
    },
    {
      title: 'Bad crumb reported',
      inputs: {
        crumbs: 'Home ||| https://example.com/\nBroken ||| /no-base-here/',
      },
      note: 'The relative crumb is skipped and reported; Home still generates markup.',
    },
  ],
  faqs: [
    {
      question: 'What is the best breadcrumb schema generator?',
      answer:
        'The best breadcrumb schema generator builds valid schema.org BreadcrumbList JSON-LD with correct sequential positions, handles relative URLs, and needs no signup. This tool does all three — enter your trail, copy the markup, and test it in Google\'s Rich Results Test.',
    },
    {
      question: 'Is there a free breadcrumb schema generator?',
      answer:
        'Yes — this breadcrumb schema generator is completely free with no signup. Enter up to 10 crumbs with names and URLs, then copy the ready-to-paste JSON-LD.',
    },
    {
      question: 'How to generate breadcrumb schema?',
      answer:
        'List your breadcrumb trail as one "Name ||| URL" per line (adding a Base URL if you use relative paths), run the tool, then copy the generated BreadcrumbList JSON-LD into your page. Test the live page in Google\'s Rich Results Test to confirm it is detected.',
    },
    {
      question: 'How does a breadcrumb schema generator work?',
      answer:
        'It takes your breadcrumb names and URLs and assembles them into a schema.org BreadcrumbList JSON-LD block with numbered ListItem positions. Nothing is written by AI — the tool only formats the trail you provide into valid markup.',
    },
    {
      question: 'How does the breadcrumb schema generator work?',
      answer:
        'Enter your details using the inputs above and the breadcrumb schema generator calculates everything instantly in your browser. No data leaves your device, and you get results the moment you change any value.',
    },
    {
      question: 'Is the breadcrumb schema generator free to use?',
      answer:
        'Yes - this breadcrumb schema generator is completely free with no signup, no account, and no usage limits. It runs 100% in your browser.',
    },
    {
      question: 'What is a breadcrumb schema generator?',
      answer:
        'A breadcrumb schema generator is a free online tool that gives you quick, accurate results without spreadsheets or manual math. This version runs entirely in your browser for instant, private results.',
    },
  ],
  assumptions: [
    'Relative URLs are only resolved when you provide a Base URL; otherwise they are skipped and reported.',
    'The markup reflects the crumb names and URLs you typed — the tool cannot verify they match your site\'s real navigation, and no URL is fetched.',
    'Google recommends breadcrumb markup mirror the visible breadcrumb trail on the page.',
  ],
  jsonLd: [
    {
      '@type': 'SoftwareApplication',
      name: 'Breadcrumb Schema Generator 2026 – Free | HusnainBlogger',
      url: TOOL_URL,
      applicationCategory: 'Utilities',
      operatingSystem: 'Web',
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      description: 'Free breadcrumb schema generator 2026: Valid schema.org BreadcrumbList JSON-LD with positions. Instant, private, and mobile-friendly. No signup - try it free!',
    },
    {
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://husnainblogger.com/' },
        { '@type': 'ListItem', position: 2, name: 'Tools', item: 'https://husnainblogger.com/tools/' },
        {
          '@type': 'ListItem',
          position: 3,
          name: 'Blogging SEO & Content',
          item: 'https://husnainblogger.com/tools/blogging-seo/',
        },
        {
          '@type': 'ListItem',
          position: 4,
          name: 'Breadcrumb Schema Generator',
          item: TOOL_URL,
        },
      ],
    },
  ],
};
