import type { ToolInput, ToolOutput } from '../../../src/lib/registry/types.ts';
import type { ToolContent } from '../../../src/templates/types.ts';

const TOOL_URL = 'https://husnainblogger.com/tools/creator-business/overdue-invoice-reminder-generator/';

export const inputs: ToolInput[] = [
  {
    id: 'clientName',
    label: 'Client name',
    type: 'text',
    required: true,
    placeholder: 'e.g. Acme Studio',
  },
  {
    id: 'invoiceNumber',
    label: 'Invoice number',
    type: 'text',
    required: true,
    placeholder: 'e.g. INV-2026-041',
  },
  {
    id: 'amountDue',
    label: 'Amount due',
    type: 'number',
    required: true,
    placeholder: 'e.g. 1250',
    validation: { min: 0 },
  },
  {
    id: 'daysOverdue',
    label: 'Days overdue',
    type: 'number',
    required: true,
    placeholder: 'e.g. 21',
    validation: { min: 0 },
  },
  {
    id: 'escalationLevel',
    label: 'Tone',
    type: 'select',
    required: true,
    options: ['polite', 'firm', 'final'],
  },
  {
    id: 'senderName',
    label: 'Your name (sign-off)',
    type: 'text',
    required: false,
    placeholder: 'e.g. Husnain',
  },
];

export const outputs: ToolOutput[] = [
  {
    id: 'reminderEmailDraft',
    label: 'Reminder email draft (copy)',
    type: 'copy',
    description:
    'Free overdue invoice reminder email 2026: 2 subject-line options plus the full reminder email body, ready to copy and send. Fast, private.',
  },
];

export const content: ToolContent = {
  title: 'Overdue Invoice Reminder Email',
  description:
    'Write an overdue invoice reminder email in seconds. Pick polite, firm, or final tone, enter the invoice details, and copy your draft. Try it free now.',
  howTo: [
    'Enter the client name, invoice number, amount due, and how many days overdue the invoice is.',
    'Pick a tone: polite for a first nudge, firm for a second follow-up, final for a last written warning.',
    'Optionally add your name for the sign-off.',
    'Run the tool, choose one of the 2 subject lines, and copy the email body.',
    'Paste it into your email client and send — the tool never sends anything itself.',
  ],
  methodology:
    'This tool fills fixed human-written templates with your invoice details: 3 escalation levels, each with 2 subject-line templates and 1 body template (6 subjects + 3 bodies total). Amounts are shown with 2 decimals and no currency symbol, so your own invoice currency applies. The "final" tone suggests seeking independent advice if payment stays unresolved — it never makes legal threats or claims. Nothing is generated by AI, and nothing is sent automatically.',
  examples: [
    {
      title: 'First polite nudge',
      inputs: {
        clientName: 'Acme Studio',
        invoiceNumber: 'INV-2026-041',
        amountDue: 1250,
        daysOverdue: 21,
        escalationLevel: 'polite',
        senderName: 'Husnain',
      },
      note: 'A friendly reminder draft with 2 subject options — best for the first follow-up.',
    },
    {
      title: 'Firm second follow-up',
      inputs: {
        clientName: 'Bright Agency',
        invoiceNumber: 'INV-2026-038',
        amountDue: 800,
        daysOverdue: 45,
        escalationLevel: 'firm',
      },
      note: 'Asks for a concrete payment date while keeping the door open to resolve invoice issues.',
    },
    {
      title: 'Final written reminder',
      inputs: {
        clientName: 'Northwind Co',
        invoiceNumber: 'INV-2026-012',
        amountDue: 2400,
        daysOverdue: 90,
        escalationLevel: 'final',
      },
      note: 'Sets a 7-day deadline and mentions seeking independent advice — no legal threats are made.',
    },
  ],
  faqs: [
    {
      question: 'What is the best overdue invoice reminder email?',
      answer:
        'The best reminder is short, factual, and escalates in tone: start polite, then firm, then final. Each email should name the invoice number, the exact amount, and how many days overdue it is, plus one clear ask. This free generator writes all three tones for you from your invoice details.',
    },
    {
      question: 'Is there a free overdue invoice reminder email?',
      answer:
        'Yes — this overdue invoice reminder generator is completely free with no signup. Enter the client name, invoice number, amount, and days overdue, pick polite, firm, or final tone, and copy the draft.',
    },
    {
      question: 'How to use overdue invoice reminder email?',
      answer:
        'Fill in the invoice details and choose the tone that matches how many times you have already chased payment. Run the tool, pick a subject line, copy the body into your email client, and send it yourself — the tool drafts only, it never sends.',
    },
    {
      question: 'How does the overdue invoice reminder email work?',
      answer:
        'Enter your details using the inputs above and the overdue invoice reminder email calculates everything instantly in your browser. No data leaves your device, and you get results the moment you change any value.',
    },
    {
      question: 'Is the overdue invoice reminder email free to use?',
      answer:
        'Yes - this overdue invoice reminder email is completely free with no signup, no account, and no usage limits. It runs 100% in your browser.',
    },
    {
      question: 'What is an overdue invoice reminder email?',
      answer:
        'An overdue invoice reminder email is a free online tool that gives you quick, accurate results without spreadsheets or manual math. This version runs entirely in your browser for instant, private results.',
    },
    {
      question: 'Do I need to create an account to use the overdue invoice reminder email?',
      answer:
        'No account needed. Open the overdue invoice reminder email, enter your values, and see results immediately - nothing is stored or sent anywhere.',
    },
  ],
  assumptions: [
    'The tool drafts a reminder email only — it does not send emails, add late fees, or change what you are owed. Any late fee must come from terms you already agreed with the client.',
    'The "final" tone suggests seeking independent advice; it is not legal advice and makes no legal claims on your behalf.',
    'Amounts are shown without a currency symbol — the figures refer to whatever currency your invoice uses.',
  ],
  jsonLd: [
    {
      '@type': 'SoftwareApplication',
      name: 'Overdue Invoice Reminder Email 2026 – Free | HusnainBlogger',
      url: TOOL_URL,
      applicationCategory: 'Utilities',
      operatingSystem: 'Web',
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      description:
    'Free overdue invoice reminder email 2026: 2 subject-line options plus the full reminder email body, ready to copy and send. Fast, private.',
    },
    {
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://husnainblogger.com/' },
        { '@type': 'ListItem', position: 2, name: 'Tools', item: 'https://husnainblogger.com/tools/' },
        {
          '@type': 'ListItem',
          position: 3,
          name: 'Creator Business',
          item: 'https://husnainblogger.com/tools/creator-business/',
        },
        {
          '@type': 'ListItem',
          position: 4,
          name: 'Overdue Invoice Reminder Generator',
          item: TOOL_URL,
        },
      ],
    },
  ],
};
