import type { ToolInput, ToolOutput } from '../../../src/lib/registry/types.ts';
import type { ToolContent } from '../../../src/templates/types.ts';

const TOOL_URL = 'https://husnainblogger.com/tools/video-editing/transition-idea-generator/';

export const inputs: ToolInput[] = [
  {
    id: 'fromScene',
    label: 'First scene',
    type: 'text',
    required: true,
    placeholder: 'e.g. talking head in the office',
  },
  {
    id: 'toScene',
    label: 'Second scene',
    type: 'text',
    required: true,
    placeholder: 'e.g. running outside at night',
  },
  {
    id: 'energy',
    label: 'Energy',
    type: 'select',
    required: true,
    options: ['calm', 'punchy'],
  },
  {
    id: 'count',
    label: 'Number of ideas',
    type: 'number',
    required: false,
    placeholder: '5',
    validation: { min: 1, max: 10 },
  },
];

export const outputs: ToolOutput[] = [
  {
    id: 'ideas',
    label: 'Transition ideas',
    type: 'list',
    description: 'Free video transition ideas 2026: Ranked transition ideas, each with a name, step-by-step CapCut how-to, and difficulty. Fast, private, no signup - try it now!',
  },
  {
    id: 'matchReason',
    label: 'Why these were picked',
    type: 'text',
    description: 'A plain-English explanation of the matching rules used to rank the ideas.',
  },
];

export const content: ToolContent = {
  title: 'Video Transition Ideas 2026 – Free Tool | HusnainBlogger',
  description:
    'Find video transition ideas matched to your two scenes and energy — smooth, punchy, and match-cut picks with step-by-step CapCut how-tos. Plan your edit now!',
  howTo: [
    'Describe the clip you are leaving (first scene) and the clip you are entering (second scene).',
    'Pick the energy: calm for smooth, punchy for high-impact transitions.',
    'Choose how many ideas you want (1-10, default 5).',
    'Run the tool and read why each idea was picked for your scenes.',
    'Follow the CapCut how-to steps to build each transition on the timeline.',
  ],
  methodology:
    'The tool matches your scenes against a fixed bank of 30 hand-written transitions across 6 families (match-cut, smooth, punchy, mask, creative, retro). If both scenes are identical it limits suggestions to match cuts; calm energy excludes punchy-only transitions; scene keywords (motion, indoor, outdoor, day, night, zoom, object) boost the ranking. CapCut steps are fixed human instructions. Nothing is generated by AI.',
  examples: [
    {
      title: 'Office to night run',
      inputs: { fromScene: 'talking head in the office', toScene: 'running outside at night', energy: 'punchy', count: 5 },
      note: 'Punchy picks ranked first: whip pan, glitch cut, shake cut.',
    },
    {
      title: 'Same scene twice',
      inputs: { fromScene: 'person walks through door', toScene: 'person walks through door', energy: 'calm', count: 3 },
      note: 'Identical scenes trigger the match-cut family only.',
    },
  ],
  faqs: [
    {
      question: 'What is the best video transition ideas?',
      answer:
        'The best transition is the one that matches your scene change: match cuts for identical scenes, smooth dissolves for calm mood shifts, and whip pans or glitches for high-energy moments. This free tool ranks ideas for your exact scenes and energy instead of giving a generic list.',
    },
    {
      question: 'Is there a free video transition ideas?',
      answer:
        'Yes — this video transition ideas tool is completely free with no signup. Describe your two scenes, pick calm or punchy energy, and get ranked ideas with CapCut how-to steps instantly.',
    },
    {
      question: 'How to use video transition?',
      answer:
        'In CapCut, tap the transition icon between two clips and pick the style and duration, or build it manually by cutting on matching motion between the clips. This tool tells you which transition type fits your scenes and gives you the exact steps to build it.',
    },
    {
      question: 'How does a video transition ideas work?',
      answer:
        'You describe the two scenes and the energy, and the tool matches them against a fixed bank of 30 hand-written transitions using fixed rules: identical scenes get match cuts, calm energy excludes punchy transitions, and scene keywords adjust the ranking. Nothing is AI-generated — the bank and rules are curated.',
    },
    {
      question: 'How does the video transition ideas work?',
      answer:
        'Enter your details using the inputs above and the video transition ideas calculates everything instantly in your browser. No data leaves your device, and you get results the moment you change any value.',
    },
    {
      question: 'Is the video transition ideas free to use?',
      answer:
        'Yes - this video transition ideas is completely free with no signup, no account, and no usage limits. It runs 100% in your browser.',
    },
    {
      question: 'What is a video transition ideas?',
      answer:
        'A video transition ideas is a free online tool that gives you quick, accurate results without spreadsheets or manual math. This version runs entirely in your browser for instant, private results.',
    },
  ],
  assumptions: [
    'The bank holds 30 curated transitions; it does not cover every CapCut effect or third-party plugin transition.',
    'CapCut menu names change between app versions — if a named menu item moved, look for the same feature under the Effects or Transition tabs.',
    'Scene matching uses simple keyword spotting on your descriptions, not video analysis, so vague descriptions give less targeted picks.',
  ],
  jsonLd: [
    {
      '@type': 'SoftwareApplication',
      name: 'Video Transition Ideas 2026 – Free Tool | HusnainBlogger',
      url: TOOL_URL,
      applicationCategory: 'Utilities',
      operatingSystem: 'Web',
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      description: 'Free video transition ideas 2026: Ranked transition ideas, each with a name, step-by-step CapCut how-to, and difficulty. Fast, private, no signup - try it now!',
    },
    {
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://husnainblogger.com/' },
        { '@type': 'ListItem', position: 2, name: 'Tools', item: 'https://husnainblogger.com/tools/' },
        {
          '@type': 'ListItem',
          position: 3,
          name: 'Video Editing Tools',
          item: 'https://husnainblogger.com/tools/video-editing/',
        },
        {
          '@type': 'ListItem',
          position: 4,
          name: 'Transition Idea Generator',
          item: TOOL_URL,
        },
      ],
    },
  ],
};
