import type { ToolInput, ToolOutput } from '../../../src/lib/registry/types.ts';
import type { ToolContent } from '../../../src/templates/types.ts';

const TOOL_URL = 'https://husnainblogger.com/tools/blogging-seo/star-rating-box-generator/';

export const inputs: ToolInput[] = [
  {
    id: 'rating',
    label: 'Rating (0–5)',
    type: 'number',
    required: true,
    placeholder: '4.5',
    validation: { min: 0, max: 5 },
  },
  {
    id: 'title',
    label: 'Box title (optional)',
    type: 'text',
    required: false,
    placeholder: 'Our rating',
  },
  {
    id: 'reviewCount',
    label: 'Review count (optional)',
    type: 'number',
    required: false,
    placeholder: '12',
    validation: { min: 0 },
  },
];

export const outputs: ToolOutput[] = [
  {
    id: 'boxHtml',
    label: 'Box HTML (copy)',
    type: 'copy',
    description:
    'Free star rating generator 2026: Ready-to-paste star rating box with minimal inline styles — works in any blog theme. Fast, private now.',
  },
  {
    id: 'boxCss',
    label: 'Box CSS (copy)',
    type: 'copy',
    description:
    'Optional matching CSS block — the HTML already carries inline styles, so this is skippable.',
  },
];

export const content: ToolContent = {
  title: 'Star Rating Generator',
  description:
    'Generate a clean star rating box for your reviews in seconds. Set your 0–5 rating, copy the ready-to-paste HTML, and drop it into any post. Try it free.',
  howTo: [
    'Enter your "Rating" — any number from 0 to 5, including fractions like 4.5.',
    'Optionally add a "Box title" and a "Review count" to show next to the stars.',
    'Run the tool and review the star box preview.',
    'Copy the "Box HTML" and paste it into your post\'s HTML or Custom HTML block. Add the "Box CSS" to your theme only if you want to restyle it.',
  ],
  methodology:
    'Your rating is rendered as two star rows: a gray row of five stars with a gold row clipped on top at rating ÷ 5 × 100% width, so fractional ratings like 4.3 show a partially filled star. The title and review count are HTML-escaped (so nothing you type can inject markup), and styling is intentionally minimal and inline so the snippet works in any blog theme. Nothing is generated by AI — the stars reflect the number you enter.',
  examples: [
    {
      title: 'Product review',
      inputs: { rating: 4.5, title: 'Our rating', reviewCount: 12 },
      note: 'A 4.5-star box with title and review count.',
    },
    {
      title: 'Fractional rating only',
      inputs: { rating: 3.7 },
      note: 'Just the stars and the "3.7 out of 5" line, no title or count.',
    },
    {
      title: 'Perfect score',
      inputs: { rating: 5, title: "Editor's choice", reviewCount: 1 },
      note: 'Full gold stars with singular "1 review".',
    },
  ],
  faqs: [
    {
      question: 'What is the best star rating generator?',
      answer:
        'The best star rating generator renders fractional ratings accurately as clean HTML you can paste into any blog theme, with no signup. This tool does that — set any 0–5 rating and get an inline-styled star box plus an optional CSS block, free.',
    },
    {
      question: 'Is there a free star rating generator?',
      answer:
        'Yes — this star rating generator is completely free with no signup. Generate as many rating boxes as you need, with optional titles and review counts.',
    },
    {
      question: 'How to generate star rating?',
      answer:
        'Enter your rating from 0 to 5 (fractions like 4.5 work), optionally add a title and review count, then run the tool. Copy the generated HTML into your post\'s HTML or Custom HTML block and the star box appears in your article.',
    },
    {
      question: 'How does a star rating generator work?',
      answer:
        'It takes the rating you enter and renders it as a gold star row clipped over a gray star row, so partial ratings show a partially filled star. The markup carries minimal inline styles that work in any blog theme, and nothing is written by AI — the stars reflect your number.',
    },
    {
      question: 'How does the star rating generator work?',
      answer:
        'Enter your details using the inputs above and the star rating generator calculates everything instantly in your browser. No data leaves your device, and you get results the moment you change any value.',
    },
    {
      question: 'Is the star rating generator free to use?',
      answer:
        'Yes - this star rating generator is completely free with no signup, no account, and no usage limits. It runs 100% in your browser.',
    },
    {
      question: 'What is a star rating generator?',
      answer:
        'A star rating generator is a free online tool that gives you quick, accurate results without spreadsheets or manual math. This version runs entirely in your browser for instant, private results.',
    },
  ],
  assumptions: [
    'Styling is intentionally minimal and inline so the snippet works in any blog theme — customize the CSS block for a branded look.',
    'All content is HTML-escaped; you cannot inject raw HTML, scripts, or attributes through this tool.',
    'The tool formats the rating you enter — it does not verify, source, or aggregate ratings.',
    'Fractional fills are rounded to one decimal place of the star-row width.',
  ],
  jsonLd: [
    {
      '@type': 'SoftwareApplication',
      name: 'Star Rating Generator 2026 – Free Tool | HusnainBlogger',
      url: TOOL_URL,
      applicationCategory: 'Utilities',
      operatingSystem: 'Web',
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      description:
    'Free star rating generator 2026: Ready-to-paste star rating box with minimal inline styles — works in any blog theme. Fast, private now.',
    },
    {
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://husnainblogger.com/' },
        { '@type': 'ListItem', position: 2, name: 'Tools', item: 'https://husnainblogger.com/tools/' },
        {
          '@type': 'ListItem',
          position: 3,
          name: 'Blogging & SEO Tools',
          item: 'https://husnainblogger.com/tools/blogging-seo/',
        },
        {
          '@type': 'ListItem',
          position: 4,
          name: 'Star Rating Box Generator',
          item: TOOL_URL,
        },
      ],
    },
  ],
};
